### ISSUE TITLE
Support for min(date) and max(date)

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#100]
Is min(date) supported ? I want to pull the min(date) and delete from Elasticsearch. However when I run the min(date), I am not getting the correct result

SELECT min(test_date),test_date_dd,test_date_mm,test_date_yy,test_date FROM xxxxx/test_locs 

Results
---------------
MIN(test_date)
 1440288000000

The test_date_dd is a integer field - which has values of 2,3,4,5,6,7,8,9. However min(test_date_dd) retunds 1 and max(test_date_dd) returns 31

SELECT min(test_date_dd),test_date_dd,test_date_mm,test_date_yy,test_date FROM xxxxxx/test_locs 

Results
------------
MIN(test_date_dd)
 1 

SELECT max(test_date_dd),test_date_dd,test_date_mm,test_date_yy,test_date FROM xxxxxx/test_locs 

Results
-------------
MAX(test_date_dd)
 31

**Comment by eliranmoyal** [comment]
On your first example, I saw the problem , I will make a fix that will take the "value_as_string" for such fields.
I don't understand the 2nd example. what is the mapping of test_date_dd?

**Comment by satapsa** [comment]
That is is the day part of the date. Ex if the date is 2015-09-02 00:00:00, test_date_dd is 2.
test_date_dd is of type 'integer' and test_date is of type 'date' of format "YYYY-MM-dd HH:mm:ss"

Query and Result below
SELECT test_date_dd,test_date_dd,test_date_mm,test_date_yy,test_date FROM xxxxxxx/test_locs limit 2

Results
---------------
test_date                        test_date_yy  test_date_mm  test_date_dd
 2015-09-02 00:00:00     2015                     9                    2 
2015-09-03 00:00:00      2015                     9                    3

**Comment by eliranmoyal** [comment]
ok thats wierd, its working fine on my elastic. can you give me the result of
http://yourHost:9200/_sql?sql=select min(test_date_dd) from  xxxxxxx/test_locs

**Comment by satapsa** [comment]
"aggregations":{"MIN(test_date)":{"value":1.4401152E12,"value_as_string":"2015-08-21 00:00:00"}}}

I believe if it can return the result as "value_as_string", we can get the correct value for test_date.

**Comment by eliranmoyal** [comment]
Good, I'll fix it this weekend

**Comment by eliranmoyal** [comment]
check the newest version 
https://github.com/NLPchina/elasticsearch-sql/releases/tag/1.4.4
