### ISSUE TITLE
REST API with Scroll to fetch 100 K records with CSV Output

### ISSUE THREAD

**Issue by rkhapre** [NLPchina/elasticsearch-sql#1007]
Hi

I am using this sql query to fetch 100K records
Select /*! USE_SCROLL*/ * from index

by rest API with GET : http://localhost:9001/_sql?flat=true&format=csv

With this I get only first 50 Records, what should i do get next 50 and how it can automatically keep going till the end to fetch all 100K records

Can we do this in POSTMAN to check?

My ultimate Goal is to use this API to fetch all the records

Now i saw this  
https://github.com/NLPchina/elasticsearch-sql/issues/613#issuecomment-388630388

But how i will get the Scroll ID from my CSV output?

**Comment by shi-yuan** [comment]
http://localhost:9001/_sql?flat=true&format=csv&_scroll_id=true

**Comment by rkhapre** [comment]
Hi 

Is this fix is available in 6.8.4 branch?

**Comment by shi-yuan** [comment]
Of course
