### ISSUE TITLE
Not getting the correct order of columns when writing the column in right sequence

### ISSUE THREAD

**Issue by rkhapre** [NLPchina/elasticsearch-sql#1008]
Not getting the correct order of columns when writing the column in right sequence

http://xxxx:9200/_sql?flat=true&format=csv&sql=select Object,P0,P1,P2,Count from index

select Object,P0,P1,P2,Count from index

I get the response like this below, the columns are jumbled. How to fix this?

P0,P1,P2,Object,Count
,2,,A005,2
,,2,A006,2
5,,,A001,5
,3,,A002,3
4,,,A003,4
I need the response in this order
Object,P0,P1,P2,Count
because in sql i am requesting in same order

Thanks

How to achieve the correct order here.?

**Comment by rkhapre** [comment]
Hi @shi-yuan 
I am trying to install 6.8.4.2 but not able to install. I think you made fixes in 6.8.4 branch
But when i install your fixes does not reflect

elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/6.8.4.0/elasticsearch-sql-6.8.4.0.zip

i tried this also

elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/6.8.4.2/elasticsearch-sql-6.8.4.2.zip

**Comment by shi-yuan** [comment]
you can package by youself，then unzip it to ES_HOME/plugins/sql

**Comment by rkhapre** [comment]
How can i package it, any example, because under folder ES_HOME/pugins/sql everything is jar file

and how can i take all the files from Github, i do not see any tags for 6.8.4

please suggests

**Comment by shi-yuan** [comment]
![image](https://user-images.githubusercontent.com/8057153/69915798-1b0d7600-148e-11ea-90a2-c7efb336be32.png)，just you need

[elasticsearch-sql-6.8.4.0.zip](https://github.com/NLPchina/elasticsearch-sql/files/3908321/elasticsearch-sql-6.8.4.0.zip)

**Comment by rkhapre** [comment]
that means i can uninstall and install it directly
elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/6.8.4.0/elasticsearch-sql-6.8.4.0.zip

**Comment by shi-yuan** [comment]
unzip [elasticsearch-sql-6.8.4.0.zip](https://github.com/NLPchina/elasticsearch-sql/files/3908321/elasticsearch-sql-6.8.4.0.zip) to ES_HOME/plugins/sql
