### ISSUE TITLE
Delete and SELECT records less than a date

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#101]
How can I delete records which are less than a today-15 ? 

Ex: For select
select test_date FROM xxxx/test_locs test_date < 2015-09-29 00:00:00

**Comment by eliranmoyal** [comment]
use elastic time format in string like this
SELECT test_date FROM  xxxx/test_locs WHERE anotherTime < '2015-09-29T00:00:00'

**Comment by satapsa** [comment]
SELECT test_date FROM xxxx/test_locs WHERE test_date < now-15d works fine. However when I am trying to delete am not able to

curl -XDELETE 'http://xxxxxx:9200/_sql?sql=SELECT test_date FROM xxxxxx/test_locs WHERE test_date < now-15d'
curl: (52) Empty reply from server

Is there a delete option in the sql plugin ?

**Comment by satapsa** [comment]
I am getting the following error when running the delete statement on the sql Web interface

DELETE FROM xxxxxx/test_locs WHERE test_date < now-15d

Error:{"error":"ActionRequestValidationException[Validation Failed: 1: source is missing;]","status":400}

**Comment by eliranmoyal** [comment]
Oh, I never used the delete statement before.. I'll have a look at it on the weekend

**Comment by satapsa** [comment]
Thank you

**Comment by eliranmoyal** [comment]
check the newest version , it have a fix for it
https://github.com/NLPchina/elasticsearch-sql/releases/tag/1.4.4
