### ISSUE TITLE
查询条件带特殊字符报错

### ISSUE THREAD

**Issue by yuhuo123** [NLPchina/elasticsearch-sql#1049]
版本6.4.2
使用查询:curl "http://localhost:9200/_sql?sql=select+*+from+test+where+url=%22http://www.test.com/h1/#/end.jsp%22"
带有'#'会报错：
{"error":{"root_cause":[{"type":"parser_exception","reason":"ERROR. token : ERROR, pos : 53"}],"type":"parser_exception","reason":"ERROR. token : ERROR, pos : 53"},"status":500}

**Comment by shi-yuan** [comment]
```bash
curl -X GET "localhost:9200/_sql" -H 'Content-Type: application/json' -d'
{
    "sql" : "select * from test where url=\"http://www.test.com/h1/#/end.jsp\""
}
'
```
