### ISSUE TITLE
Could not find plugin descriptor 'plugin-descriptor.properties' in plugin

### ISSUE THREAD

**Issue by robertsmarty** [NLPchina/elasticsearch-sql#105]
I think elasticsearch 2.0.0 processes plugins differently. Can someone please confirm how I should go about installing with 2.0.0? I'm receiving this error...

ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by eliranmoyal** [comment]
Hey, we do not support elasticsearch 2.0 yet. I hope I will able to make a new version in the next couple of weeks

**Comment by eliranmoyal** [comment]
check the new release
https://github.com/NLPchina/elasticsearch-sql/releases/tag/2.0.0

**Comment by robertsmarty** [comment]
Excited. Thanks!
