### ISSUE TITLE
请问可以把elasticsearch-sql.jar新版本的包发布到中央maven库么?

### ISSUE THREAD

**Issue by gpdream** [NLPchina/elasticsearch-sql#1053]
在应用里现在使用了elasticsearch-sql.jar,现在maven仓库里最新版本是6.3.0,想要用7.0的jar包，请问有计划把这个jar包发到中央maven仓库的计划么?

```xml
       <groupId>org.nlpcn</groupId>
	<artifactId>elasticsearch-sql</artifactId>
	<version>6.3.0.0</version>
```

![image](https://user-images.githubusercontent.com/24906614/78789855-4b3ac780-79e0-11ea-8322-61b05695c643.png)

**Comment by shi-yuan** [comment]
已将最新的7.8发布了
