### ISSUE TITLE
HIGHLIGHT 是否支持多字段高亮？

### ISSUE THREAD

**Issue by anonyonmous** [NLPchina/elasticsearch-sql#1058]
select /*! HIGHLIGHT[(content ,pre_tags : ['<en>'], post_tags : ['</en>'] ) ,(title ,pre_tags : ['<en>'], post_tags : ['</en>'] )]  */  * from table where content like '大吉大利'

这个sql只能高亮content字段，但是我想把content和title两个字段都高亮显示，现在的插件是否支持？

-- 谢谢

**Comment by shi-yuan** [comment]
```sql
select /*! HIGHLIGHT(name,pre_tags : ['<b>'],post_tags : ['</b>'])*/ /*! HIGHLIGHT(content,pre_tags : ['<b>'],post_tags : ['</b>']) */ * from table where name like "大吉大利" or content like "大吉大利"
```
