### ISSUE TITLE
Support elasticsearch 2.0

### ISSUE THREAD

**Issue by ofir-petrushka** [NLPchina/elasticsearch-sql#106]
I think it might be something trvial to change in the release layout or something.
Elasticseach changed the way things are installed, you don't give package name anymore...
https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/installation.html

Didn't work for me at least, maybe I just don't know how and we just need to document it.

**Comment by eliranmoyal** [comment]
I checked and there are major api changes between the versions (no more Filters only queries , delete by query is now a plugin etc..) so I need to compile against the new version and make all tests pass..

**Comment by eliranmoyal** [comment]
check the new release 
https://github.com/NLPchina/elasticsearch-sql/releases/tag/2.0.0
