### ISSUE TITLE
sql插件报错 invalid_index_name_exception

### ISSUE THREAD

**Issue by zachzzq** [NLPchina/elasticsearch-sql#1060]
sql：SELECT * FROM test
不管我使用什么index，都会抛出这个错误
{"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_nlpcn], must not start with '_', '-', or '+'","index_uuid":"_na_","index":"_nlpcn"}],"type":"invalid_index_name_exception","reason":"Invalid index name [_nlpcn], must not start with '_', '-', or '+'","index_uuid":"_na_","index":"_nlpcn"},"status":400}

**Comment by shi-yuan** [comment]
用的7.5.0之后的吧，更换了path的
