### ISSUE TITLE
Cannot open the url http://essql.nlpcn.org/

### ISSUE THREAD

**Issue by gecailong** [NLPchina/elasticsearch-sql#1070]
Cannot open the url http://essql.nlpcn.org/ and view the corresponding document information

**Comment by gecailong** [comment]
I am located in China, but I have used a ladder.How do I see the documentation information and examples？

**Comment by shi-yuan** [comment]
Alternatively，you can start es，then use [elasticsearch sql site chrome extension](https://github.com/shi-yuan/elasticsearch-sql-site-chrome)

**Comment by lucaspottersky** [comment]
http://essql.nlpcn.org is opening crazy ads sites for me.

**Comment by ansjsun** [comment]
I'm sorry because the org domain name can't be authenticated. I've lost the ownership of this domain name




On 06/27/2020 09:56, Lucas Pottersky wrote:

http://essql.nlpcn.org is opening crazy ads sites for me.
