### ISSUE TITLE
ORDER BY **,++ DESC doesnt work

### ISSUE THREAD

**Issue by aitanjupt** [NLPchina/elasticsearch-sql#108]
`ORDER BY ** DESC` works, but `ORDER BY **, ++ DESC` and `ORDER BY ** DESC, ++ ASC` doesn't work.

**Comment by eliranmoyal** [comment]
Checked it and found that this is only bug on new table presenter. will fix on new version.
You can use the previous presenter with the option: useOldTable on the right side of the UI.

**Comment by eliranmoyal** [comment]
check version 1.4.6 (if you are using elastic 1.X )
and 2.0.1 (if you are using elastic 2.0.0)
it contains the fix
