### ISSUE TITLE
csv format gives wrong output if there is a comma in a field

### ISSUE THREAD

**Issue by rkhapre** [NLPchina/elasticsearch-sql#1084]
Hi All

We get a wrong csv response when we have a comma value in a field, here is the example

Currently the response is coming as below where first line is a header

URL = http://localhost:9001/_sql?separator=,
body is

```
{
  "format": "csv",
  "flat": "true",
  "showHeader": "true",
  "_scroll_id": "false",
"sql": "Select field1,field2 from index"
}

```
```
field1,field2
this is the,description,column1value1
this is the, second description,column1value2
```
expected result is 

```
field1,field2
"this is the,description",column1value1
"this is the, second description",column1value2
```

Please let me know how we can fix this? This is genuine case of csv data

Thanks

**Comment by rkhapre** [comment]
@shi-yuan , you have any solution or suggestion for this question?

**Comment by shi-yuan** [comment]
Add a parameter `quote`，when true, then
```
"field1","field2"
"this is the,description","column1value1"
"this is the, second description","column1value2"
```

**Comment by rkhapre** [comment]
You mean like this

{
  "format": "csv",
  "flat": "true",
  "showHeader": "true",
  "_scroll_id": "false",
"quote" : "true",
"sql": "Select field1,field2 from index"
}

The above one is not working

**Comment by shi-yuan** [comment]
This feature will be supported as soon as possible

**Comment by rkhapre** [comment]
okay thanks for the information, waiting for it

**Comment by rkhapre** [comment]
Hi @shi-yuan , do you have any work around for time being, i realized i need this, i am not able to move forward because of this quote issue. If you have any easy workaround please let me know i will go with it.

**Comment by rkhapre** [comment]
@shi-yuan will think work in version 6.8.6 or i need to upgrade to 6.8.10.?

**Comment by shi-yuan** [comment]
you can change `elasticsearch.version` in pom.xml, then package

**Comment by rkhapre** [comment]
@shi-yuan this is still a issue. I tried installing the plugin with 6.8.10 and 7.8.0 and i am getting below issue. Is this code is not committed?

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/_nlpcn/sql] contains unrecognized parameter: [quote]"}],"type":"illegal_argument_exception","reason":"request [/_nlpcn/sql] contains unrecognized parameter: [quote]"},"status":400}`

**Comment by shi-yuan** [comment]
use [6.8.11](https://github.com/NLPchina/elasticsearch-sql/releases/tag/6.8.11.0) and [7.8.1](https://github.com/NLPchina/elasticsearch-sql/releases/tag/7.8.1.0)

**Comment by rkhapre** [comment]
Thanks @shi-yuan , its working well
