### ISSUE TITLE
对于es存储类型为array的数据怎么查询

### ISSUE THREAD

**Issue by xihuanjin** [NLPchina/elasticsearch-sql#1086]
类似于[1,2,3,4]这样的数据怎么查

**Comment by shi-yuan** [comment]
需要怎么查？term，terms，还是match

**Comment by xihuanjin** [comment]
{"id":1,"name":xxx,"tags":[1,2,3,4]}...
我查询tag = [1,2] 应该查询出上述数据

**Comment by xihuanjin** [comment]
已经找到方法了select * from table where tag = 1 and tag =2这样可以查到，谢谢解答
