### ISSUE TITLE
support to 6.8.12

### ISSUE THREAD

**Issue by ricardo-chaves-movile** [NLPchina/elasticsearch-sql#1089]
Hi,
I use this plugin quite often. it's very useful, first of all congratulations.

Do you have any idea when this will have support for version 6.8.12?

**Comment by tiago-cruz-movile** [comment]
+1

**Comment by shi-yuan** [comment]
[6.8.12](https://github.com/NLPchina/elasticsearch-sql/releases/tag/6.8.12.0) is coming
