### ISSUE TITLE
How to judge the length of elasticsearch-sql nested array

### ISSUE THREAD

**Issue by Johnhz** [NLPchina/elasticsearch-sql#1092]
![image](https://user-images.githubusercontent.com/4067322/94509852-e2723080-0247-11eb-9a2a-33ff4fe7a1ee.png)

like this none_pay_course_list has 4 objects 
{
	"none_pay_course_list": [{
		"course": "11_30"
	}, {
		"course": "11_37"
	}, {
		"course": "11_23"
	}, {
		"course": "11_38"
	}]
}

how can I find out that the length of none_pay_course_list is 4 by querying.

I have a scenario to judge that a user has one and only one, I need to judge the length of the nested array while querying

**Comment by shi-yuan** [comment]
```sql
SELECT script('nested_field_size','params._source.none_pay_course_list.size()') FROM myindex
```

**Comment by Johnhz** [comment]
ok thanks
