### ISSUE TITLE
es 6.7.1版本 sql查询报错

### ISSUE THREAD

**Issue by chen-ABC** [NLPchina/elasticsearch-sql#1097]
![image](https://user-images.githubusercontent.com/30097790/96205446-2af45280-0f99-11eb-8082-a43e2634d44d.png)

我是mac本地安装的es服务,我也确定我安装插件后重启了项目.
![image](https://user-images.githubusercontent.com/30097790/96205485-49f2e480-0f99-11eb-9eba-4a36dab9f333.png)

**Comment by shi-yuan** [comment]
客户端版本，有问题

以前7.5.0，path都是以/_sql打头的，以后由于和官方冲突了改成了/_nlpcn打头了

**Comment by shi-yuan** [comment]
客户端版本得降级

**Comment by Dennyxiaowe** [comment]
es7.7.0 也遇到同样的问题，curl可以访问，web UI不行。
请问客户端版本降级是什么意思，有操作指引吗？没太明白。求指导。

**Comment by shi-yuan** [comment]
web ui建议直接用chrome插件：[elasticsearch-sql-site-chrome](https://github.com/shi-yuan/elasticsearch-sql-site-chrome)

**Comment by Dennyxiaowe** [comment]
> web ui建议直接用chrome插件：[elasticsearch-sql-site-chrome](https://github.com/shi-yuan/elasticsearch-sql-site-chrome)

非常感谢，已经可用了。
