### ISSUE TITLE
Installation problem met

### ISSUE THREAD

**Issue by cch123** [NLPchina/elasticsearch-sql#110]
Hi guys,
I used the instruction you provide in installation guide as
```
./bin/plugin -u https://github.com/NLPchina/elasticsearch-sql/releases/download/1.4.6/elasticsearch-sql-1.4.6.zip --install sql
```
but always timeout，as

```
-> Installing elasticsearch-sql...
Trying https://github.com/NLPchina/elasticsearch-sql/releases/download/1.4.6/elasticsearch-sql-1.4.6.zip...
Failed: ConnectException[Connection timed out]
Trying https://github.com/null/elasticsearch-sql/archive/master.zip...
Failed to install elasticsearch-sql, reason: failed to download out of all possible locations..., use --verbose to get detailed information
```

so what's the reason.
ORZ

**Comment by eliranmoyal** [comment]
Hey, I did not encounter this issue now or before.
Maby try with -t 5m 
It will set a 5minute timeout.

BWT You can always download the zip file
from here:
https://github.com/NLPchina/elasticsearch-sql/releases/download/1.4.6/elasticsearch-sql-1.4.6.zip

save it to your computer and do:
./bin/plugin -u file:///home/yourFolder/elasticsearch-sql-1.4.6.zip --install sql

**Comment by cch123** [comment]
thank you for yr help,
maybe it's because our Chinese network environment,
i download it and solved by your solution
thx!

**Comment by eliranmoyal** [comment]
Np :)
