### ISSUE TITLE
Count Distinct & Case When

### ISSUE THREAD

**Issue by diamondjira2020** [NLPchina/elasticsearch-sql#1115]
hi @shi-yuan. how can execute this query for cardinality by script mode.

`select count(distinct case when stage_tag is null then 0 when stage_tag = 2 then stage_id else 0 end ) as cnt 
from inx`

this query translate in and return 0 value
"cnt": {
      "cardinality": {
        "field": "if((doc['stage_tag'].empty)){0} else if((doc['stage_tag'].value==2)){doc['stage_id'].value} else {0}",
        "script": {
          "source": "if((doc['stage_tag'].empty)){0} else if((doc['stage_tag'].value==2)){doc['stage_id'].value} else {0}",
          "lang": "painless"
        }
      }
  }

BUT this reference say just "field" or just "script" mode 
[https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_script_4](url)

this is correct DSL query
"cnt": {
      "cardinality": {
        "script": {
          "source": "if((doc['stage_tag'].empty)){0} else if((doc['stage_tag'].value==2)){doc['stage_id'].value} else {0}",
          "lang": "painless"
        }
      }
  }

**Comment by shi-yuan** [comment]
yes,  either from specific fields in the document or generated by a script, it will be fixed

**Comment by diamondjira2020** [comment]
Thank you for your attention. Is it possible to specify a time to complete this section?

**Comment by shi-yuan** [comment]
````
{
  "from": 0,
  "size": 0,
  "_source": {
    "includes": [
      "COUNT"
    ],
    "excludes": []
  },
  "aggregations": {
    "cnt": {
      "cardinality": {
        "script": {
          "source": "if((doc['stage_tag'].empty)){0} else if((doc['stage_tag'].value==2)){doc['stage_id'].value} else {0}",
          "lang": "painless"
        }
      }
    }
  }
}
````

**Comment by diamondjira2020** [comment]
it is not working on ver 7.9.3.
:(

**Comment by diamondjira2020** [comment]
> ```json
> {
>   "from": 0,
>   "size": 0,
>   "_source": {
>     "includes": [
>       "COUNT"
>     ],
>     "excludes": []
>   },
>   "aggregations": {
>     "cnt": {
>       "cardinality": {
>         "script": {
>           "source": "if((doc['stage_tag'].empty)){0} else if((doc['stage_tag'].value==2)){doc['stage_id'].value} else {0}",
>           "lang": "painless"
>         }
>       }
>     }
>   }
> }
> ```

it is not working on ver 7.9.3. reinstall again not working
:(
