### ISSUE TITLE
Select between 2 dates

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#112]
Can you provide an example to do a select between 2 dates ?

I searched the Wiki. but could not find one.

SELECT count(*) FROM xxx/xxx where range(test_date, '2014-08-18' , '2014-08-17')

**Comment by eliranmoyal** [comment]
Sure you can just 
select * from xx/xx where test_date between '2014-08-18' and '2014-08-17'
You can also use the now keyword
select * from xx/xx where test_date between '2014-08-18' and count(*)

The date format needs to match the date format you put on your mapping

**Comment by kiakaku** [comment]
I cannot use `now-1h`
```
                    "script_stack": [
                        "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:81)",
                        "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)",
                        "doc['created'].value > doc['now-1h'].value",
                        "                           ^---- HERE"
                    ],
```

**Comment by shi-yuan** [comment]
```sql
SELECT created FROM packages-* where created > 'now-1h'
```

**Comment by kiakaku** [comment]
ok thank @shi-yuan
