### ISSUE TITLE
Cannot restart ES after installation 

### ISSUE THREAD

**Issue by AndersonTaylor** [NLPchina/elasticsearch-sql#113]
Using ES 1.3.4  in a debian based vm.
Installed the 1.x plugin
Seemed to install okay (I could load the web interface,
with the 404 error described in readme), 
but when I try to restart elasticsearch it will not come back up.

es logs:
```
[2015-11-18 16:37:05,950][INFO ][node                     ] [Night Thrasher] initializing ...
[2015-11-18 16:37:05,963][INFO ][plugins                  ] [Night Thrasher] loaded [sql], sites [sql, kopf, head]
[2015-11-18 16:37:08,788][ERROR][bootstrap                ] {1.3.4}: Initialization Failed ...
1) NoSuchMethodError[org.elasticsearch.rest.BaseRestHandler.<init>(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/rest/RestController;Lorg/elasticsearch/client/Client;)V]
```

Uninstalling sql plugin fixes the situation.  
I tried reinstalling with elasticsearch is stopped, but same result.

As you can see I also have kopf, head plugins not sure if that makes a difference.

**Comment by eliranmoyal** [comment]
I've tested the plugin with elasticsearch 1.4-1.7 .
Maby the api changed for java based plugins (kopf and head are site based )
I'll try and test it with 1.3.4 on the weekend

**Comment by eliranmoyal** [comment]
Sorry, too many changes since 1.3.4 
please upgrade your elasticsearch if you want to use this plugin.
