### ISSUE TITLE
how to init SearchDao with RestHighLevelClient

### ISSUE THREAD

**Issue by linqin07** [NLPchina/elasticsearch-sql#1133]

**Comment by linqin07** [comment]
我要使用RestHighLevelClient 来操作es-sql，可是没法转换这个关键的类，我要如何使用新客户端进行整合，es版本  7.3.2 RestHighLevelClientFactory restHighLevelClientFactory = RestHighLevelClientFactory.build("escluster", nodes, null);
  restHighLevelClie

exception
java.lang.ClassCastException: org.elasticsearch.client.RestHighLevelClient cannot be cast to org.elasticsearch.client.Client

**Comment by shi-yuan** [comment]
现在不支持的

**Comment by linqin07** [comment]
谢谢！
