### ISSUE TITLE
web 界面访问地址不对

### ISSUE THREAD

**Issue by pengpeng-fan** [NLPchina/elasticsearch-sql#1135]
版本：https://github.com/NLPchina/elasticsearch-sql/releases/download/5.4.1.0/es-sql-site-standalone.zip
es版本：7.10.2  （说明上提供的地址）
在web端访问的连接为http://ip:9200/_sql ，访问结果4000. changelog上 “Since 7.5.0.0, the path `/_sql` is changed to `/_nlpcn/sql`” ，所以请问这块是es-sql-site-standalone 版本太低吗，还是其他原因呢
如果版本太低，请发下适配的服务包下载地址，感谢

**Comment by shi-yuan** [comment]
建议直接用[elasticsearch-sql的chrome插件](https://github.com/shi-yuan/elasticsearch-sql-site-chrome)

**Comment by pengpeng-fan** [comment]
elasticsearch-sql的chrome插件 这个插件是可以的。但是我们是想把服务安装到服务器上就不用在使用的时候在安装扩展程序了。es-sql-site-standalone.zip 这个插件后续会更新适配7.55以后的服务吗

**Comment by shi-yuan** [comment]
近期会更新一版

**Comment by shi-yuan** [comment]
[es-sql-site-standalone.zip](https://github.com/NLPchina/elasticsearch-sql/files/6721637/es-sql-site-standalone.zip)
