### ISSUE TITLE
Elasticsearch response in csv format

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#114]
Can Elasticsearch response be in csv format, when a query is posted through the sql plugin ?

**Comment by eliranmoyal** [comment]
You mean when using the plugin like this:
http://xxxx:9200/_plugin/sql?sql=select * from x
?

**Comment by clover1983** [comment]
yes

I use rest API to query SQL from elasticsearch just like http://xxxx:9200/_sql?sql=select * from x

but the result is show in nested json.

How I get the result ouput like csv??

**Comment by eliranmoyal** [comment]
This is not possible right now.
I'll add this feature soon
Do you want the column names in the first row like in csv?

**Comment by clover1983** [comment]
YES
also I want all the results query by rest api show as csv format

**Comment by clover1983** [comment]
Thank you for your help, eliranmoyal

**Comment by satapsa** [comment]
That will be a very good feature to have. Please let us know when it is available.

**Comment by eliranmoyal** [comment]
Hey , I've made it possible for queries that doesn't contain aggregations.
just need to add 
http://xxxx:9200/_sql?**format=csv**&sql=select * from x
and also this avilable if you have nested objects
http://xxxx:9200/_sql?**format=csv&flat=true**&sql=select * from x
I'll try work on aggregations tomorrow but it looks a bit hard (too many types of aggregations)
anyway i'll make a release with this feature on Tuesday/Wednesday

**Comment by eliranmoyal** [comment]
The new version with this feature is out
make sure you read the wiki about it
https://github.com/NLPchina/elasticsearch-sql/wiki/CSV-result

Tell me about your experience with this feature

**Comment by satapsa** [comment]
I am on Elasticsearch 1.7 and sql plug in 1.4.8. will the csv format availbale for the same ?

**Comment by eliranmoyal** [comment]
Yeah

**Comment by satapsa** [comment]
So I donot need to do any upgrade on the plugin and it will be availble to me now ?

**Comment by eliranmoyal** [comment]
The 1.4.8 released yesterday, if you installed it than you should be able to use it

**Comment by satapsa** [comment]
Ok. My mistake. I had installed 1.4.3 a month ago. So I need to install 1.4.8 to access the new feature. Makes sense. Thanks
