### ISSUE TITLE
about nested search 

### ISSUE THREAD

**Issue by tigerone1** [NLPchina/elasticsearch-sql#115]
hi eliranmoyal，thank for your contribution for the plugin elasticsearch-sql,and before 3 days,you commit some code supporting nested search,but I find some bug,for example，I have an nested array object,like this
"comments": [
{
"name": "John Smith",
"comment": "Great article",
"age": 28,
"stars": 4,
"date": "2014-09-01"
}
,
{
"name": "Alice White",
"comment": "More like this please",
"age": 31,
"stars": 5,
"date": "2014-10-22"
}
I want to search age=28 and stars=4,how to write condition? I try search nested(comments.age)='28' and nested(comments.stars)='5',this record is hited

**Comment by eliranmoyal** [comment]
Yeah haven't finished with this feature yet, this is why it wasn't released. 
What do you say about suppprting something like this:
"where nested('comments', comments.age='28' and comments.stars='5')"?

**Comment by tigerone1** [comment]
thanks,I got it after read your code

**Comment by eliranmoyal** [comment]
I'll create a new release this weekend. I'll add an explanation on the wiki in this kind of queries.

**Comment by xlfulove** [comment]
https://github.com/NLPchina/elasticsearch-sql/issues/115#issuecomment-159181924

Is this problem fixed? , I am currently using version 5.5.0, there is still this problem
@eliranmoyal
