### ISSUE TITLE
needed help with Script and Script_Fields

### ISSUE THREAD

**Issue by mhsankar** [NLPchina/elasticsearch-sql#1151]
Hi
I'm using **Elastic version 7.9.3**
I have an index with one `text fields`. its `fielddata` is true.
I want to get all document with `length` of `text field` is bigger than 10 character
and this is my code 

```
select cleanText ,script_fields('FANDS','params._source.cleanText.length()')
from test_status
where cleanText is not missing
limit 10
```

but this doesnt work 

```
elect cleanText ,script_fields('FANDS','params._source.cleanText.length()')
from test_status
where cleanText is not missing
and script('params._fields["FANDS"].value==10')
limit 10
```

and neither this one

```
select cleanText ,script_fields('FANDS','params._source.cleanText.length()')
from test_status
where cleanText is not missing
and script('params._source.cleanText.length()==10')
limit 10
```

also i added `return `in the beginning of script in where clause but that didn't work either 
like this

```
select cleanText ,script_fields('FANDS','params._source.cleanText.length()')
from test_status
where cleanText is not missing
and script('return params._source.cleanText.length()==10')
limit 10
```
and in would be nice to see how i could make a `script_fields` and if you could give me an example I'll be grateful

**Comment by imandoostie** [comment]
hi guys 
i had same issue with text type field but so far haven't find any answer 
if anyone could help us in this matter 
we're in need ASAP
thanks

**Comment by shi-yuan** [comment]
```sql
select * from myindex where script("doc['FANDS.keyword'].value.length() == 10")
```

**Comment by mhsankar** [comment]
thanks for your reply but i forgot to mention that my `text fields` doesn't have a `keyword subfield` because the amount of data we have here and storage we got cant handle keyword duo to the lack of storage 
also I forgot to mention that we did enabled the `fielddata` for both of the fields that we needed on this query
best regard
hadi .s

**Comment by shi-yuan** [comment]
if `text fields` analyzer is keyword，you can search: 
````
select * from myindex where script("doc['FANDS'].value.length() == 10")
````

Alternatively, [retrieve a runtime field](https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime-retrieving-fields.html)
````
POST myindex/_search
{
    "runtime_mappings": {
        "FANDS_length": {
            "type": "long",
            "script": {
                "source": "emit(params['_source']['FANDS'].length())"
            }
        }
    },
    "query": {
        "term": {
            "FANDS_length": {
                "value": 10
            }
        }
    }
}
````

**Comment by mhsankar** [comment]
Thanks for reply
but how can use `runtime mappings` when I'm using `nlpchina` plugin?

**Comment by shi-yuan** [comment]
> Thanks for reply but how can use `runtime mappings` when I'm using `nlpchina` plugin?

Not supported now，:sweat:

**Comment by shi-yuan** [comment]
> Thanks for reply but how can use `runtime mappings` when I'm using `nlpchina` plugin?

Not supported now，:sweat:

**Comment by mhsankar** [comment]
is there anyway that this feature became available any time soon?

**Comment by shi-yuan** [comment]
will be supported as soon as possible

**Comment by mhsankar** [comment]
could you please inform us on this topic after this feature added to the next version of `nlpchina`?

Best Regards
Hadi .s

**Comment by shi-yuan** [comment]
```sql
SELECT /* ! RUNTIME_MAPPINGS({"FANDS_length":{"type":"long","script":{"source":"emit(params['_source']['FANDS'].length())"}}}
)*/* FROM myindex WHERE FANDS_length = 10
```
