### ISSUE TITLE
No showing total number of records

### ISSUE THREAD

**Issue by guru1612** [NLPchina/elasticsearch-sql#1155]
Hi Expert
 I am using 7.9.3 elasticsearch and same nlpcn sql plugin. whenever try to get data from an index it shows "Object Object" instead of total number records.
 help me to solve this.
![Screenshot from 2021-12-14 13-45-14](https://user-images.githubusercontent.com/96039459/145959353-32261537-764a-4562-a9fa-985318bfe2ac.png)

thanks,
guru

**Comment by shi-yuan** [comment]
will be supported as soon as possible
