### ISSUE TITLE
Column order does not match SELECT

### ISSUE THREAD

**Issue by felixbuenemann** [NLPchina/elasticsearch-sql#116]
The order of the columns in the web ui does not match the order or the columns given in the select.

Example: `SELECT foo, bar FROM baz` might show table columns in the oder bar, foo.

Tested on ES 2.0.0, plugin 2.0.1.

**Comment by eliranmoyal** [comment]
Yeah I've notice it before.
The problem is that the columns order at result stage is always the mapping order for your type.
Mainly the plugin just translate the query to elasticsearch json and the ui just parse the results and do not interfere in the way so there is no easy fix for it.

**Comment by felixbuenemann** [comment]
It's probably not worth implementing it if it's not trivial. I'll close this.
