### ISSUE TITLE
about sum/avg nested fields

### ISSUE THREAD

**Issue by tigerone1** [NLPchina/elasticsearch-sql#118]
hi eliranmoyal,I have other question about nested,for example,there is an nested array object,like this
"comments": [
{
"name": "John Smith",
"comment": "Great article",
"age": 28,
"stars": 4,
"date": "2014-09-01"
}
,
{
"name": "Alice White",
"comment": "More like this please",
"age": 31,
"stars": 5,
"date": "2014-10-22"
}
]
I want to select sum(comments.age) * from index,how to do?

**Comment by eliranmoyal** [comment]
Guess i didn't thought about this kind of aggregations.
i'll add it to this weekend release.
Really thanks for experimenting with the master and new features!!

**Comment by tigerone1** [comment]
Thanks

**Comment by eliranmoyal** [comment]
You are now able to do `select sum(nested(comments.age)) from index `
you can also use it on buckets aggregations  with the nested option , like this:

select count(\*) from index
group by date_histogram('field'='message.date','interval'='1d','alias'='day', **'nested' ='message'**)
On nested you need to enter the nested path.

**Comment by tigerone1** [comment]
OK，Thank you very much
