### ISSUE TITLE
elasticsearch-sql依赖的druid组件存在安全漏洞，升级druid组件后和elasticsearch-sql不兼容，如何解决？

### ISSUE THREAD

**Issue by h344818623** [NLPchina/elasticsearch-sql#1187]
druid<1.2.3的版本存在安全漏洞，如下
![image](https://user-images.githubusercontent.com/30397897/205828882-09d56b0e-ebb5-4ccd-9850-e4af682b29e8.png)
漏洞详细描述见：https://nvd.nist.gov/vuln/search/results?isCpeNameSearch=false&query=druid&results_type=overview&form_type=Basic&search_type=all&startIndex=0

目前elasticsearch-sql最新版本依然依赖的druid有安全漏洞的版本（1.1.16），若强升druid没有该安全漏洞的版本（1.2.4），则和elasticsearch-sql版本不兼容，对此elasticsearch-sql有什么解决方案么？

**Comment by shi-yuan** [comment]
近期会升级druid到最新版
