### ISSUE TITLE
Does not work with ES 2.1.0

### ISSUE THREAD

**Issue by javadevmtl** [NLPchina/elasticsearch-sql#119]
Just installed ES 2.1.0

Here is the error message...

Verifying https://github.com/NLPchina/elasticsearch-sql/releases/download/2.0.1/elasticsearch-sql-2.0.1.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Plugin [sql] is incompatible with Elasticsearch [2.1.0]. Was designed for version [2.0.0]

**Comment by eliranmoyal** [comment]
Yeah from 2.0 you need to compile your plugin with each version.
I'll create a branch and a release for 2.1 today/tomorrow.

**Comment by eliranmoyal** [comment]
check release 2.1 
https://github.com/NLPchina/elasticsearch-sql/releases/tag/2.1.0
