### ISSUE TITLE
ignore_unavailable option

### ISSUE THREAD

**Issue by chendo** [NLPchina/elasticsearch-sql#120]
Is it possible to enable the `ignore_unavailable` option as specified in https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html when querying multiple indexes? I'm trying to use this awesome plugin to query a Logstash cluster and some of our indexes have longer retention times than others, so some indexes that I'd like to query for does not exist, and I'd rather it not error.

I could have another query that checks for the indexes that do exist, but that's another hop I'd like to avoid.

Thanks for a great plugin!

**Comment by eliranmoyal** [comment]
Thank you, and thanks  for using it :) 
How do you want it to look like? 
Is hint ok? 
```sql
Select /*!  IGNORE_UNAVILIABLE */ * from x,y,z
```

Also, which version of elasticsearch are you using? I will create a patch for you if you don't want to wait until the next release

**Comment by chendo** [comment]
Hint works for me!

We're using 1.4.5 (a bit behind).

Thanks! :D

**Comment by eliranmoyal** [comment]
I've create a version for you with this update.
you can compile it using maven (there is an explanation on wiki)
Or send me an email - my mail is on pom.xml and i will send you the zip .
From what I saw :  if all the indices are unavailable you will still get error but if some of them exists it will be ok.
this is the hint: /*! IGNORE_UNAVAILABLE*/

**Comment by chendo** [comment]
Fantastic, thanks for the quick turnaround! Will hopefully get to try it some time today.

**Comment by chendo** [comment]
Confirmed that it works, thanks again!
