### ISSUE TITLE
分页检索似乎有问题，无法按照页码滚动、

### ISSUE THREAD

**Issue by leviYX** [NLPchina/elasticsearch-sql#1207]
我的总数只有六条数据，当指定limit 0,3的时候第一页返回3条。
但是当我limit 3,3的时候，依然能返回数据。
SELECT * FROM social_media  WHERE status = 1

**Comment by leviYX** [comment]
而且分页的时候，第二页出现了和第一页一样的数据。这个是bug吗

**Comment by leviYX** [comment]
版本是7.13.0

**Comment by leviYX** [comment]
![image](https://user-images.githubusercontent.com/111969932/222629671-4f779c62-3565-412a-ab25-33139b6ff6ee.png)
![image](https://user-images.githubusercontent.com/111969932/222629728-0dc393a2-0b3d-4e66-bf9f-007f675dd4a7.png)

**Comment by leviYX** [comment]
@shi-yuan 大佬求指点。

**Comment by shi-yuan** [comment]
没问题的，limit第一个参数是offset（从0开始），第二个参数是row_count
