### ISSUE TITLE
what is the syntax to ingnore_unavailable index in queries

### ISSUE THREAD

**Issue by mohaneldia** [NLPchina/elasticsearch-sql#121]

**Comment by eliranmoyal** [comment]
it's only available on master branch (for 1.4-1.7 ) not in any release yet.
You simply need to use a sql hint:

```sql
SELECT SELECT /*! IGNORE_UNAVAILABLE */ * FROM index1,index2,index3
WHERE ....
```

**Comment by mohaneldia** [comment]
that means it won't work in the release 1.4.7?

**Comment by eliranmoyal** [comment]
No , i just pushed this commit yesterday. you can compile it on your own / send me an email and i will send you the zip file.

**Comment by mohaneldia** [comment]
1.will this hint will be available in the future releases?
2.will this hint works in subquries?

**Comment by eliranmoyal** [comment]
yes and yes

**Comment by mohaneldia** [comment]
thanks
