### ISSUE TITLE
Bulk Query

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#122]
Is there a way to have the response back in a aggregate manner when the the response is say 100000 records so as not to have performance issue in the front end application ( not in sql plugin UI)?

**Comment by eliranmoyal** [comment]
You can use scroll api to do paging in your client. 
The scroll api is good for your client and for your elasticsearch cluster.

**Comment by satapsa** [comment]
Does the scroll option provided by the sql plugin uses bith scroll and scan. 
 SELECT /*! USE_SCROLL(100,30000)*/ firstname , balance FROM accounts 

It seems the sorting should be disabled by using
_search?search_type=scan&scroll=1m

**Comment by eliranmoyal** [comment]
It uses scan and scroll if order by not provided. The search_type on url occures from the 2nd request. And from there it doesn't matter if the type provided or not (it uses the first search type)
