### ISSUE TITLE
Upgrade to Elasticsearch 2.0.0 or 2.1.0 and corresponding sql plugin

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#123]
I am using Elasticsearch 1.7.0 and need to upgrade to Elasticsearch 2.0.0. Trying to see, if I should upgrade to the latest version of 2.1.0 instead. Is the Elasticsearch 2.1.0  stable ?

If I upgrade to Elasticsearch 2.1.0, I should get the sql plug in for Elasticsearch 2.1.0 ?

**Comment by eliranmoyal** [comment]
I think that elasticsearch 2.1 is stable. they officially released it 20 days ago..
if you upgrade to 2.1.0 use the 2.1.0 plugin version
if you upgrade to 2.0.0 use 2.0.2 plugin version

**Comment by satapsa** [comment]
Thanks Eliranmoyal
