### ISSUE TITLE
怎么进行分页

### ISSUE THREAD

**Issue by shaonianlang-ooo** [NLPchina/elasticsearch-sql#1231]
select * from assets_mapping where ipLocation like '%内网%' LIMIT 0,1000

{
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "line 1:66: mismatched input ',' expecting <EOF>"
            }
        ],
        "type": "parsing_exception",
        "reason": "line 1:66: mismatched input ',' expecting <EOF>",
        "caused_by": {
            "type": "input_mismatch_exception",
            "reason": null
        }
    },
    "status": 400
}

**Comment by clh123321** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by shi-yuan** [comment]
> select * from assets_mapping where ipLocation like '%内网%' LIMIT 0,1000
> 
> { "error": { "root_cause": [ { "type": "parsing_exception", "reason": "line 1:66: mismatched input ',' expecting " } ], "type": "parsing_exception", "reason": "line 1:66: mismatched input ',' expecting ", "caused_by": { "type": "input_mismatch_exception", "reason": null } }, "status": 400 }

哪个版本，怎么访问的，这个sql，没问题的
![image](https://github.com/NLPchina/elasticsearch-sql/assets/8057153/e40c3c69-5576-4930-aa4d-f4060125f171)

**Comment by z673168469** [comment]
你好 楼主，分页这个问题你解决了嘛？我这边也出现了同样的问题

**Comment by 13223746581** [comment]
> > select * from assets_mapping where ipLocation like '%内网%' LIMIT 0,1000
> > { "error": { "root_cause": [ { "type": "parsing_exception", "reason": "line 1:66: mismatched input ',' expecting " } ], "type": "parsing_exception", "reason": "line 1:66: mismatched input ',' expecting ", "caused_by": { "type": "input_mismatch_exception", "reason": null } }, "status": 400 }
> 
> 哪个版本，怎么访问的，这个sql，没问题的 ![image](https://github.com/NLPchina/elasticsearch-sql/assets/8057153/e40c3c69-5576-4930-aa4d-f4060125f171)

您好 大佬可否问一下这个如何分页呢 我也遇到了同样的问题 安装了插件以后分页报错 求帮助
