### ISSUE TITLE
网页查询报错

### ISSUE THREAD

**Issue by 4your** [NLPchina/elasticsearch-sql#1232]
![image](https://github.com/NLPchina/elasticsearch-sql/assets/4377098/4cf81b3f-3225-4d61-867a-20866e933699)
 Error:{"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:8] Unrecognized token 'SELECT': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 1, column: 8]"}],"type":"x_content_parse_exception","reason":"[1:8] Unrecognized token 'SELECT': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 1, column: 8]","caused_by":{"type":"json_parse_exception","reason":"Unrecognized token 'SELECT': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 1, column: 8]"}},"status":400}

版本：8.10.2

**Comment by 4your** [comment]
大佬能看下这个问题吗

**Comment by clh123321** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by shi-yuan** [comment]
> ![image](https://private-user-images.githubusercontent.com/4377098/281326053-4cf81b3f-3225-4d61-867a-20866e933699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTI3ODEsIm5iZiI6MTcwNDExMjQ4MSwicGF0aCI6Ii80Mzc3MDk4LzI4MTMyNjA1My00Y2Y4MWIzZi0zMjI1LTRkNjEtODY3YS0yMDg2NmU5MzM2OTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDFUMTIzNDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjIxNmU4ZjNhNmI0MzFjODE2YjdlYmVmM2Y3MTIwN2FiYjBkZjc5ODJkYTBhYWJjYzhkM2E4NTgyMjI1YzM4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K_JbmRD2oHCOU0rKtTPlx4HPAv-dwhxZpXTcH904vUE) Error:{"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:8] Unrecognized token 'SELECT': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 1, column: 8]"}],"type":"x_content_parse_exception","reason":"[1:8] Unrecognized token 'SELECT': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 1, column: 8]","caused_by":{"type":"json_parse_exception","reason":"Unrecognized token 'SELECT': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 1, column: 8]"}},"status":400}
> 
> 版本：8.10.2

客户端换成
https://github.com/shi-yuan/elasticsearch-sql-site-chrome
