### ISSUE TITLE
integer only field name with backtick

### ISSUE THREAD

**Issue by knoguchi** [NLPchina/elasticsearch-sql#127]
I'm dealing with an existing index/doc that I have no control.  There are field names like 0304. 
The backtick works in the SELECT columns.  However it doesn't work in the WHERE clause.  Would you make it work in WHERE as well?  Thank you.

 **works**
SELECT \`0304\` FROM index/doc
**doesn't work**.  The resulting ES query JSON got "\`0304\`" field name.
SELECT \`0304\` FROM index/doc WHERE \`0304\` > 123

**Comment by eliranmoyal** [comment]
Hey ,
It cannot parsed as sql.. 
So i'll create you something like this:
```sql
select * from index/doc where ['0304'] > 123
```
Hope i'll create a release this weekend

**Comment by knoguchi** [comment]
Thanks for your response, and the alternative solution!    Would you please enlighten me why it can't be parsed?  Isn't the columns in WHERE clause expression same as column expressions in the SELECT in terms of AST?

**Comment by eliranmoyal** [comment]
I'm using mysql parser with minor changes. On sql you can always select static values(literals)  before the from clause (it is not possible on elasticsearch so I used them as fields). 
But on where you must have identifiers on left side of the condition, identifiers are like words (must start with a-Z)  but it can also be wrapped by brackets

**Comment by eliranmoyal** [comment]
You will be able to use it this way:

```sql
SELECT ['0304'] FROM index/doc
where ['0304'] >123
```
as you mentioned this will also work

```sql
SELECT `0304` FROM index/doc
where ['0304'] >123
```

**Comment by knoguchi** [comment]
It's great if the bracket notation is consistent in any expressions.  Will that work for ORDER BY as well?

**Comment by knoguchi** [comment]
Thanks for the commit.  I will check out and test away.

**Comment by eliranmoyal** [comment]
yeah it will work for order by and for group by

**Comment by eliranmoyal** [comment]
Hey the new version with this feature is now out
check it and tell me if you are having problems
good luck :)
