### ISSUE TITLE
Filter does not support equality for dates

### ISSUE THREAD

**Issue by javadevmtl** [NLPchina/elasticsearch-sql#128]
For example the below sql throws an exception...

```sql
select * from my_index where my_date = now/d
```

{"error":{"root_cause":[{"type":"sql_parse_exception","reason":"Cannot recoginze Sql identifer now"}],"type":"sql_parse_exception","reason":"Cannot recoginze Sql identifer now"},"status":500}

This is perfectly valid query...

```javascript
{
	"from": 0,
	"size": 200,
	"query": {
		"bool": {
			"must": {
				"range": {
					"my_date": {
						"from": "now/d",
						"to": "now/d"
					}
				}
			}
		}
	}
}
```

**Comment by javadevmtl** [comment]
Ok maybe needs to be thought of. Basically we need to do my_date >= "now/d" and my_date <= "now/d"

**Comment by eliranmoyal** [comment]
Do like this:
```SQL
select * from myIndex where my_date between 'now/d' and 'now/d'
```
