### ISSUE TITLE
elasticsearch 2.1.1 not yet supported

### ISSUE THREAD

**Issue by robertsmarty** [NLPchina/elasticsearch-sql#129]
Hi,

I know this will be coming however could you let me know when 2.1.1 will be supported?

Cheers,

Marty

**Comment by eliranmoyal** [comment]
Hey, I'll be working on this on the next couple of days
 sorry for the long wait

**Comment by anduo1989** [comment]
我看支持啊，我直接改了下version，版本号

**Comment by eliranmoyal** [comment]
check the new version 2.1.1
https://github.com/NLPchina/elasticsearch-sql/releases/download/2.1.1/elasticsearch-sql-2.1.1.zip

**Comment by robertsmarty** [comment]
Thank you and happy new year!
