### ISSUE TITLE
Plugin [sql] is incompatible with Elasticsearch [2.1.1]

### ISSUE THREAD

**Issue by doanthanhlong** [NLPchina/elasticsearch-sql#130]
Hi,
I have install ElasticSearch-SQL with ElasticSearch 2.1.1,
But the lasted version 2.1.0 is not compatible with ES 2.1.1
Please release a new one. Thank you :)

./plugin install file:../../elasticsearch-sql-2.1.0.zip
-> Installing from file:../../elasticsearch-sql-2.1.0.zip...
Trying file:../../elasticsearch-sql-2.1.0.zip ...
Downloading ......................................DONE
Verifying file:../../elasticsearch-sql-2.1.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Plugin [sql] is incompatible with Elasticsearch [2.1.1]. Was designed for version [2.1.0]

**Comment by eliranmoyal** [comment]
duplicate #129
I'll work on this :)
