### ISSUE TITLE
Support for nested queries

### ISSUE THREAD

**Issue by tigerone1** [NLPchina/elasticsearch-sql#131]
hi eliranmoyal.I find an another issues,if there are two nested array objects(A,B is nested),I want to search in conditions,like this
where nested('A', A.field='xxx') and nested('B',B.field='yyy'),but I get the response Error,
other case is same error,like this (A is nested,C is common field )
where  nested('A', A.field='xxx') and c='zzz'
How to do?

**Comment by eliranmoyal** [comment]
Hey tiger 
I think you got the parameters wrong it's 
Where nested(A.field,'A') ='xxx' and nested(B.field,'B')='yyy'

**Comment by eliranmoyal** [comment]
Ok i see the problem. i'll look at it tomorrow
thanks

**Comment by eliranmoyal** [comment]
Ok it's a bug. 

just for you to understand me:
complex nested is `nested(PATH, condition)`
simple nested is  `nested(field,PATH) OP value`

A workaround is not to put complex nested on left side.
meaning:
**BAD** - will not work
```sql
select * from myIndex where nested('A', A.field='xxx') and c='zzz'
```
**GOOD** - will work
```sql
select * from myIndex where c='zzz' and nested('A', A.field='xxx') 
```
Also if you can just use the simple nested on the left side.
```sql
select * from myIndex where nested(A.field,'A') ='xxx'  and nested('B', B.field='xxx') 
```
I'll fix it , but hope this workaround works for you for now.

**Comment by tigerone1** [comment]
Thank you very much,I will test it.Proud of your work
