### ISSUE TITLE
distinct语法不支持？

### ISSUE THREAD

**Issue by yangaoquan** [NLPchina/elasticsearch-sql#133]
目前distinct只能配合count使用，单独还使用不了啊， 比如：select distinct(ip) from mytype 语句就不行，不知道这个功能啥时候能支持哦？

**Comment by eliranmoyal** [comment]
I do not understand Chinese. 
I guess you want a distinct but I don't think it's available in elasticsearch 
You can do a group by and it will work pretty much the same 
Select * from myindex group by ip

**Comment by Ghost93** [comment]
@eliranmoyal what about [cardinality aggreagation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html)?
It may be used as some kind of ```distinct```...

**Comment by eliranmoyal** [comment]
Cardinality is distinct count not distinct values

**Comment by ansjsun** [comment]
Hi   @yangaoquan 

你好目前 不支持distinct  但是你可以通过 ,topHits来实现类似的功能

select topHits('size'=3,age='desc') from bank  group by gender

**Comment by yangaoquan** [comment]
@eliranmoyal, @ansjsun, Thanks a lot. I was ready to use native DSL statement
