### ISSUE TITLE
Securi in Elasticsearch and sql plugin

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#135]
If we are required to use a user id and password to login to Elastic search, can we pass the user id and password in the query via the sql plug in as well ?

If yes - what is the syntax ?

If no - what are the other options ?

**Comment by eliranmoyal** [comment]
I don't familiar with this feature (security on elasticsearch). can you give me a link how to install it on my elasticsearch?

**Comment by satapsa** [comment]
https://www.elastic.co/downloads/shield

I am on Elasticsearch 1.7 and thus shield 1.0.0 was downloaded automatically.

Please let me know, if you have any more questions.

**Comment by satapsa** [comment]
I am sending the query
http://xxxxxx:9200/-u xxx -p yyy  _sql?sql=SELECT abc as my key from xxxx/xxx group by test_loc limit 0
However it is returning the status all the indices and is not returning the the result as is supposed to be.

**Comment by satapsa** [comment]
Hi Eliranmoyal

i found a way around of using the ( Python) base64.encodestring(username,password) and add the request to the header and it worked.

url="http://xxxxx:9200/_sql?sql=SELECT+****++AS+mykey%2C+count%28%2A%29+AS+myval1+FROM+xxxxx%2Fxxxx+WHERE+xxxx%3E0+AND+xxxxx+in%2847%2C37%2C27%2C7%29+and+GEO_BOUNDING_BOX%28xxx%2C-93.29192853733362%2C44.98521676873701%2C-93.24924922748754%2C44.972952619045344%29+GROUP+BY+xxxx+LIMIT+0"

        req = urllib2.Request(url)
        base64string = base64.encodestring('%s:%s' % ("username", "password")).replace('\n', '')
        req.add_header("Authorization", "Basic %s" % base64string)
        res=urllib2.urlopen(req)
        print res.read()

**Comment by eliranmoyal** [comment]
Great !
It is a bit a problem to use a plugin from another plugin
https://github.com/elastic/elasticsearch/issues/14585
