### ISSUE TITLE
Is there any way to escape underscore when doing a like query?

### ISSUE THREAD

**Issue by milodky** [NLPchina/elasticsearch-sql#137]
I tried back slash, brackets, but neither worked..

**Comment by eliranmoyal** [comment]
Hey @milodky 
I didn't wrote this feature and yes, I looked and unfortunately it does not support escaping..
I'll make a quick fix for it tomorrow so you will be able to escape underscore and also %.

**Comment by eliranmoyal** [comment]
escaping are &PERCENT and &UNDERSCORE

**Comment by rahuldaskar** [comment]
Hi @eliranmoyal 
I think * and ? should also be escaped equivalent to % and _ respectively.

**Comment by eliranmoyal** [comment]
Guess you are are right
Do you know if escaping them in elasticsearch is just putting a backslash before?

**Comment by rahuldaskar** [comment]
As stated here-https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_wildcards
I used backslash but select query is not working.
Below is the query that my code is forming-
_SELECT * FROM index/documentype WHERE  fieldname like '*\**'_

Here I should get only those records having * in their field name. But I am getting all the records instead.

**Comment by eliranmoyal** [comment]
Hey @rahuldaskar and @milodky , I'm really sorry
wasn't here for about a month+
have you tried two backslashes?
I tried and it worked for me
Added 2 docs one with message "sos" another with "s*s"
when asking
```sql
select * from myIndex
were myField like 's*s'
```
got both of them

when asking 
```sql
select * from myIndex
were myField like 's\\*s'
```
got only s*s document

**Comment by rahuldaskar** [comment]
Thanks @eliranmoyal ! Two backslashes worked for me!
