### ISSUE TITLE
Using asterisk in JOIN query

### ISSUE THREAD

**Issue by umaxfun** [NLPchina/elasticsearch-sql#138]
Hi,

I've encountered a problem with JOIN queries like this:
```
SELECT s.*, cat.DisplayName
FROM shops s
JOIN shops cat ON s.id = cat.parentId
WHERE s.parentId = '123123'
```

Here I expect `s.*` to be recognized as "all fields from index s", but it gets recognized as field name.

Maybe there is some workaround for this case?

**Comment by eliranmoyal** [comment]
There is no such option now.
I will add this feature

**Comment by umaxfun** [comment]
Thank you :+1:
