### ISSUE TITLE
Any support for the highlight feature?

### ISSUE THREAD

**Issue by ottboy4** [NLPchina/elasticsearch-sql#140]
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html

I would like to pull some highlighted text back, but I would like to build the query using the SQL plugin.

Is this currently supported? Or are there plans to support this?

**Comment by eliranmoyal** [comment]
This is not currently supported
I see there is lot of options for this feature and this is not something intuitive to implement (not another filter / aggregation)
Can you provide example for how you want it to look on queries? (maybe an hint?)

**Comment by ottboy4** [comment]
I'm open to whatever works best; however, I could see it being implemented in a similar way to the way  /*! USE_SCROLL */ is implemented.

Something maybe like this...
```SELECT /*! HIGHLIGHT(fields_to_highlight, options) */ * FROM index```

More realistic example...
```SELECT /*! HIGHLIGHT(firstname, fragment_size: 150, number_of_fragments: 3) */ firstname , balance FROM accounts```

Another option could be, add in support only for the REST API and add the ability to pass JSON as the request body and have a "sql" field with the sql query and then be able to do a separate "highlight" field that allows for the highlight options from elastic to be passed in.

Then the JSON request could look like...
```
 {
   "sql": "SELECT firstname, balance FROM accounts",
   "highlight" : {
        "fields" : {
            "firstname" : {
                "fragment_size" : 150,
                "number_of_fragments" : 3,
                "no_match_size": 150
            }
        }
    }
}
 ```
The JSON option could add some nice functionality for easily adding other elastic features as well.

I believe this would be a nice addition of functionality, so I am just throwing out some ideas on how it could be implemented.

**Comment by eliranmoyal** [comment]
Thanks
I'll be working on this soon :)

**Comment by ottboy4** [comment]
Awesome thanks!

**Comment by eliranmoyal** [comment]
Sorry for the long wait , check the new release :)
It is only available through rest api (not on site)

**Comment by ottboy4** [comment]
Awesome! This is great to hear!

Is there anywhere in the wiki that documents how to do this?

**Comment by eliranmoyal** [comment]
Yes here
https://github.com/NLPchina/elasticsearch-sql/wiki/Highlight

**Comment by ottboy4** [comment]
Awesome. Thanks!
