### ISSUE TITLE
Support for date functions

### ISSUE THREAD

**Issue by gkluoe** [NLPchina/elasticsearch-sql#142]
Hi - do you support any functions for pulling out the hour, minute of a timestamp? Like the SQL server DATEPART function? If not, this would be a great feature.

http://www.w3schools.com/sql/func_datepart.asp

**Comment by eliranmoyal** [comment]
elasticsearch does not support date functions so i have nothing to translate to.
But you can do it with scripting
To select fields with scripts you can do something like this:
```sql
select script('hour','doc["insert_time"].date.hourOfDay') , message from myIndex
```
There is example here for scripting on query : 
https://github.com/NLPchina/elasticsearch-sql/wiki/ScriptQuery

**Comment by gkluoe** [comment]
Ah, great - I hadn't noticed that. Thanks!
