### ISSUE TITLE
Timestamp formatting

### ISSUE THREAD

**Issue by bassduh** [NLPchina/elasticsearch-sql#143]
Hi,

I have already searched through the wiki, but didn't find an answer yet.
Is it possible to format a timestamp field?

For instance:

"select timestamp from myindex limit 1" gives me

2016-01-21T12:09:51.0962625Z

It would be nice to display it as: 2016-01-21 12:09:51

**Comment by umaxfun** [comment]
See https://github.com/NLPchina/elasticsearch-sql/issues/142 for resolution :)

**Comment by eliranmoyal** [comment]
@umaxfun is right , you can always use scripts.
Also the format is the format in your mapping, so if you will index a date with other format on your mapping you will get that format when displaying this field.

**Comment by satapsa** [comment]
Hi Eliranmoyal

I am getting a date "value":1.4521248E12,"value_as_string":"2016-01-07 00:00:00"

Is 1.4521248E12 in GMT, UTC or local format ?

**Comment by eliranmoyal** [comment]
What's your mapping?

**Comment by satapsa** [comment]
"format":"YYYY-MM-dd HH:mm:ss",
"type": :date"

**Comment by eliranmoyal** [comment]
I believe it is just the number of milli seconds from 1970-01-01 00:00:00
meaning the unix time in milliseconds

**Comment by eliranmoyal** [comment]
@bassduh 
if you are still having trouble . this will work:
```sql
SELECT script('myFormat','new Date(doc["insert_time"].value).format("yyyy-MM-dd HH:mm:ss")') , insert_time FROM yourIndex
```

**Comment by bassduh** [comment]
Thanks for pointing me in the right direction.
Had tried some things with script-function, but didn't work for me.

After all, it seems groovy was not enabled in ES.
Now it is working fine:

Timestamp	myFormat
2016-01-21T12:09:51.0962625Z	2016-01-21 13:09:51
2016-01-21T12:09:50.8532531Z	2016-01-21 13:09:50
