### ISSUE TITLE
CSV - Rest API

### ISSUE THREAD

**Issue by bassduh** [NLPchina/elasticsearch-sql#146]
Thanks for adding this, i'm using it a lot.
I know it is experimental, but I'm walking into a problem.

Scripted fields are ignored;

SELECT Timestamp, STATUS, script('TIMESTAMP','new Date(doc["Timestamp"].value).format("yyyy-MM-dd HH:mm:ss")') FROM commvault ORDER BY Timestamp DESC LIMIT 1

returns:

STATUS|Timestamp
-----------|--------------
Succeeded|2016-01-27T07:27:26.2095478Z

But in the 'normal' page it is working great;

STATUS|Timestamp|TIMESTAMP
-----------|--------------|----------------
Succeeded|2016-01-27T07:27:26.2095478Z|2016-01-27 08:27:26

Is this a know issue?

**Comment by eliranmoyal** [comment]
Hey , 
Yeah its a bug, I just parsed the source and not the fields from the result.
will fix in next version.
Thanks!

**Comment by eliranmoyal** [comment]
Sorry for the long wait , check the new release :)
