### ISSUE TITLE
CSV output from sql plug in

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#149]
I am on Elasticsearch 1.7 and sql plugin 1.4.6

When I run the query on the browser it brings up the sql plugin front end. Since I want run it from my script, how can I achieve it ?

Do I need to upgrade to a later version of the sql plug in ?

http://xxxx:9200/_plugin/sql/?separator=,&format=csv&sql=select * from xxxx/xxxx limit 4

**Comment by eliranmoyal** [comment]
The csv feature is from 1.4.8
you can read the the release notes here:
https://github.com/NLPchina/elasticsearch-sql/releases

**Comment by satapsa** [comment]
Thanks a lot for your quick reply.

**Comment by satapsa** [comment]
Hi Eliranmoyal

Just wanted to update you that the query is taking a long time . we are looking for 20000 records. Is there a way to improve the speed ?
