### ISSUE TITLE
_score field in Query

### ISSUE THREAD

**Issue by prof-schacht** [NLPchina/elasticsearch-sql#150]
Hello,

I tried the following query to see the searched field and also the _score but the tool only displays the address field. 

SELECT address,_score FROM bank 
WHERE address = matchQuery('880 Holmes Lane') 
ORDER BY _score desc limit 3

Is there a way to display also the _score field in result table?

BR

**Comment by eliranmoyal** [comment]
Hey,
the _score and _id fields always returns from elasticsearch response so i don't know whether you requested them or not (the results parser has no knowledge about the query and just translates elasticsearch responses).
I can add a feature to the options to let you choose if you want to add the _score and the _id fields to the table.
Is that ok for you?

**Comment by prof-schacht** [comment]
Hey, 
This would be great.

BR

**Comment by eliranmoyal** [comment]
sorry for the long wait , check the new release
