### ISSUE TITLE
is there any way I can achieve distinct values sum using cardinality aggregation ?

### ISSUE THREAD

**Issue by Shashi-GS** [NLPchina/elasticsearch-sql#151]

**Comment by eliranmoyal** [comment]
not sure what are you trying to do.
can you give an example?
you can always create scripted aggregation with code if it's not an elasticsearch feature.

**Comment by Shashi-GS** [comment]
I wanted to achieve the below sql query. 
select sum(distinct target), sum(amount) from ams group by product

i.e., here is the data table.
![image](https://cloud.githubusercontent.com/assets/17082069/12864365/6db20668-ccae-11e5-9361-7cef8d79f6ac.png)

I am able to achieve the sum of grouped elements, but not able to achieve the sum of distinct values from a column.

**Comment by eliranmoyal** [comment]
Oh,
I couldn't find something like that in elasticsearch so i have nothing to translate to..
the cardinality is like distinct-count and not breakable.
I managed to do it using the scripted_metric , but its look a bit ugly.. 
```sql
SELECT 
 scripted_metric(
'init_script' = '_agg["distinctAges"]=new HashSet<Integer>()',
'map_script'='_agg.distinctAges.add(doc["age"].value)' ,
'combine_script'='return _agg.distinctAges;', 
'reduce_script'='allAges = new HashSet<Integer>();
   for(agesFromShard in _aggs) {
   	allAges.addAll(agesFromShard);
   };
   sum = 0;
   for(age in allAges){
   	sum+=age;
   };
   return sum;
   ') as sum_distinct

FROM elast*/account
```

**Comment by Shashi-GS** [comment]
Thank you so much for the info. it is really helpful.
