### ISSUE TITLE
ES 2.2.0 compatible version

### ISSUE THREAD

**Issue by athuljayaraj** [NLPchina/elasticsearch-sql#153]
Will there be a version of elasticsearch-sql compatible with ES 2.2.0?

**Comment by eliranmoyal** [comment]
Yeah, when I'll finish with my exams next week :)

**Comment by crazrain** [comment]
+1

**Comment by MobileAppVault** [comment]
+1

**Comment by cdonnellytx** [comment]
+1

**Comment by cdonnellytx** [comment]
FWIW, I did a fork of the repo and tried doing a naive upgrade (just version bump in .travis.yml, pom.xml), installed Maven, and was unable to build it.  Not sure if it's my setup (Windows 10 /JDK 1.8 / Maven 3.3.9), if there's some other dependency that needs to be bumped somewhere that I am unaware of, or changes to Elasticsearch that need to be accounted for:

[elasticsearch-sql.log.txt](https://github.com/NLPchina/elasticsearch-sql/files/155193/elasticsearch-sql.log.txt)

I suspect it's the last one, but don't have time to debug it myself.

**Comment by mohaneldia** [comment]
+1

**Comment by eliranmoyal** [comment]
sorry for the long time.
I was needed to change some code in order to support elasticsearch 2.2.0
https://github.com/NLPchina/elasticsearch-sql/releases/download/2.2.0/elasticsearch-sql-2.2.0.zip

**Comment by pedrocolon93** [comment]
Hi, if you could, push the changes done to support 2.2.0.  I found the source in releases, but I could not find it within the repository

**Comment by eliranmoyal** [comment]
It's on branch elastic2.2

**Comment by pedrocolon93** [comment]
Nevermind, must be that I failed switching branches.
