### ISSUE TITLE
replace function is not working

### ISSUE THREAD

**Issue by ppamulapati** [NLPchina/elasticsearch-sql#155]
we try to replace a string value in 'message' field. It is not working. 

ElasticSearch Ver :2.1.0

SELECT REPLACE(message,"MSDW_WOOJ_ALGO_SWP","TESTNAME"),
       FROM DISCFIX where FIXTags.11 = 'Y2VMB7FHKNB' 
and FIXTags.17 = 'zVcKuLJ4SASj66a-jakP9gA'

**Comment by eliranmoyal** [comment]
what is the replace function? I don't think elasticsearch has this kind of functionality
but you can always create a script field
```sql
SELECT message, script('replaced_field','doc["message"].value.replace("MSDW_WOOJ_ALGO_SWP","TESTNAME")'
FROM DISCFIX where FIXTags.11 = 'Y2VMB7FHKNB' 
and FIXTags.17 = 'zVcKuLJ4SASj66a-jakP9gA'
```
