### ISSUE TITLE
can i use elasticsearch-sql to convert sql to DSL?

### ISSUE THREAD

**Issue by ajqc** [NLPchina/elasticsearch-sql#156]
can i use elasticsearch-sql to convert sql to DSL?
if yes, how?

**Comment by eliranmoyal** [comment]
What do you mean? Do you want to convert it to elasticsearch json?

**Comment by ajqc** [comment]
i want to convert sql to elasticsearch dsl, like this:
sql:
`select * from a where fielda='b'`
i want to get this dsl by elasticsearch-sql:
```
{
  "query": {
    "term": {
      "fielda": "b"
    }
  }
}

```

**Comment by eliranmoyal** [comment]
Yes, if you are using the elasticsearch-sql  website just click on the explain button. 
On the rest api you can ask with _explain?sql=yourSql

**Comment by eliranmoyal** [comment]
http://localhost:9200/_sql/_explain?sql=select * from a where fielda='b'

**Comment by ajqc** [comment]
i need dsl,not search result or sql

**Comment by eliranmoyal** [comment]
and that is exactly what the EXPLAIN does..
WEB:
![image](https://cloud.githubusercontent.com/assets/2933669/13123371/7c1eaa0c-d5c4-11e5-878a-0e3c9f32ccf7.png)


API:
![image](https://cloud.githubusercontent.com/assets/2933669/13123337/5b21db30-d5c4-11e5-9ea8-6a119c5e2f97.png)

**Comment by ajqc** [comment]
thank you very much!!!

**Comment by levylll** [comment]
amazing!
