### ISSUE TITLE
Can i use the routing parameter when use the sql

### ISSUE THREAD

**Issue by fpk7660837** [NLPchina/elasticsearch-sql#157]
when  index,update the index, i set the routing parameter to make the index with the same style location on the same shard, so when query the data ,can i use routing to make query faster? thanks

**Comment by eliranmoyal** [comment]
hey, this is not currently supported
i'll add this feature with an hint

**Comment by fpk7660837** [comment]
i'm glad to hear that.thanks

**Comment by eliranmoyal** [comment]
Sorry for the long wait , check the new release
you can now query like this
```sql
SELECT /*! ROUTINGS(myRouting) */ * FROM myIndex/myType
```
```sql
SELECT /*! ROUTINGS(myRouting,mySecondRouting) */ * FROM myIndex/myType
```
