### ISSUE TITLE
transport client document insert with version 1.5 string is splitting with space

### ISSUE THREAD

**Issue by Shashi-GS** [NLPchina/elasticsearch-sql#161]
elastic search transport client document insert is splitting the word with space.
e.g., Sachin Tendulkar is splitted as Sachin and Tendulkar two words. When we query I am getting the first word only.

Please let me know how to avoid this?

**Comment by eliranmoyal** [comment]
Use not_analyzed on mapping of this field to avoid this kind of behavior in elasticsearch. 
It's happen only in elasticsearch-sql plugin? What happens when you query on native javaapi or restapi

**Comment by Shashi-GS** [comment]
Sorry! this question is not specific to elasticsearch-sql. I am using the transport client JAVA API, there it ignores the configuration of the elasticsearch.yml file. I wanted to set all the fields as not_analyzed in while inserting the data into elasticsearch.

**Comment by eliranmoyal** [comment]
Hey
you need to use dynamic_templates - for your index
https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html
next time for elasticsearch related questions just open it on the elasticsearch discuss forum
