### ISSUE TITLE
ES 2.1.2 compatible version?

### ISSUE THREAD

**Issue by githubmui** [NLPchina/elasticsearch-sql#163]
Will there be a version of elasticsearch-sql compatible with ES 2.1.2?

**Comment by githubmui** [comment]
Is it possible (in principal) to write an ES-SQL-Plugin in a way, that it's supporting a whole release-tree e.g. 2.1.x or 2.2.x? 
Currently for each version an individual plugin release is needed.
What are the technical reasons for that: e.g. always changing APIs or Query-DSL changes?

**Comment by eliranmoyal** [comment]
There are some changes (mostly elasticsearch api)
But from 2.x you must compile your plugin against the same version you work with, it causes wierd issues if you don't.
I will make you a new release but i think that after this release I will only support latest elastic version.

**Comment by githubmui** [comment]
Thank you very much for your support! I really appreciate this plugin project.

As you explained, the JSON approach would be more universal and would improve the benefits of this plugin. Another advantages would be to have the SQL-To-QueryDSL functionality in a portable way: e.g. for usage on client side.

**Comment by eliranmoyal** [comment]
I think a feature like that is a big change for this plugin.
Lately I don't have a lot of time working on this project (work and finishing my master degree).
My roadmap now is:
1. making this project an independent library 
2. more than 2 tables joins
3. supporting jdbc

I think that plugin that just converting the sql to json could maybe built only on JavaScript and than it will make it more accessible for users.

**Comment by githubmui** [comment]
Great roadmap and I like your idea with a Sql2Json-JavaScript ! 
But first go ahead with your master degree.

**Comment by eliranmoyal** [comment]
Really sorry for the long wait
https://github.com/NLPchina/elasticsearch-sql/releases/download/2.1.2.0/elasticsearch-sql-2.1.2.0.zip
