### ISSUE TITLE
 ParserException due to index name??

### ISSUE THREAD

**Issue by Selvinaz1984** [NLPchina/elasticsearch-sql#166]
I have installed Elasticsearch 1.6.0 and SQL Plugin 1.4.8. If I want to run an query via UI I receive following error:

 Error: {"error":"NoClassDefFoundError[com/alibaba/druid/sql/parser/Lexer]; nested: ClassNotFoundException[com.alibaba.druid.sql.parser.Lexer]; ","status":500}

If I run just show * or a real query on my index SELECT * FROM esh;event;event_0.4;2015-04-20_00-00-00-000;2015-04-26_23-59-59-999/EventBean WHERE version='1.6'; the error is the same? Why it doesnt find the class Lexer? I have installed the plugin successfully.

Under elasticsearch/plugins/sql there is the druid.jar where the class Lexer is in, why it will not be found?

**Comment by Selvinaz1984** [comment]
I have put the jars in elasticsearch/lib and then the error is away.
Now I get the Error: {"error":"ParserException[illegal sql expr : SELECT * FROM 'esh;event;event_0.4;2015-04-20_00-00-00-000;2015-04-26_23-59-59-999'/EventBean WHERE version='1.6']","status":500}.

Out indices are created dynamically per week, and if I want to put a sql query for all known indeces, how I can do this? Does the Parser exception occurs due to the name of index containing "." and ";"??

**Comment by Selvinaz1984** [comment]
Does the index name must follow a specific notation? Do constraints exist?

**Comment by eliranmoyal** [comment]
yeah there are some constraints. semicolons are not allowed.
I will fix it for you.. 
For now you can create aliases (for example replace all semicolons with dots)
