### ISSUE TITLE
install elasticsearch-sql get error

### ISSUE THREAD

**Issue by nathan-zhu** [NLPchina/elasticsearch-sql#167]
Hi, i got error during install es-sql plugin.
-> Installing from file:temp/elsticsearch-sql.zip...
Trying file:temp/elsticsearch-sql.zip ...
Downloading .......................................DONE
Verifying file:temp/elsticsearch-sql.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

i install it from file, can help to fix it? thanks.

**Comment by eliranmoyal** [comment]
What is your elasticsearch version? Which plugin version did you download ?

**Comment by nathan-zhu** [comment]
i use es 2.2 and es-sql is 2.2

**Comment by eliranmoyal** [comment]
the master is for 1.x versions as mentioned on readme file
this is the release for you (on branch elastic2.2)
https://github.com/NLPchina/elasticsearch-sql/releases/download/2.2.0/elasticsearch-sql-2.2.0.zip

**Comment by nathan-zhu** [comment]
@eliranmoyal thanks, very much. i got it works now.
