### ISSUE TITLE
Getting unique values in query response

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#169]
I am getting duplicate in the response. Is there a way to get unique values ?

I tried distinct - but did not help

**Comment by satapsa** [comment]
select  distinct(field_name)  FROM xxx/xxx

**Comment by shi-yuan** [comment]
have a look at issue [SELECT distinct --- Repeat error](https://github.com/NLPchina/elasticsearch-sql/issues/266)
