### ISSUE TITLE
Aggregation support on a JOIN

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#172]
Is aggregation supported in a JOIN of tw indices.

I have a requirement where I want to join 2 indices on some common columns and get an average on another field 
Ex:
SELECT a.date_yy,a._date_mm,avg(a.salary) as a_salary,avg(b.salary) as b_salary FROM xxxx/locs a JOIN /locs b ON a.date_yy=b.date_yy and a.date_mm=b.date_mm and  where GEO_BOUNDING_BOX(a.empl_loc,-75.21406035586925,40.53576072692386,-74.8261795087214,40.214914876818895)

**Comment by eliranmoyal** [comment]
Hey, sorry but no and I don't think I will be able to support it soon

**Comment by satapsa** [comment]
Thanks for the quick response. 
Is "median" supported ? I tried stats and extended_stats, but cannot find it.

**Comment by eliranmoyal** [comment]
yes use percentiles
SELECT percentiles('age') p FROM yourIndex

**Comment by satapsa** [comment]
If I want to pick only the percentiles 95 and 99, how can I specify the same in the query ?

**Comment by eliranmoyal** [comment]
it is not available now , will be on next version

**Comment by satapsa** [comment]
What is the target date for the next version ? Will it be for Elastcsearch 1.7 as well ?

**Comment by eliranmoyal** [comment]
Ya, hopefully tomorrow

**Comment by satapsa** [comment]
Thanks a lot !!

**Comment by eliranmoyal** [comment]
Hey, haven't finish merging for all versions but here is the one for you
[elasticsearch-sql-1.4.9.zip](https://github.com/NLPchina/elasticsearch-sql/files/181054/elasticsearch-sql-1.4.9.zip)
