### ISSUE TITLE
Plugin Version for Elasticsearch 2.2.1

### ISSUE THREAD

**Issue by loms0815** [NLPchina/elasticsearch-sql#173]
Hi, is it possible to adapt the plugin version 2.2.0 in a way that it's usable for ES trunk version 2.2.1?

**Comment by enzogro** [comment]
+1

**Comment by mwerks11** [comment]
+1 please and thank you.

**Comment by eliranmoyal** [comment]
./bin/plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/2.2.1.0/elasticsearch-sql-2.2.1.0.zip

**Comment by enzogro** [comment]
thank you!!
