### ISSUE TITLE
LIKE space not working

### ISSUE THREAD

**Issue by webgori** [NLPchina/elasticsearch-sql#175]
![error](http://meltyway.kr/data/space.PNG)

LIKE space not working.

**Comment by satapsa** [comment]
Getting no result back for this like

SELECT * from xxx/xxx  where fields_name Like 'SM-G%'

The field values are like

SM-G900V
SM-G920V

**Comment by KangYongKyun** [comment]
it depend on mapping information. 

If you set filed's mapping setting like
```
'{
  "properties" : {
    "field_name" : {
      "type" :    "string",
      "index":    "not_analyzed"
    }
  }
}'
```
, you can get result what you want.

field_name part must be replaced your own field name

**Comment by webgori** [comment]
@KangYongKyun thank you
