### ISSUE TITLE
Got issuse with timestamp ISO

### ISSUE THREAD

**Issue by kevinvn1709** [NLPchina/elasticsearch-sql#176]
Hi eliranmoyal,
I got some problems with data store under format ISO timestamp

My data stored with ISO format timestamp such as "2016-01-01T00:00:00.000+07:00"
I made a query like this:

SELECT datetimeCreate 
FROM installs
WHERE datetimeCreate BETWEEN '2016-01-01T00:00:00.000+07:00' AND '2016-01-01T23:59:59.000+07:00'

I got an error parsing from system (see image below)
http://take.ms/R4swO

and this
http://take.ms/LI5xa

**Comment by eliranmoyal** [comment]
Hey, the mapping for the field is the default for date?

**Comment by eliranmoyal** [comment]
Well I checked and it worked fine on site
Than I checked the api and I got the same error as you did.
checked and it turns out to be url escaping for '+' on browser.
if you need to query with your browser just replace the + with %2B

**Comment by kevinvn1709** [comment]
It worked well. Thanks your works :+1:
