### ISSUE TITLE
Working with "terms" aggs and min_doc_count

### ISSUE THREAD

**Issue by WilsonHo** [NLPchina/elasticsearch-sql#178]
Excuse me, how could I get a "terms" aggs and min_doc_count by SQL?

**Comment by eliranmoyal** [comment]
two ways:
lets say you want to group by a field called firstname
implicit way:
```sql
SELECT * FROM yourIndex
group by firstname
limit 3
```
explicit way:
```sql
SELECT * FROM yourIndex
group by terms('field'=firstname,'size'=3,alias='name')
```

**Comment by WilsonHo** [comment]
oh, this is limit the number of row, I would like a min_doc_count. https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_minimum_document_count_3

**Comment by eliranmoyal** [comment]
Oh, this is not implemented. 
I wasn't aware of this option.. 
I'll add this

**Comment by WilsonHo** [comment]
thank you so much... :+1:

**Comment by eliranmoyal** [comment]
The new version is out :)
