### ISSUE TITLE
like  query problem

### ISSUE THREAD

**Issue by tongchuanwei** [NLPchina/elasticsearch-sql#179]
this  like "_a"   explain like “?a",

**Comment by tongchuanwei** [comment]
select * from monitor 
where result.Content.formattedSql like 'SELECT COUNT(1) AS totalCount FROM (SELECT ID, SYSTEM_NAME, SYSTEM_CODE, SYSTEM_DOMAIN, DEPLOY_POINTS , CACHE_KEY, CACHE_VALUE, CACHE_INDEX, STATUS, DETAILS , CREATE_TIME, UPDATE_TIME FROM DOMAIN WHERE 1 = 1 LIMIT 0, 110 ) _a%'

**Comment by tongchuanwei** [comment]
i  can't  get  this result.

**Comment by tongchuanwei** [comment]
{
	"from": 0,
	"size": 200,
	"query": {
		"filtered": {
			"filter": {
				"bool": {
					"must": {
						"query": {
							"wildcard": {
								"result.Content.formattedSql": {
									"wildcard": "SELECT COUNT(1) AS totalCount FROM (SELECT ID, SYSTEM?NAME, SYSTEM?CODE, SYSTEM?DOMAIN, DEPLOY?POINTS , CACHE?KEY, CACHE?VALUE, CACHE?INDEX, STATUS, DETAILS , CREATE?TIME, UPDATE?TIME FROM DOMAIN WHERE 1 = 1 LIMIT 0, 110 ) ?a*"
								}
							}
						}
					}
				}
			}
		}
	}
}

**Comment by eliranmoyal** [comment]
yes , I'm creating a version with escapes so you will be able to escape _ and %

**Comment by eliranmoyal** [comment]
check the new version
you can escape the _a with &UNDERSCOREa

**Comment by tongchuanwei** [comment]
thank you  very  much!
