### ISSUE TITLE
Problem CSV Format Number with large number

### ISSUE THREAD

**Issue by kevinvn1709** [NLPchina/elasticsearch-sql#181]
Hi,
I got a problem with large number under format CSV, please see the image below:
http://take.ms/fCx4f

I use your http query method:
http://10.8.37.81:9200/_sql/?format=csv&sql=<sql>

My Query string like this:
"SELECT SUM(money)
FROM inappeventpurchases"

Thanks

**Comment by eliranmoyal** [comment]
I'm using elasticsearch java-api and the api returns double for all those aggregations.
this is just the toString of the double..
any suggestions on how to do it more readable? (not really familiar with numbers formattings)

**Comment by WilsonHo** [comment]
Maybe it would help you
Double value = new Double(1234546789);
String str = new DecimalFormat("#").format(value);

**Comment by eliranmoyal** [comment]
Thanks! i will try it :)

**Comment by kevinvn1709** [comment]
Thanks all.
I solved my problem with a helper from programming language. But, I think you should modify format number from source code, because elasticsearch works almost with a huge data and number. So, this feature is really essential.
