### ISSUE TITLE
How can I query data by paging just like mysql..

### ISSUE THREAD

**Issue by MartinKan** [NLPchina/elasticsearch-sql#186]

**Comment by eliranmoyal** [comment]
two options:
1. from & size:
```sql 
LIMIT 10,20
```
will result in from and size parameters for elasticsearch

2. use scrolling , read about it here:
https://github.com/NLPchina/elasticsearch-sql/wiki/Scroll

**Comment by nathan-zhu** [comment]
@MartinKan 发现你了，哈哈

**Comment by MartinKan** [comment]
@nathan-zhu  握个抓~
