### ISSUE TITLE
Unable to install 2.3.0

### ISSUE THREAD

**Issue by g1ylb** [NLPchina/elasticsearch-sql#189]
Hi,

any ideas on the below ?

root@reuxeuls198[Development]# ./bin/plugin install file:///fopimp/elasticsearch-sql-elastic2.3.0.zip
-> Installing from file:/fopimp/elasticsearch-sql-elastic2.3.0.zip...
Trying file:/fopimp/elasticsearch-sql-elastic2.3.0.zip ...
Downloading .......................................DONE
Verifying file:/fopimp/elasticsearch-sql-elastic2.3.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by eliranmoyal** [comment]
Where is the zip from?

**Comment by g1ylb** [comment]
from here selected branch 2.3.0 and downloaded zip, unfortunately our server has no internet access.

**Comment by eliranmoyal** [comment]
you downloaded the code in a zip file..
download the compiled plugin from here:
https://github.com/NLPchina/elasticsearch-sql/releases/download/2.3.0.0/elasticsearch-sql-2.3.0.0.zip
