### ISSUE TITLE
Elasticsearch 2.3.1 Support

### ISSUE THREAD

**Issue by thiagomata** [NLPchina/elasticsearch-sql#199]
Any predictions to support the version 2.3.1?

**Comment by alexott** [comment]
Would be very useful to get the new release...
Maybe there is a way to specify wildcard version, at least inside the major releases?

**Comment by ansjsun** [comment]
it is here ! https://github.com/NLPchina/elasticsearch-sql/releases/tag/2.3.1.0

**Comment by alexott** [comment]
Thank you!

**Comment by cdonnellytx** [comment]
They just released a 2.3.2 yesterday (2016-04-28).

Is there a particular reason you do separate builds for each point release?  Major/minor I understand, but not point releases, since the APIs aren't supposed to change...

**Comment by ansjsun** [comment]
in here !  @dadoonet say:

https://github.com/elastic/elasticsearch/commit/28f82fb568c3185a8ce10c5f09b4dbd33a8bbe9e


````
The opposite is true. If you try to install a version of a plugin which was built with a newer version of elasticsearch, it will fail the same way:

````

but the api not change , only change  pom.xml es.version . and deploy it ...

**Comment by dadoonet** [comment]
Yes. It's a new policy we have. We want to make sure that a plugin has been tested with the version it is supposed to run on.
It creates more work for sure for plugin authors but is a way safer for our users.
