### ISSUE TITLE
GROUP BY 'field' differ GROUP BY terms('field'=deviceId) result value

### ISSUE THREAD

**Issue by WilsonHo** [NLPchina/elasticsearch-sql#201]
I try to with 2 queries: 
SELECT COUNT(*) FROM activities
WHERE appId LIKE '570f3e5ba61682c71a2b320f'
AND timestamp BETWEEN '2016-04-20T00:00:00.000+0700' AND '2016-04-21T00:00:00.000+0700'
GROUP BY terms('field'=deviceId)
and 
SELECT COUNT(*) FROM activities
WHERE appId LIKE '570f3e5ba61682c71a2b320f'
AND timestamp BETWEEN '2016-04-20T00:00:00.000+0700' AND '2016-04-21T00:00:00.000+0700'
GROUP BY deviceId

The 2 queries have 2 result value different, but when I explain and use the json to query, the result ij ok.

**Comment by WilsonHo** [comment]
And how could I use GROUP BY with no limit ?
Thank you so much.
I am looking forward for your help.

**Comment by ansjsun** [comment]
````
And how could I use GROUP BY with no limit ?
Thank you so much.
I am looking forward for your help.
````

you can run `SELECT COUNT() FROM activities
WHERE appId LIKE '570f3e5ba61682c71a2b320f'
AND timestamp BETWEEN '2016-04-20T00:00:00.000+0700' AND '2016-04-21T00:00:00.000+0700'
GROUP BY deviceId limit 0 `
