### ISSUE TITLE
Could elasticsearch-sql support the filter_path??

### ISSUE THREAD

**Issue by ChinaChaos** [NLPchina/elasticsearch-sql#205]
Like that
`curl -XGET 'localhost:9200/_search?pretty&filter_path=took,hits.hits._id,hits.hits._score'
{
  "took" : 3,
  "hits" : {
    "hits" : [
      {
        "_id" : "3640",
        "_score" : 1.0
      },
      {
        "_id" : "3642",
        "_score" : 1.0
      }
    ]
  }
}`
The request response is json，waste too much internet！

LGDM!

**Comment by eliranmoyal** [comment]
I'm using the Java api and I don't think there is a way to translate this. 
If you care about wasting Internet, you can try the format=csv option (check on wiki)

**Comment by ChinaChaos** [comment]
thanks,thats worked!
