### ISSUE TITLE
incompatible with Elasticsearch [2.3.2]

### ISSUE THREAD

**Issue by anuxs** [NLPchina/elasticsearch-sql#206]
Plugin [sql] is incompatible with Elasticsearch [2.3.2]. Was designed for version [2.3.1]

Where is version [2.3.2]?

**Comment by ansjsun** [comment]
支持了,有问题告诉我啊....es的版本号太操蛋了,每个小版本编译一次.简直要命..

**Comment by anuxs** [comment]
用了一段时间，确实解决了。话说我还专门看了变更记录，到底哪些地方需要改版本号。

**Comment by tingking23** [comment]
我在本地单节点测试没有问题能用，但是为啥子放到集群上面就报错了？ 报status 400的错，是不是集群还有其他需要配置？

**Comment by tingking23** [comment]
可以了，不好意思，集群还有其他人在动，陈我不注意给装了个shild权限，不过这个sql界面还是能进，然后就是搜不到结果，输入集群的帐号密码进去sql界面就好了
