### ISSUE TITLE
Field name with back-slash is not explained correctly in where clause.

### ISSUE THREAD

**Issue by lephix** [NLPchina/elasticsearch-sql#209]
Sql:

    SELECT count(*) FROM jupiter  where `/user/car_info/budget` =in_terms("a") group by `/user/car_info/budget`

result of the explain:

    {
		"from": 0,
		"size": 0,
		"query": {
			"filtered": {
				"filter": {
					"bool": {
						"must": {
							"terms": {
								"`/user/car_info/budget`": [
									"a",
									"b"
								]
							}
						}
					}
				}
			}
		},
		"_source": {
			"includes": [
				"COUNT"
			],
			"excludes": []
		},
		"aggregations": {
			"/user/car_info/budget": {
				"terms": {
					"field": "/user/car_info/budget",
					"size": 200
				},
				"aggregations": {
					"COUNT(`/user/car_info/budget`)": {
						"value_count": {
							"field": "`/user/car_info/budget`"
						}
					}
				}
			}
		}
	}

You can see the field in the terms function is still has the quote mark.

	"terms": {
		"`/user/car_info/budget`": [
			"a",
			"b"
		]
	}

**Comment by shi-yuan** [comment]
try
`SELECT count(*) FROM jupiter  where ['/user/car_info/budget'] =in_terms("a") group by `/user/car_info/budget``

Issue [#254](https://github.com/NLPchina/elasticsearch-sql/issues/254) may help you

**Comment by lephix** [comment]
Thanks for your advice. Problem solved.
