### ISSUE TITLE
Optimised aggregated query

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#213]
Is there a way to optimize queries via the sql plugin.
We are running a few aggregated queries and finding the heap size going up dramatically.

Please advise

SELECT location_500  AS mykey,percentiles(abc) AS myval1  FROM xxxx/lxx WHERE date_yy>0  and abc <> null and abc < 10 and abc > -1000 AND code in(107) and country = 'yyyyyyy' and network = 'xxxxx xxxxx' and GEO_BOUNDING_BOX(location,-74.81685161590576,40.613365173339844,-74.59712505340576,40.497236251831055) GROUP BY location_500 LIMIT 0

SELECT location_500  AS mykey,AVG(def) AS myval1  FROM xxxx/xx WHERE date_yy>0  and def < 300 and def > -300 AND mno in(107) and country = 'yyyyyyyy' and network = ‘xxxxx xxxxx’ and GEO_BOUNDING_BOX(location,-74.81685161590576,40.613365173339844,-74.59712505340576,40.497236251831055) GROUP BY location_500 LIMIT 0

**Comment by allwefantasy** [comment]
We think this is all about ES  not ES-SQL.
