### ISSUE TITLE
Any support to return all hits when using aggregation (grouping) ?

### ISSUE THREAD

**Issue by cyber4ron** [NLPchina/elasticsearch-sql#222]
e.g. the explained query of `select ucid, ch_id from online_user_20160516 where _type = 'srh' group by ucid`:
```
{
  "from" : 0,
  "size" : 0,
  "query" : {
    ...
  },
  "_source" : {
    "includes" : [ "ucid", "ch_id" ],
    "excludes" : [ ]
  },
  "fields" : "ucid",
  "aggregations" : {
    ....
  }
}
```
however what I need is:
```
{
  "from" : 0,
  "query" : {
    ...
  },
  "_source" : {
    "includes" : [ "ucid", "ch_id" ],
    "excludes" : [ ]
  },
  "fields" : "ucid",
  "aggregations" : {
    ....
  }
}
```
to return all hits by removing `"size" : 0`.

I'm using elasticsearch-sql(2.3) as jar dependency, so any java api or sql query support will be appreciated.

**Comment by ansjsun** [comment]
the size in group query is 0,

because you need size in aggregations {....};

you see you result .it is ok 

select ucid, ch_id from online_user_20160516 where _type = 'srh' group by ucid limit 0,2000 

but if you group by ucid it only have ucid .not have ch_id .

it result is  ucid , count(ucid) ;

**Comment by cyber4ron** [comment]
Got it. Thanks.
