### ISSUE TITLE
Plugin for elasticsearch 2.3.3.

### ISSUE THREAD

**Issue by Diwahars** [NLPchina/elasticsearch-sql#223]
When will the plugin for elasticsearch 2.3.3. will be released?

**Comment by zhiaixuexi** [comment]
+1

**Comment by seanyoo** [comment]
+1

**Comment by zhiaixuexi** [comment]
@Diwahars @seanyoo 
hi guys,
https://github.com/NLPchina/elasticsearch-sql/releases/tag/2.3.3.0
2.3.3 supported now ~
