### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by happyshows** [NLPchina/elasticsearch-sql#227]
![image](https://cloud.githubusercontent.com/assets/3208181/15750754/3c27c0dc-28ad-11e6-803c-00816c7ad423.png)

OS: WINDOWS 10

**Comment by ansjsun** [comment]
the plugin have been installed！

you can visite

ip：port/_plugin/sql

if page not found 

Remove Es/plugin/sql directory 


Install again 

发自我的 iPhone

**Comment by happyshows** [comment]
sorry , my bad.

**Comment by happyshows** [comment]
when I tried
SELECT * FROM test    <- test is my index name, I saw below error, is this because of wrong installation?

 Error: {"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_sql], must not start with '_'","index":"_sql"}],"type":"invalid_index_name_exception","reason":"Invalid index name [_sql], must not start with '_'","index":"_sql"},"status":400}

Then I tried  http://localhost:9200/_sql?sql=select%20*%20from%20test%20limit%2010

 {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No feature for name [_sql]"}],"type":"illegal_argument_exception","reason":"No feature for name [_sql]"},"status":400}

**Comment by gunererd** [comment]
+1

**Comment by ansjsun** [comment]
i think you need restart server when installed plugin !
