### ISSUE TITLE
Just read-only-access over Elasticsearch-SQL-Plugin

### ISSUE THREAD

**Issue by Selvinaz1984** [NLPchina/elasticsearch-sql#230]
Hello,

is it possible that user has only read-only-access to ES data via SQL-Plugin? Can we configure that anyway?

**Comment by Selvinaz1984** [comment]
Hello Eliran,

I have checked out the code for ES-Plugin 2.3.1 and changed the code in ESActionFactory.create(Client client, String sql), so that in case of DELETE also a SQLFeatureNotSupportedException will be thrown. I want to make this feature configurable but I have seen that there does not exist a configuration file which is used internally in the code, just es-plugin.properties which is generally needed by ES. But I want to commit this change in Git so that at each update we do not want to change this point in code manually each time.

What du you propose?

**Comment by eliranmoyal** [comment]
hey @Selvinaz1984  , sorry for not being online on this project for some time.
I'll add this feature to next version (with the configuration support)
If you already made this with configuration send me your code or create a pull request
