### ISSUE TITLE
Does it support multiple aggs

### ISSUE THREAD

**Issue by cindyming** [NLPchina/elasticsearch-sql#237]
such as 

 
{
    "aggs": {
        "groupby_sex": {
            "terms": {
                "field": "sex",
                "order":{"_count":"desc"}
            }
        },
        "groupby_language": {
            "terms": {
                "field": "language",
                "order":{"_count":"desc"}
            }
        }
    }
}

**Comment by eliranmoyal** [comment]
yes read the wiki
https://github.com/NLPchina/elasticsearch-sql/wiki/Aggregations
on multiple aggregation section
something like
```sql
select ...
group by (sex) , (language)
```
