### ISSUE TITLE
Only top-level fields show up.

### ISSUE THREAD

**Issue by andydude** [NLPchina/elasticsearch-sql#239]
When I run a query from the web interface "/_plugin/sql/" such as

"SELECT load.load1, load.load5, load.load15 FROM topbeat-2016.06.24 where type = 'system'"

I would expect to see 3 columns in the results below, however, but there is 1 column "load" with JSON strings in each cell.

**Comment by eliranmoyal** [comment]
look at the settings on the left side -> flat results
