### ISSUE TITLE
使用date_range类型的Aggregation时不能使用order排序

### ISSUE THREAD

**Issue by xuebing1110** [NLPchina/elasticsearch-sql#240]
explain时报“DateRangeBuilder cannot be cast to TermsBuilder”错误：

`{"error":{"root_cause":[{"type":"class_cast_exception","reason":"org.elasticsearch.search.aggregations.bucket.range.date.DateRangeBuilder cannot be cast to org.elasticsearch.search.aggregations.bucket.terms.TermsBuilder"}],"type":"class_cast_exception","reason":"org.elasticsearch.search.aggregations.bucket.range.date.DateRangeBuilder cannot be cast to org.elasticsearch.search.aggregations.bucket.terms.TermsBuilder"},"status":500}`

执行sql：
`SELECT count(*) as countret 
from myindex 
group by date_range(field='time','now-1h','now','now-1M','now')
order by countret desc`

**Comment by ansjsun** [comment]
date_range 不需要排序...换句话说没有排序功能...是按照你 date_range(field='time','now-1h','now','now-1M','now') 输入的顺序排序的

**Comment by xuebing1110** [comment]
看了下sql解析，明白了：
date_range不支持order，并且sql parse时order使用在最后的aggregation ，所以当只有一个date_rage aggregation 并且排序就报错了。
谢谢回复！
