### ISSUE TITLE
None of the configured nodes are available in ES 2.2.0

### ISSUE THREAD

**Issue by sureshghatuwa** [NLPchina/elasticsearch-sql#245]
For ES 2.2.0:

when i tried to run **mvn test** .. then face with error  **None of the configured nodes are available**
i.e: from client.admin().cluster().**prepareNodesInfo().get()**;
org.nlpcn.es4sql.MainTestSuite: None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9200}]

Please Suggest.

Thanks,

**Comment by shi-yuan** [comment]
Do you startup es? 
Do you install delete-by-query plugin?

**Comment by allwefantasy** [comment]
This bug may  have been fixed  in master branch . It happened cause cluster_name in es-sql  is not consistent with the es instance.

**Comment by allwefantasy** [comment]
You can modify MainTestSuit's setup function . Add lines like following:

```java
Settings settings = Settings.builder().put("client.transport.ignore_cluster_name",true).build();
		client = TransportClient.builder().addPlugin(DeleteByQueryPlugin.class).settings(settings).
				build().addTransportAddress(getTransportAddress());
```

If it do not fix your problem, please reopen this issue.
