### ISSUE TITLE
Allow specifying missing value in group by clause

### ISSUE THREAD

**Issue by shanielh** [NLPchina/elasticsearch-sql#246]
I would like to specify the [missing value](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_missing_value_12) for group by clauses : 

```
select model_id, count(*) from foo group by model_id
```

For example : 

```
select model_id, count(*) from foo group by model_id /* missing "n/a" */
```

**Comment by eliranmoyal** [comment]
Hey @shanielh 
I'm I sorry wasn't working on this for some time.
I'll support this on the next version.
which elasticsearch version are you using? (I will make an hotfix for your version if necessary )

**Comment by shanielh** [comment]
Version 2.1.2

 Thanks.

**Comment by eliranmoyal** [comment]
[elasticsearch-sql-2.1.2.1.zip](https://github.com/NLPchina/elasticsearch-sql/files/413007/elasticsearch-sql-2.1.2.1.zip)

Use it with the full syntax of terms group by
like this:
```sql
SELECT count(*) FROM myIndex/person
group by terms('field'='nickname','missing'='unknown','alias'='nicknames')
```

**Comment by shanielh** [comment]
Thank you very much!

**Comment by allwefantasy** [comment]
@eliranmoyal  This feature have already merged to master?
