### ISSUE TITLE
Eorro:must not start with '_'","index":"_sql"},"status":400

### ISSUE THREAD

**Issue by chensambb** [NLPchina/elasticsearch-sql#247]
{"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_sql], must not start with '_'","index":"_sql"}],"type":"invalid_index_name_exception","reason":"Invalid index name [_sql], must not start with '_'","index":"_sql"},"status":400}

why?

**Comment by ansjsun** [comment]
look at  #29,

i think you need restart your es server

**Comment by chensambb** [comment]
thank you! @ansjsun
I fixed it.
installed this plugins must restart es service.

**Comment by sibennayak** [comment]
Close this issue?
