### ISSUE TITLE
keyword from not work in condition

### ISSUE THREAD

**Issue by honchy** [NLPchina/elasticsearch-sql#254]
select `from` from table_name
       where appName = 'app_name'
       and dateTime >= 'today_date'
       and `from` like 'u%'

I have a column named as 'from', It's a keyword unfortunately。

when it is in select clause , all things just works fine.

 but when I add it to a condition clause, I got nothing back, though It should have data.

would anyone give me a hand

**Comment by eliranmoyal** [comment]
use brackets to escape 
```sql
 select `from` from table_name
   where appName = 'app_name'
   and dateTime >= 'today_date'
   and [`from`] like 'u%'
```

also like will not work if from field is analyzed (using wildcard)

**Comment by honchy** [comment]
@eliranmoyal 

        select `from` from table_name
        where appName = 'app_name'
        and ['from'] like 'u%'

        select `from\` from table_name
        where appName = 'app_name'
        and ['from'] = 'ucenter'


these work fine  .  tks ^_^
