### ISSUE TITLE
Can support where 1 = 1 condition

### ISSUE THREAD

**Issue by ljhabc1982** [NLPchina/elasticsearch-sql#258]
version:2.3.1
select * FROM myindex where1 = 1 

 Error: {"error":{"root_cause":[{"type":"sql_parse_exception","reason":"err find condition class com.alibaba.druid.sql.ast.expr.SQLIntegerExpr"}],"type":"sql_parse_exception","reason":"err find condition class com.alibaba.druid.sql.ast.expr.SQLIntegerExpr"},"status":500}

**Comment by shi-yuan** [comment]
Isn't it `select * FROM myindex` ?

**Comment by ljhabc1982** [comment]
I want can support 
SELECT * FROM wladdress where 1 = 1 (and dynamic condition)

**Comment by shi-yuan** [comment]
Not supported currently. 
But you can use [ScriptQuery](https://github.com/NLPchina/elasticsearch-sql/wiki/ScriptQuery), like:
`SELECT * FROM myindex where script('1 == 1')`

**Comment by ljhabc1982** [comment]
Script disabled
Is there any other way？

**Comment by shi-yuan** [comment]
you can enable script

**Comment by ljhabc1982** [comment]
OK ,thank you

**Comment by shi-yuan** [comment]
Add `script.engine.groovy.inline.search: on` to elasticsearch.yml configuration file and restart the node

**Comment by ljhabc1982** [comment]
OK ,IT WORK

**Comment by allwefantasy** [comment]
`select * FROM myindex where1 = 1 ` is more sql style and `SELECT * FROM myindex where script('1 == 1')` make newbies confuse . So if es-sql support  this future would be more convenience.  So new pr to fix this issue will be created.
