### ISSUE TITLE
How to query the data from multiple types

### ISSUE THREAD

**Issue by vganjare** [NLPchina/elasticsearch-sql#259]
Hi,

How can we query from multiple types? e.g., lets say, we have 10 types available in index, and we want to query from only 3 types from the index. If we think from ElasticSearch query point of view (url based) , something like ES_HOST/INDEX_NAME/TYPE1,TYPE2/_search

Thanks,
Vishal

**Comment by ansjsun** [comment]
select * from INDEX_NAME/TYPE1,INDEX_NAME/TYPE2  where ....

**Comment by allwefantasy** [comment]
@vganjare is right.  So this is not issue and es-sql no need to support since the query url already have this done.
