### ISSUE TITLE
Question on _source and _all

### ISSUE THREAD

**Issue by srijiths** [NLPchina/elasticsearch-sql#263]
Hi Team,

I have an index where i disabled _source and _all in the mapping. I set all the fields as doc_types. So i am able to see and filter it in Kibana. But when i try the same index with this plugin , its not able to show anything. Probably this would be a feature request ?

Thanks

**Comment by eliranmoyal** [comment]
which elasticsearch version are you using?
can you post the mapping?
I'll check this and will prepare a feature for this if possible

**Comment by srijiths** [comment]
ES 2.3.4. Please see the mapping.

```
curl -X PUT "http://$hostname:9200/$index/$doctype/_mapping" -d '{
        "'$doctype'" : {
             "_all": { "enabled": false },
             "_source": { "enabled":false },
       "properties" : {                               
                "val" : {"type":"long", "include_in_all":false},
                "bas_id" : {"type":"string", "index":"not_analyzed"},
                "building_id" : {"type":"string", "index":"not_analyzed"},
                "point_id" : {"type":"string", "index":"not_analyzed"},
                "point_name" : {"type":"string", "index":"not_analyzed"},
                "building_name" : {"type":"string", "index":"not_analyzed"},
                "building_city" : {"type":"string", "index":"not_analyzed"},
                "building_state" : {"type":"string", "index":"not_analyzed"},
                "building_country" : {"type":"string", "index":"not_analyzed"},
                "site_id" : {"type":"string", "index":"not_analyzed"},
                "site_name" : {"type":"string", "index":"not_analyzed"},
                "company_id" : {"type":"string", "index":"not_analyzed"},
                "company_name" : {"type":"string", "index":"not_analyzed"},
                "sval_max" : {"type":"long", "include_in_all":false},
                "sval_min" : {"type":"long", "include_in_all":false},
                "sensorId" : {"type":"string","index":"not_analyzed"},
                "type" : {"type":"string","index":"not_analyzed"},
                "time" : {"type":"date","format":"dd-MM-yyyy HH:mm:ss.SSS"},
                "geo" : {"type":"geo_point"}
           }
        }

}'
```
By default doc_values are enabled by default , even if we say _all and _source as false. https://www.elastic.co/guide/en/elasticsearch/reference/current/doc-values.html

Thank You

**Comment by srijiths** [comment]
@eliranmoyal My bad..I tried some other queries like group by a key . Its working. select * from indexName limit 10 , is not working.

**Comment by eliranmoyal** [comment]
hey @srijiths 
I have noticed it too
But I couldn't able to get the fields on the _search api..
do you know how to do a post request that does not involve aggregations and get the fields and not only the id?

**Comment by srijiths** [comment]
@eliranmoyal You will not get the fields in _search api, since _all is disabled in mapping. So its not searchable.

**Comment by eliranmoyal** [comment]
Oh ok..
So are you having any other problems?

**Comment by srijiths** [comment]
No, but what is the issue in the above query not working and group by works ? Just to understand. Is it possible to extend your back end query end point to address this situvation ? Is it feasible ?

**Comment by eliranmoyal** [comment]
What do you want to see?
From what I tested you can search and filter and see only the amount of docs return.

**Comment by srijiths** [comment]
Yes , thats correct. Apart from the basic select query , do you over see any other query failures with this mapping ? If only this one , i can manage. Otherwise need to think of other options.

**Comment by eliranmoyal** [comment]
Well I've noticed you only get the number of docs.
![image](https://cloud.githubusercontent.com/assets/2933669/17830459/42f9a14a-66d4-11e6-82f2-1245476b79ff.png)

For the next version I am going to add the id column to the results so you'll be able to see it
Also I've noticed it cause a bug on csv format , i'll fix it too

**Comment by eliranmoyal** [comment]
Also I can't say I have tested all the scenarios on this index  (lot of work)
But if you'll have any problem I'll be happy to help

**Comment by srijiths** [comment]
@eliranmoyal Thats great.. Thank You..

**Comment by allwefantasy** [comment]
Since  _source is disabled ,you can only  access the value of fields  which are  in aggregation functions eg.  group by ,sum

**Comment by allwefantasy** [comment]
@srijiths  @eliranmoyal  can we just close this issue?
