### ISSUE TITLE
select count(t.*) as counts ,sum(t.size) from table t error

### ISSUE THREAD

**Issue by flyingandrunning** [NLPchina/elasticsearch-sql#265]
执行以下查询时
select count(t.*) as counts ,sum(t.size) from table t 

result is 

null, null

返回值都是null,

**Comment by eliranmoyal** [comment]
Can you try without the "t"

**Comment by allwefantasy** [comment]
@flyingandrunning The query you mentioned is wrong cause table is keyword . you can try 

```
select count(t.*) as counts ,sum(t.size) from your_table_name t
```

instead of
```
select count(t.*) as counts ,sum(t.size) from table t
```

you can also try run your query  in `http://www.nlpcn.org:9999/web/ ` which provides a convenient way to explain your sql.

**Comment by satapsa** [comment]
This doesnot work
select count(t.*) as counts,sum(t.size) from xxx/locs t

**Comment by ansjsun** [comment]
to。count（*） 
发自我的 iPhone

**Comment by satapsa** [comment]
Got a result for count , but not for size

select count(*) as counts,sum(t.size) from xxx/locs t

**Comment by allwefantasy** [comment]
Yes ,this is a bug .  query like ` select count(*) as counts,sum(t.size) from xxx/locs t group by t.field` do not handle table alias.  We will fix later .

**Comment by allwefantasy** [comment]
@satapsa  @eliranmoyal @ansjsun  New pull request  ( https://github.com/NLPchina/elasticsearch-sql/pull/271  ) have already fix this bug.
