### ISSUE TITLE
SELECT distinct --- Repeat error

### ISSUE THREAD

**Issue by flyingandrunning** [NLPchina/elasticsearch-sql#266]
SELECT distinct(userId) FROM logstash-api-access-2016.08.17 where ip = '112.65.191.239'

some data repeat,

出现部分的数据重复

**Comment by shi-yuan** [comment]
You can eliminate duplicates using [aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/_executing_aggregations.html)

With [term aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html) the results will be grouped by one field

try
`SELECT distinct(userId) FROM logstash-api-access-2016.08.17 where ip = '112.65.191.239' group by userId`

**Comment by wanglifengwf** [comment]
@shi-yuan 
- **sql**
SELECT distinct(name) FROM user
- **explan**
```
{
	"from": 0,
	"size": 200,
	"_source": {
		"includes": [
			"name"
		],
		"excludes": []
	}
}
```
Distict  don't has physical execution plan

**Comment by ansjsun** [comment]
hi @wanglifengwf  i am not sure it support `distinct`

i am sure it support count(distinct(userId)) ;

you can try it 
`SELECT userId FROM logstash-api-access-2016.08.17 where ip = '112.65.191.239' group by userId`

**Comment by eliranmoyal** [comment]
Yeah distinct is not supported (there is no such feature in elasticsearch) 
Count distinct is supported(cardinality feature on elasticsearch) 
I'll make an error when using only distinct on the next version

**Comment by wanglifengwf** [comment]
@eliranmoyal  I'm sorry,I forgot es does not support distinct.thanks!

**Comment by shi-yuan** [comment]
es support [Finding Distinct Counts](https://www.elastic.co/guide/en/elasticsearch/guide/current/cardinality.html)

Find distinct values, use [Terms Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html). And you need to pay attention to how that field you want to get distinct values on is analyzed, meaning you need to make sure you're not tokenizing it while indexing, otherwise every entry in the aggregation will be a different term that is part of the field content.

**Comment by allwefantasy** [comment]
@eliranmoyal  @ansjsun   group by and distinct  some times can  have the same effect  . If  distinct used and group by block not found in sql ,we can just automatically add it for user . 

`SELECT distinct(userId) FROM logstash-api-access-2016.08.17 where ip = '112.65.191.239'`

will be translate to :

`SELECT userId FROM logstash-api-access-2016.08.17 where ip = '112.65.191.239' group by userId `

**Comment by ansjsun** [comment]
@allwefantasy 

or this  

`select topHits('size'=1)  FROM logstash-api-access-2016.08.17 where ip = '112.65.191.239'  group by userId`
