### ISSUE TITLE
How to remove _routing and _parent fields

### ISSUE THREAD

**Issue by wanglifengwf** [NLPchina/elasticsearch-sql#268]
**version**: 2.3.4.0  
- Describe  
  For example :  select x from the user; but the field ”x“ is missing.
- **When I query on the UI**(http://host:9200/_plugin/sql/)  
  No results output.
- when I use java api.
  The sql result :   

| _routing | _parent |  |
| :-- | --: | --: |
| ....... | ........ |  |
- how can use java api output the 'UI''s result

**Comment by ansjsun** [comment]
it return es result ... 

i think the ui skip empty result .

so .you need skip it in your javacode .

**Comment by wanglifengwf** [comment]
hi @ansjsun 
if the result is : 

| _routing | _parent |x |
| :--------| -------: |---:|
|  .......      |  ........   | |
|  .......      |  ........   | |
|  .......      |  ........   | |
|  .......      |  ........   | xvalue |
|  .......      |  ........   | |

**Then the sql is** : select x from the user limit 3;  
When I skip it in my javacode;  
There is no result output.
I want to get the result which has the field 'x'.
I must set the 'where x is not missing' any times,

**Comment by shi-yuan** [comment]
If you want to get the 'UI''s result or get the result which has the field 'x', you should parse the json result
by yourself.

**Comment by wanglifengwf** [comment]
thank you
