### ISSUE TITLE
columnA=columnB in WHERE sentence support

### ISSUE THREAD

**Issue by yt-hub** [NLPchina/elasticsearch-sql#277]
select * from tableName where columnA=columnB and columnC>columnD

**Comment by allwefantasy** [comment]
It's not supported yet for now. However you can use script grammar below:

```
SELECT * FROM myindex where script('doc["a"].value == doc["b"].value')
```

Kind tricky, we will create a PR to make it looks more sql style.

**Comment by allwefantasy** [comment]
check this PR:  https://github.com/NLPchina/elasticsearch-sql/pull/278
