### ISSUE TITLE
Build for elastic search 2.4.0

### ISSUE THREAD

**Issue by yenduttjain** [NLPchina/elasticsearch-sql#285]
This is not a bug but I need release for elastic search 2.4.0 can someone please package and provide me zip or release which works with elastic search 2.4.0

**Comment by peablog** [comment]
mark

**Comment by GuoYuan-DiYiDan** [comment]
@yenduttjain Do u still need 2.4.0.zip? I just download the project and build one by hand.It seems the package works well with Elasticsearch 2.4.0.

**Comment by madkoala** [comment]
@GuoYuan-DiYiDan Could you please let me know how to build this against ES 2.4.0? I'm not familiar with maven build system and elastic search plugin architecture. Thanks.

**Comment by GuoYuan-DiYiDan** [comment]
1.Download the master version and modify the pom.xml file:
  > find "<elasticsearch.version>2.3.5</elasticsearch.version>" in pom.xml file, change its value to 2.4.0
  > find 	
       ......
       <artifactId>elasticsearch-sql</artifactId>
	<version>2.3.5.0</version>
	<packaging>jar</packaging> 
      .....
   change its value to 2.4.0

2.cd to ../elasticsearch-sql-master/ dir, run cmd "mvn clean package assembly:single -DskipTests", then you will get the package you want.

**Comment by GuoYuan-DiYiDan** [comment]
@madkoala  
1.Download the master version and modify the pom.xml file:

find "2.3.5" in pom.xml file, change its value to 2.4.0
find

......
elasticsearch-sql
2.3.5.0
jar 
.....
change its value to 2.4.0
2.cd to ../elasticsearch-sql-master/ dir, run cmd "mvn clean package assembly:single -DskipTests", then you will get the package you want.

**Comment by GuoYuan-DiYiDan** [comment]
@madkoala 
```
1.Download the master version and modify the pom.xml file:

> find "<elasticsearch.version>2.3.5</elasticsearch.version>" in pom.xml file, change its value to 2.4.0
> find
    ...
    <artifactId>elasticsearch-sql</artifactId>
    <version>2.4.0</version>
    <packaging>jar</packaging>
    ...
change its value to 2.4.0

2.cd to ../elasticsearch-sql-master/ dir, run cmd "mvn clean package assembly:single -DskipTests", then you will get the package you want.
```

**Comment by shi-yuan** [comment]
[2.4.0](https://github.com/NLPchina/elasticsearch-sql/releases/tag/2.4.0.0) is released!

**Comment by madkoala** [comment]
Great! Thank you for your effort!!
