### ISSUE TITLE
Cannot use "!=" operator with SELECT statement

### ISSUE THREAD

**Issue by GuoYuan-DiYiDan** [NLPchina/elasticsearch-sql#289]
I want something like this  
{
    ....
   "must_not": {"match": {"post_tags": key_word}}
}.
I write a select statement:
SELECT * FROM test WHERE post_tags != matchQuery("动漫")

and when I hit the "Explain" button of http://localhost/_plugin/sql/, the page gives me an error:
Error: {"error":{"root_cause":[{"type":"sql_parse_exception","reason":"!= is err!"}],"type":"sql_parse_exception","reason":"!= is err!"},"status":500}.

![qq 20160914104230](https://cloud.githubusercontent.com/assets/20035835/18498295/058bfe96-7a68-11e6-98a8-7d23a339c307.png)

So, I guess that elasticsearch-sql doesn't support  "!=" operator,  is that true? And is there any other way to generate the "must not" condition.

**Comment by shi-yuan** [comment]
Support '<>' operator，use '<>' instead

**Comment by GuoYuan-DiYiDan** [comment]
@shi-yuan It works.Thanks.
