### ISSUE TITLE
Top Hit aggregation _source include?

### ISSUE THREAD

**Issue by dangnhdev** [NLPchina/elasticsearch-sql#292]
Hello I've found this great top hits support:
```
SELECT topHits('size'=3, age='asc') FROM test_index
```
which produce the following DSL:
```javascript
{
   "from":0,
   "size":0,
   "_source":{
      "includes":[
         "topHits"
      ],
      "excludes":[

      ]
   },
   "aggregations":{
      "topHits(size=3,age=asc)":{
         "top_hits":{
            "size":3,
            "sort":[
               {
                  "age":{
                     "order":"asc"
                  }
               }
            ]
         }
      }
   }
}
```
How can I define an include field in the above query, which then produce a top hit aggregation as following:
```javascript
{
   "top_hits":{
      "size":3,
      "sort":[
         {
            "age":{
               "order":"asc"
            }
         }
      ]      "_source":{
         "include":[
            "age"
         ]
      }
   }
}
```

Can I have something like this:
```
SELECT topHits('size'=3, age="asc", include='age') FROM test_index
```

Thanks!

**Comment by eliranmoyal** [comment]
hey, this feature is not supported yet
I'll add this soon

**Comment by eliranmoyal** [comment]
its on master now , do you need it for a specific version?

**Comment by dangnhdev** [comment]
Wow! Thank you very much! Can you include it in a current or a new minor release? It will be very helpful :+1:

**Comment by eliranmoyal** [comment]
There you go 

[elasticsearch-sql-2.4.0.1.zip](https://github.com/NLPchina/elasticsearch-sql/files/496114/elasticsearch-sql-2.4.0.1.zip)
install it with path (plugin.bat install  file:PATH_TO_FILE )
I'll fix some more stuff / add features and hopefully will make a formal release this weekend

**Comment by eliranmoyal** [comment]
https://github.com/NLPchina/elasticsearch-sql/releases/tag/2.4.0.1
