### ISSUE TITLE
!= Not supported ?

### ISSUE THREAD

**Issue by rockmgh** [NLPchina/elasticsearch-sql#293]
hello 

Is != not supported ?

SELECT * FROM table where group_a != 1 

 Error: {"error":{"root_cause":[{"type":"sql_parse_exception","reason":"!= is err!"}],"type":"sql_parse_exception","reason":"!= is err!"},"status":500}

**Comment by shi-yuan** [comment]
Support '<>' operator, see [issue](https://github.com/NLPchina/elasticsearch-sql/issues/289)

**Comment by rockmgh** [comment]
Thanks. :)
