### ISSUE TITLE
Support for ES 2.4.1 needed

### ISSUE THREAD

**Issue by madkoala** [NLPchina/elasticsearch-sql#297]
Support for ES 2.4.1 will be needed.

ES 2.4.1 has been released on last week.
In my experiences, current release works fine with ES 2.4.1 by minimal changes in pom.xml file.

**Comment by eliranmoyal** [comment]
Done,

./bin/plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/2.4.1.0/elasticsearch-sql-2.4.1.0.zip
