### ISSUE TITLE
DSL query 

### ISSUE THREAD

**Issue by Prazzy** [NLPchina/elasticsearch-sql#30]
Hi,

These is not an issue, Just checking if it's already available. I am looking for a DSL query generated for every SQL query so that we can understand how it's being translated.

Thanks

**Comment by omershelef** [comment]
Yes you can use the _explain end point. for example:
```
http://localhost:9200/_sql/_explain?sql=SELECT * FROM myindex WHERE age > 20  GROUP BY gender
```
will return this:
```
{
  "size" : 0,
  "query" : {
    "filtered" : {
      "filter" : {
        "bool" : {
          "must" : {
            "range" : {
              "age" : {
                "from" : 20,
                "to" : null,
                "include_lower" : false,
                "include_upper" : true
              }
            }
          }
        }
      }
    }
  },
  "aggregations" : {
    "gender" : {
      "terms" : {
        "field" : "gender",
        "size" : 200
      }
    }
  }
}
```
There is not explain button currently in the website, but we will implement it in the future. 

The explain endpoint is currently broken on the master branch, but I will fix it before creating new release. As long as you will download the latest release 1.2 you will be ok.

**Comment by Prazzy** [comment]
Thanks for the details.
