### ISSUE TITLE
Result in terminal

### ISSUE THREAD

**Issue by UrielRicardo** [NLPchina/elasticsearch-sql#307]
Hello friends, I wonder if it is possible, make the query (select) and get the result, via terminal.
For what I want to do is connect with an api that will make certain action based on the result of the query.
Or if you know another way to do it.

**Comment by eliranmoyal** [comment]
you can use curl
look here :  #174 
You can also use the csv parameter for better reading
https://github.com/NLPchina/elasticsearch-sql/wiki/CSV-result

**Comment by UrielRicardo** [comment]
@eliranmoyal  Thanks so much bro!!!!!!!!!
