### ISSUE TITLE
[enhancement] Add math functions

### ISSUE THREAD

**Issue by daledude** [NLPchina/elasticsearch-sql#32]
It would be useful to have functions similar to mysql such as round, concat, substr, ceil, etc.

```
select ROUND(sum(billedamount),5) as billedamt, max(id) as maxid from table;

select CONCAT(someField,'some text') as someData from table order by LENGTH(someData) desc;
```

**Comment by ansjsun** [comment]
i think in functions do this is not good idea ... but i think we can add it like script ..example: javascript groovy ..or python script do it ... how to implement it ..

**Comment by omershelef** [comment]
It may be possible to implement it, but it will be hard to make it work on every case. 
For fields in default query (not aggregation) you can use scripted field.  Sorting by function also possible using scripting. 
Aggregations is a pretty complex case, there is experimental feature in elasticsearch 1.4 which we can rely on, scripted metric. It provides kind of map reduce support so although its name implies, it may be suitable to creating buckets as well.

**Comment by daledude** [comment]
If someone codes one of the functions I'd like to contribute more by looking at how it was done. I haven't been able to find a thorough resource on scripting so I haven't been able to really wrap my head around it. I admit I haven't looked very hard.

**Comment by otisg** [comment]
+1 for this one.

**Comment by eliranmoyal** [comment]
some implementation of this features now enabled on 1.4.5 using scripts.
look on [scripted_fields](https://github.com/NLPchina/elasticsearch-sql/wiki/Script-Fields)  and scripted_metric on [aggregations page](https://github.com/NLPchina/elasticsearch-sql/wiki/Aggregations)

**Comment by daledude** [comment]
I'll check it out after vacation. Thank you!
