### ISSUE TITLE
is there any way I can check the where condition of month from date column.

### ISSUE THREAD

**Issue by Shashi-GS** [NLPchina/elasticsearch-sql#324]
Hi,
 is there any way I can check the where condition of month from date column?

lets say, Select month(startDate) as monthValue from xyz where monthValue='Oct'

Thanks In Advance,
Shashi

**Comment by eliranmoyal** [comment]
Yes you can
A bit ugly but this will work
```sql
SELECT insert_time FROM elast*/online where 
script('doc["insert_time"].date.monthOfYear==10')
```

read more about it here
https://github.com/NLPchina/elasticsearch-sql/wiki/ScriptQuery
and this is the class that elasticsearch using for more properites
http://joda-time.sourceforge.net/apidocs/org/joda/time/MutableDateTime.html
