### ISSUE TITLE
can't support divide?

### ISSUE THREAD

**Issue by woderia** [NLPchina/elasticsearch-sql#326]
SELECT 
	sale_money/ord_count
FROM data where _type='storage' and id='11111'
and ord_count >0 limit 10
![n w84 1nn 3djpn_k7iyg2](https://cloud.githubusercontent.com/assets/1846796/20469745/22048548-afdd-11e6-813d-157e1a713600.png)

**Comment by allwefantasy** [comment]
Make sure  groovy script is enabled in your es cluster

**Comment by oreak** [comment]
@allwefantasy plan for es5.0?

**Comment by woderia** [comment]
why need groovy? 
Just two column to '+-*/'

**Comment by allwefantasy** [comment]
@oreak We are waiting more people to upgrade es 5.0 .

**Comment by allwefantasy** [comment]
@woderia  groovy is required to support functions eg. split,log, +,-,*,/  which are not  supported originally by ES

**Comment by woderia** [comment]
solve it
1.install groovy
2.add script.engine.groovy.inline.aggs: on
          script.engine.groovy.inline.update: on 
in your.yml

**Comment by oreak** [comment]
@allwefantasy It's time now ,many people have already upgreded to es 5.0
