### ISSUE TITLE
add desc table or show tables command

### ISSUE THREAD

**Issue by ansjsun** [NLPchina/elasticsearch-sql#33]
add desc table or show tables command!
i think it is useful like this 

```
show indexs  ; //return all indexes ;

show [indexName] ; // return all mapping

desc [indexName] ; //return index fields

desc [indexName]/[mapping] ; //return mapping config

```
and if sql end with ";" replace it to empty. 

how about ?

**Comment by jstortz** [comment]
+1

I'll vote for this.

**Comment by eliranmoyal** [comment]
Hey, some questions before i'll try to implement this:
1. on "desc indexName"
what if the index contains more than one type?
2. on "desc [indexName]/[mapping]" do you mean indexName/type? cause if not i don't understand the difference between this and "show [indexName]"

**Comment by eliranmoyal** [comment]
added on 1.4.4
https://github.com/NLPchina/elasticsearch-sql/releases/tag/1.4.4

wiki link
https://github.com/NLPchina/elasticsearch-sql/wiki/Show-Commands
