### ISSUE TITLE
Feature Request: Join data between more than 2 Indices

### ISSUE THREAD

**Issue by Kshopper93** [NLPchina/elasticsearch-sql#330]
This plugin for ElasticSearch is very useful but I have one question. 
How can I join data between three or more indices? 
I get this error-message: "currently supports only 2 tables join".
Is this feature already on your ToDo list? 

A reply would be greatly appreciated.

**Comment by eliranmoyal** [comment]
Hey
well this is a bit complex
I have this in mind and in my todo-list but I didn't start working on it
