### ISSUE TITLE
ParserException illegal sql expr 

### ISSUE THREAD

**Issue by daledude** [NLPchina/elasticsearch-sql#34]
I'm not sure if these are expected behaviors...

Trying to execute this query from the sql web interface... (with or without the semicolon)...

```
SELECT min(id),max(id) FROM logs-2015.01.13;
```

Produces this error...
```
{"error":"ParserException[illegal sql expr : SELECT min(id),max(id) FROM logs-2015.01.13;]","status":500}
```

But, if I add a LIMIT clause then the query executes...
```
SELECT min(id),max(id) FROM logs-2015.01.13 limit 1
```

Also, running the above query with a semicolon at the end produces an error. Note that I also used a semicolon in the first query above for what it's worth...
```
SELECT min(id),max(id) FROM logs-2015.01.13 limit 1;
```
```
{"error":"ParserException[illegal sql expr : SELECT min(id),max(id) FROM TEMP_TABLE limit 1;]","status":500}
```

**Comment by omershelef** [comment]
It looks like a bug, i will fix it on next release

**Comment by omershelef** [comment]
After a quick look at the code, It may be better if you just wrap your index name with backticks.
```
SELECT * FROM `logs-2015.01.13`
```

**Comment by blaxroze** [comment]
I am using eS 1.5.2

Query : 
SELECT * 
FROM myIndex
WHERE campaign_uid = 'd99759c4-3f40-11e5-bc57-04015a317301'

Still got this, eventhought I am using ' '.
Error: {"error":"ParserException[illegal sql expr : SELECT * \nFROM myIndex\nWHERE campaign_uid = 'd99759c4-3f40-11e5-bc57-04015a317301']","status":500}
