### ISSUE TITLE
Support for ES version 2.4.2

### ISSUE THREAD

**Issue by phamptu** [NLPchina/elasticsearch-sql#341]
Elastic search sql is a great & important plugin with our team but since upgrade to 2.4.2, we can't use this plugin anymore because maximum support version is 2.4.1.

Can you support 2.4.2?
Thanks

**Comment by madkoala** [comment]
You can build plugin package which supports ES 2.4.2 with very simple changes on pom.xml.
Just change version of elasticsearch from 2.4.1 to 2.4.2.
