### ISSUE TITLE
regex support

### ISSUE THREAD

**Issue by eliranmoyal** [NLPchina/elasticsearch-sql#345]
#340
look at :
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/query-dsl-regexp-query.html

support all options

maby something like 
```sql
where myField = regexp('h[abc]*','flags',max_determinized_states)
```

**Comment by ansjsun** [comment]
@shi-yuan  can you try it ?

**Comment by shi-yuan** [comment]
I'll try it, but i'm not sure

**Comment by shi-yuan** [comment]
plugin version [2.4.2.1](https://github.com/NLPchina/elasticsearch-sql/releases/download/2.4.2.1/elasticsearch-sql-2.4.2.1.zip), support

**Comment by shi-yuan** [comment]
```sql
select * from account where name = regexp('ha.*', 'INTERSECTION|COMPLEMENT|EMPTY', 10000)
```

**Comment by sanjuktas** [comment]
will it work for Elasticsearch 1.7.1 ?

**Comment by shi-yuan** [comment]
Now support elasticsearch 2.x

**Comment by xiaoshao** [comment]
Cloud I install 2.4.1 in ES 2.4? seems it does not work. there is no version 2.4.2 for ES.  I can use 2.4.2 in which version?

**Comment by CharanSahaj** [comment]
@shi-yuan is it supported in 5.6.4? if not is there anyway to be able to do even basic regex like starts with and ends with?

**Comment by shi-yuan** [comment]
I'll add it soon!

**Comment by shi-yuan** [comment]
[regex support](https://github.com/NLPchina/elasticsearch-sql/commit/f03f83742a7045348a922be7e63c7e6c1f52a091)

**Comment by CharanSahaj** [comment]
I just asked if it's supported and you made changes such that it is, best thing that ever happened to me on github. Thanks a lot :) 👍  @shi-yuan
