### ISSUE TITLE
The plugin support column alias for select

### ISSUE THREAD

**Issue by ChengJi** [NLPchina/elasticsearch-sql#348]

**Comment by ChengJi** [comment]
when i execute 

> `select longitude_latitude_name as name,count(*) as value from event_20161215 group by longitude_latitude_name order by value desc`

return columns 

> `longitude_latitude_name,value`

but not 

> `name,value`

what's going on?
please help me.Thanks.

**Comment by shi-yuan** [comment]
```sql
select longitude_latitude_name as name,count(*) as value from event_20161215 group by name order by value desc
```

**Comment by ChengJi** [comment]
@shi-yuan 
It didn't work.

> `select longitude_latitude_name as name from event_20161215`

return 

> `longitude_latitude_name`

 

but not 

> `name`

**Comment by shi-yuan** [comment]
fields contains name

**Comment by ChengJi** [comment]
@shi-yuan 
I checked it.
fields dose not contains ‘name’

**Comment by ChengJi** [comment]
![default](https://cloud.githubusercontent.com/assets/5689340/21209233/44c62fd0-c2ae-11e6-9d93-a1d7d6811339.png)
@shi-yuan

**Comment by shi-yuan** [comment]
see http response:
![image](https://cloud.githubusercontent.com/assets/8057153/21209866/f617f05e-c2b1-11e6-977c-4286dbafd6c1.png)

**Comment by ChengJi** [comment]
@shi-yuan 
![default](https://cloud.githubusercontent.com/assets/5689340/21210690/19f85c4c-c2b8-11e6-8fbc-c903aacff3c5.png)

my plugin is Version: 2.3.5.0

**Comment by shi-yuan** [comment]
Ah, mine is 2.3.1.0

**Comment by ChengJi** [comment]
Seems to be independent of the version.
Does the plugin support column alias？
@shi-yuan @fxsjy @guettli @perlun @allwefantasy

**Comment by ChengJi** [comment]
@eliranmoyal

**Comment by ansjsun** [comment]
what  is your es version ?

try explain button to  find the query dsl .

let me see

**Comment by ChengJi** [comment]
![default](https://cloud.githubusercontent.com/assets/5689340/21215401/efb8abca-c2db-11e6-8718-be36b543b24d.png)
@ansjsun

**Comment by shi-yuan** [comment]
There may be a problem with your version.
You can check to branch elastic2.4.2, then change elasticsearch.version to 2.3.5 in pom.xml, and package it.

My test: http://localhost:9200/_sql/_explain?sql=select longitude_latitude_name as name from event_20161215

![image](https://cloud.githubusercontent.com/assets/8057153/21227196/d1369f80-c313-11e6-96fe-470c2a011f82.png)

**Comment by ChengJi** [comment]
@shi-yuan OK,thanks.
