### ISSUE TITLE
No endpoint or operation is available at [sql]

### ISSUE THREAD

**Issue by akkivaghasiya5** [NLPchina/elasticsearch-sql#349]
I have installed Elsaticsearch 5.1.1 in ububtu 14.04. Now I have installed this plugin using `/usr/share/elasticsearch/bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/5.1.1.0/elasticsearch-sql-5.1.1.0.zip`. I restarted elasticsearch. But when I'm running web UI (`http://localhost:9200/_plugin/sql`), I'm getting this error

    {
        "error": {
            "root_cause": [
                {
                    "type": "illegal_argument_exception",
                    "reason": "No endpoint or operation is available at [sql]"
                }
            ],
            "type": "illegal_argument_exception",
            "reason": "No endpoint or operation is available at [sql]"
        },
        "status": 400
    }

But when I'm running `http://localhost:9200/_sql?sql=select * from myIndex limit 10` from postman, I'm getting result. So what is the problem to access Web UI?

**Comment by eliranmoyal** [comment]
Hey from elasticsearch 5.0 elastic does not support site plugins anymore 
Read about the release https://github.com/NLPchina/elasticsearch-sql/releases/tag/5.0.1
Or in readme file on a workaround until we will finish kibana plugin
