### ISSUE TITLE
Feature Request:Add feature to join query with two or more  indices

### ISSUE THREAD

**Issue by MaheshSankaran** [NLPchina/elasticsearch-sql#35]
It wiill be very userful if it has join query support.

Regards
Mahesh.S

**Comment by omershelef** [comment]
It might be very hard to satisfy such requirment, elasticsearch itself does not support join queries like relational databases does. The best it can do is add limited support for document joining on parent child relations or use client side join when the number of documents is relatively small.
You have any thoughts on how to implement such thing?

**Comment by jimrice57** [comment]
how about using a union type of function where you can query multiple indexes then combine the data into a single data set?

**Comment by jmcgdz** [comment]
What about joining across multiple types within the same index?

Is that the same problem/issue?

**Comment by jimrice57** [comment]
So here is my scenario - I have an index per week for 52 weeks for 5 years.   Sometimes it would be nice to be able to query week1-5 and week 10-20 - the index structure should be the same but not have a multiple table option in the select does not allow me to perform that operation.  I can do something like week 1* which give me 10 weeks but was looking for a way to pick things without multiple runs.   For example - give me the count and sum of the records that have cola=value from week 1 and 5 and 35?   A union would all me to query each week individually then display then all out.

**Comment by jmcgdz** [comment]
@jimrice57 Is that the aliases usecase?

http://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html

If you can query by aliases I think that will solve your issue.

**Comment by eliranmoyal** [comment]
Hey , I've been working on a version with join support.
Currently only allow EQUAL conditions on join and some other restrictions (no group by and order by support on joins..)
I would really appreciate it if you give it a try

https://github.com/eliranmoyal/elasticsearch-sql

example:
![image](https://cloud.githubusercontent.com/assets/2933669/9706301/ea995aec-54e9-11e5-97b7-a7615bc5c34a.png)

feel free to contact me at (eliran.moyal1 gmail) if you having any trouble or problems :)

**Comment by eliranmoyal** [comment]
limited version of this feature enabled since 1.4 , read about it [here](https://github.com/NLPchina/elasticsearch-sql/wiki/Join)
If you have issues feel free to re-open the issue / create another one :)
