### ISSUE TITLE
es-sql-site-standalone 无法运行

### ISSUE THREAD

**Issue by ivancxj** [NLPchina/elasticsearch-sql#350]
步骤:
1. 下载https://github.com/NLPchina/elasticsearch-sql/releases/download/5.0.1/es-sql-site-standalone.zip 
2. 安装node环境
3. 解压运行 npm install express --save
4. 提示找不到 es-sql-site/site-server/package.json

或者如果用golang写,打成二进制包直接运行会不会更方便点- -

**Comment by shi-yuan** [comment]
这个警告不影响运行，要解决的话，可以手动添加package.json文件，并加上
```json
{
  "dependencies": {
    "express": "^4.14.0"
  }
}
```

**Comment by shi-yuan** [comment]
都是静态页，任意一个http服务器就能运行。
如果用golang写，是不是弄复杂了呢

**Comment by ivancxj** [comment]
好的,谢谢,因为我看到还要安装node环境,所以有此想法- -

**Comment by ivancxj** [comment]
不好意思,没仔细看代码,如果是纯静态页,那我直接用nginx挂载下就可以了
不过你们可以在文档上说明下可能更好点,我还去安装了node环境- -
