### ISSUE TITLE
 can't visit website

### ISSUE THREAD

**Issue by jgshzy** [NLPchina/elasticsearch-sql#362]
version: elastic search 5.1.1

I can visit rest api example:http://192.168.89.128:9200/_sql?sql=select * from user-property-library limit 10;

but i can't visit website:http://192.168.89.128:9200/_plugin/sql

error:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No endpoint or operation is available at [sql]"}],"type":"illegal_argument_exception","reason":"No endpoint or operation is available at [sql]"},"status":400}

Does anyone know how to solve this problem?

**Comment by eliranmoyal** [comment]
Read release notes/readme, there is a standalone website now. Elasticsearch no longer support plugin websites since elasticsearch5.0
