### ISSUE TITLE
How to get a prefix query

### ISSUE THREAD

**Issue by kevitra** [NLPchina/elasticsearch-sql#363]
I am querying on file data that is stored in typical UNC paths such as 
\\test\test_data\this is test\

I am trying to get all of the data only under the path above.  The issue is that we also have a path with a similar name:
\\test\test_data\this is test - copy\
and I cannot figure out how to query to exclude the "- copy" folder.  

Using Elastic directly the query that works is:
 "query": {
    "bool": {
      "must": [
        {
          "prefix": {
            "fullPath": "\\\\test\\test_data\\this is a test\\"
          }
        }
      ],
      "must_not": [],
      "should": []
    }
  }
As long as I have the trailing end slash the query properly returns only the data in that folder.

I have not been able to figure out the SQL to feed into this plugin to recreate the above JSON.  If I use
select sum(mydata)from ourdata where fullPathForSearch = '\\\\test\\test_data\\this is test\\'
the return value is
"match" : {
              "fullPath" : {
                "query" : ""\\\\test\\test_data\\this is a test\\"
                "type" : "phrase"
              }
            }
This returns the data from the correct folder and also the data within the "this is a test - copy" folder.  

If I use 
select sum(mydata)from ourdata where fullPathForSearch like '\\\\test\\test_data\\this is test\\*'
The return JSON is 
"wildcard" : {
              "fullPath" : '\\\\test\\test_data\\this is test\\*'
            }
which returns 0 hits.

I have two fields I have been using to test against, fullPath that has the Elastic path_tokenizer applied and another, fullPathForSearch that is a standard string.  I've tried the above with both.
Any guidance would be greatly appreciated!

**Comment by kevitra** [comment]
Any updates on this?  I haven't found a way to make an Elastic prefix query with this API.  Thanks

**Comment by shi-yuan** [comment]
```sql
select sum(mydata)from ourdata where fullPathForSearch like '\\\\test\\\\test&UNDERSCOREdata\\\\this is test\\\\*'
```

**Comment by kevitra** [comment]
Thank you.  I had tried using 'like' but I didn't have enough slashes.
