### ISSUE TITLE
es-sql-site-standalone not working

### ISSUE THREAD

**Issue by SubiRUN** [NLPchina/elasticsearch-sql#364]
`$http.post($scope.url + "_sql", query)`
There is no listener on "mydomain:8080/_sql". 
If I modify url to "mydomain:9200/_sql", cross-origin ajax issue will happen.

**Comment by SubiRUN** [comment]
How about the following solution?
es-sql project: 
Add Access-Control-Allow-Origin response header in class org.elasticsearch.plugin.nlpcn.RestSqlAction

es-sql-site project: 
Add a config file including username, password, ip, port of ES
Add Authorization header and modify request url

**Comment by shi-yuan** [comment]
enable [cors](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html) and set `http.cors.allow-origin`

**Comment by SubiRUN** [comment]
@shi-yuan then es-sql project don't have to change in solution 1

**Comment by SubiRUN** [comment]
I have implemented **solution 2** in java

**Comment by SubiRUN** [comment]
@shi-yuan this issue still exist. es-sql-site-standalone in this repo is still not working because of authorization problems. My workaround solution may cause security issues if this site deployed on unprotected environment.

**Comment by shi-yuan** [comment]
In my opinion, it's right to enable [cors](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html) on elasticsearch.yml

**Comment by SubiRUN** [comment]
es-sql-site-standalone is still not working even if cors enabled on elasticsearch.yml. Standalone means to deploy on a different host:port, so the "Authorization" request header needs to be passed to ES. The value of "Authorization" request header is "Basic base64(username:password)", so es-sql-site-standalone need to know username, password, ip, port of ES

**Comment by shi-yuan** [comment]
It is a good idea

**Comment by shi-yuan** [comment]
Http request add header: 
```javascript
{
    headers: {
        "Authorization": "Basic " + window.btoa(username + ":" + password)
    }
}
```

**Comment by shi-yuan** [comment]
Thanks, I'll add it soon.

**Comment by SubiRUN** [comment]
thx, fixed in [5d19ee3](https://github.com/NLPchina/elasticsearch-sql/commit/5d19ee3d7f271b86d700d52024262e01fa00e192)

**Comment by SubiRUN** [comment]
to use site on es 5.x, 
enable cors and visit "mydomain:8080?username=xxx&password=xxx&base_uri=encodedURI" to config es settings

**Comment by madhuA14** [comment]
Hey Guys,

I am using Elasticsearch 5.1.2, I have below configuration in elasticsearch.yml file

```
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type, Content-Length
```

I am using elasticsearch-sql-site-standalone downloaded from https://github.com/NLPchina/elasticsearch-sql/releases/download/5.0.1/es-sql-site-standalone.zip

I am trying to access my elasticsearch-sql site but getting error 'Error occured! response is not avalible', please refer below screenshot. what am I missing ?

![image](https://cloud.githubusercontent.com/assets/8759619/22829820/574d6382-efca-11e6-8a70-54184b6b3c03.png)
