### ISSUE TITLE
Does the codes of branch "master" support elasticsearch v2.3.5?

### ISSUE THREAD

**Issue by BillGrim** [NLPchina/elasticsearch-sql#365]
The elasticsearch environment of the company I am working for is based on V2.3.5. And we need to modify the plugin to support more features of elasticsearch. It seems the branch for v2.3.5 is closed, so I wonder if the newest branch "master" can be used for V2.3.5. I'd appreciate it if you can give me some advice.

**Comment by shi-yuan** [comment]
you can download [elasticsearch-sql-2.3.5.0.zip](https://github.com/NLPchina/elasticsearch-sql/releases/download/2.3.5.0/elasticsearch-sql-2.3.5.0.zip)
or
you can check to branch elastic2.4.0, then change elasticsearch.version to 2.3.5 and package it by youself

**Comment by shi-yuan** [comment]
now branch "master" support elasticsearch v5.x

**Comment by BillGrim** [comment]
OK. Thank you!
