### ISSUE TITLE
Cannot POST /_sql

### ISSUE THREAD

**Issue by ricardoj-br** [NLPchina/elasticsearch-sql#379]
After SQL plugin installation I am receiving the following message ("Cannot POST /_sql\n") . It does not matter what kind of SQL Query I have, even just clicking at the Search botton do it. See the screenshot
![elk_sql_error-01](https://cloud.githubusercontent.com/assets/20463353/22227944/419eddd6-e1b5-11e6-893f-fcf261287f23.png)

My elasticsearch.yml file has this configuration at the very end of it

http.cors.enabled: true

http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type, Content-Length

Elasticsearch version 5.1.1

Can someone point me what is wrong / what else must de done ?

**Comment by ansjsun** [comment]
es-sql-site-standalone not working #364

**Comment by suncz** [comment]
I also have this question,can you tell me how do you solve it

**Comment by ricardoj-br** [comment]
Hi suncz I'm still looking for a solution. Since the version 5.X I can not use /sql queries from my browser. I did manage to install "site-server" but it's not the same.

**Comment by ricardoj-br** [comment]
In a Meetup event here in Brazil people from Elastic told they are working on a SQL query engine but they can not disclosure if or when it will be available !
