### ISSUE TITLE
Is there any plan for ES 5.2.0?

### ISSUE THREAD

**Issue by kyunooh** [NLPchina/elasticsearch-sql#381]
This plugin looks awesome. 

I updated my ES recently(actually this is my mistake...)
but I couldn't find for ES 5.2 and issues either.

If there is plan for ES 5.2, let me know
Finally thank you for developing this plugin :D

**Comment by chuanconggao** [comment]
Really hope to see the support for 5.2.0 soon. 👍

**Comment by ansjsun** [comment]
you can clone  this project 

https://github.com/NLPchina/elasticsearch-site


and run ....


visite http://localhost:8080/web/sql/ to use it .


not need install plugin in es , support all 5.x

**Comment by ottboy4** [comment]
Will Elastic 5.2.0 (and newer versions) be supported going forward as a plugin (without the site)? I am purely looking for the plugin's API support (_sql). Or is all support switching over to the elasticsearch-site?

@eliranmoyal

**Comment by ansjsun** [comment]
In the past period of time , we have more workds at relase new version , but not add new feature in plugin.
we are tired for es version .
At least third of the current es development plugin is not very friendly .
So we added a es-site to deal with,  this is just an experiment .

**Comment by billmartschenko** [comment]
What happens if we install the plugin on a 5.2.x deployment of ES?  Will it fail to install?  Will it install and always fail?  Will it install and work generally but isn't fully tested/supported yet?

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/releases/tag/5.2.0.0
