### ISSUE TITLE
Order by Nested Fields

### ISSUE THREAD

**Issue by kaioken** [NLPchina/elasticsearch-sql#387]
Hi, we are trying to sort by nested fields but have found it not working correctly  .

Using elastic 2.4.2
```
SELECT id,
       first_name,
       last_name,
       companiesoffices.companies.name,
FROM participants
ORDER BY nested(companiesoffices.companies.name) desc LIMIT 0, 100
```
Thanks

**Comment by KristapsF** [comment]
Using version 2.4.5 the same problem occurs.
What can be done to solve this?
