### ISSUE TITLE
incorrect dsl generation for 'IN' operator

### ISSUE THREAD

**Issue by nkastur** [NLPchina/elasticsearch-sql#40]
SQL input:
select  field1,field2 FROM index1  WHERE field3 in (5,7,9)

output as shown by explain tool:
{
  "from" : 0,
  "size" : 200,
  "post_filter" : {
    "bool" : {
      "must" : {
        "range" : {
          "field3" : {
            "from" : 5,
            "to" : 7,
            "include_lower" : true,
            "include_upper" : true
          }
        }
      }
    }
  },
  "fields" : [ "field1", "field2" ]
}

when I try to execute the above query (edited)  , I always find query returns fault results. When I further analyze to see how the SQL to DSL conversion is happening, I see the 'IN' usage is converted to 'range'   in DSL which I believe is incorrect. It show be ideally be using "terms" filter I believe. Please correct me if I am wrong.

**Comment by omershelef** [comment]
what version of elasticsearch-sql are you using?
this bug was already fixed.

**Comment by nkastur** [comment]
Hi omershelef ,

Thanks for the response. Here are the details -

Elastic search version : 

{
  "status" : 200,
  "name" : "myhost",
  "cluster_name" : "myCluster",
  "version" : {
    "number" : "1.4.2",
    "build_hash" : "927caff6f05403e936c20bf4529f144f0c89fd8c",
    "build_timestamp" : "2014-12-16T14:11:12Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"
  },
  "tagline" : "You Know, for Search"
}

SQL plugin version -

elasticsearch-sql-1.4.1 ( elasticsearch-sql-1.4.1.jar).


Please let me know if you need more details.

**Comment by ansjsun** [comment]
hi @nkastur i use it in to explan query like this 

result is 

````
{
  "from" : 0,
  "size" : 200,
  "query" : {
    "filtered" : {
      "filter" : {
        "bool" : {
          "must" : {
            "or" : {
              "filters" : [ {
                "query" : {
                  "match" : {
                    "field3" : {
                      "query" : 5,
                      "type" : "phrase"
                    }
                  }
                }
              }, {
                "query" : {
                  "match" : {
                    "field3" : {
                      "query" : 7,
                      "type" : "phrase"
                    }
                  }
                }
              }, {
                "query" : {
                  "match" : {
                    "field3" : {
                      "query" : 9,
                      "type" : "phrase"
                    }
                  }
                }
              } ]
            }
          }
        }
      }
    }
  },
  "_source" : {
    "includes" : [ "field1", "field2" ],
    "excludes" : [ ]
  }
}

````

so you can install 

./bin/plugin -u https://github.com/NLPchina/elasticsearch-sql/releases/download/1.3.1/elasticsearch-sql-1.3.1.zip --install sql


and visit http://localhost:9200/_plugin/sql/

try your sql ...

**Comment by nkastur** [comment]
Hi omershelef ,

With elasticsearch 1.4.1 and sql plugin 1.3.1 , the explain query generates the exact query as above. Thank you so much .
