### ISSUE TITLE
elasticsearch sql question

### ISSUE THREAD

**Issue by haomer** [NLPchina/elasticsearch-sql#404]
If SQL is too long, the request will not be sent。
eg: http://localhost:9200/_sql?sql=queryString.
The queryString has a length of more than 4KB and the request fails. Is there any other way?

**Comment by zhanghao1013** [comment]
@eliranmoyal @perlun @olleolleolle @fxsjy @guettli @allwefantasy

**Comment by zhanghao1013** [comment]
#174
