### ISSUE TITLE
支持5.3.0吗

### ISSUE THREAD

**Issue by longshang** [NLPchina/elasticsearch-sql#405]
你好，请问支持5.3.0吗？安装elasticsearch-plugin install elasticsearch-sql.zip，提示：ERROR: Unknown plugin elasticsearch-sql.zip

**Comment by ansjsun** [comment]
你可以下载下来个zip然后把里面的... plugin-descriptor.properties 里面的es版本改成你的版本..
然后放到es的plugin目录下,不出意外就可以运行了

**Comment by MR-JDY** [comment]
@ansjsun 你好   这个sql  是相当于在用普通查询语句的时候就已经自动进行了es操作吗？  我很想知道在有数据库   es   java应用程序的三者同时存在的时候的工作原理  望不吝赐教  qq 756528875

**Comment by MR-JDY** [comment]
@ansjsun 而且我的是windows
