### ISSUE TITLE
通过WEB访问，提示下面的错误

### ISSUE THREAD

**Issue by longshang** [NLPchina/elasticsearch-sql#411]
<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /_sql</pre>\n</body>\n</html>\n

**Comment by longshang** [comment]
不好意思，我知道问题了。是我没有改IP地址

**Comment by zhan-yl** [comment]
请问您是怎么解决的？我也碰到这个问题了
 Error: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /_sql</pre>\n</body>\n</html>\n"

**Comment by winfys** [comment]
把web界面右上角的url改成es的地址

**Comment by winfys** [comment]
把web界面右上角的url改成es的地址
