### ISSUE TITLE
how to use date_format function

### ISSUE THREAD

**Issue by yanquanyu** [NLPchina/elasticsearch-sql#412]
I want to use date_format function to format the date field, but it fails.
`select date_format(a.IN_DATE,'yyyyMMddHHmm') AS IN_DATE from index/type`
The following is the exception message:
`Caused by: java.lang.IllegalArgumentException: Unknown call [format] with [1] arguments on type [Date].

at org.elasticsearch.painless.Executable$Script.compile(def date_format_344459093 = new Date(doc['IN_DATE'].value - 8*1000*60*60).format('yyyyMMddHHmm') ;return date_format_344459093;:74)`

**Comment by shi-yuan** [comment]
```json
{
	"from": 0,
	"size": 200,
	"_source": {
		"includes": [],
		"excludes": []
	},
	"script_fields": {
		"IN_DATE": {
			"script": {
				"inline": "def date_format_1009785701 = new SimpleDateFormat('yyyyMMddHHmm').format(new Date(doc['a.IN_DATE'].value - 8*1000*60*60));return date_format_1009785701;",
				"lang": "painless"
			},
			"ignore_failure": false
		}
	}
}
```
