### ISSUE TITLE
查询的字段中包含特殊字符 冒号 出现问题

### ISSUE THREAD

**Issue by dick318** [NLPchina/elasticsearch-sql#417]
我要查询的是mac字段，是string类型，mac中包含“:”冒号     如 80:ed:2c:ca:33:d3

1、如果用like查询
SELECT * from  test3 where mac like '80%'  这么写，不包含: 是可以查询的
但是如果SELECT * from  test3 where mac like '80:%' 这么写  就查不到了

2、如果用 = 查询
下面这些查询有结果
SELECT * from  test3 where mac = '80:ed:2c:ca:33:d3'
SELECT * from  test3 where mac = '80:ed:2c:ca:33:'
SELECT * from  test3 where mac = '80:ed:2c:ca:33'
SELECT * from  test3 where mac = '80:ed:2c:ca:'
SELECT * from  test3 where mac = '80:ed:2c:ca'
SELECT * from  test3 where mac = '80:ed:'
SELECT * from  test3 where mac = '80:ed'
SELECT * from  test3 where mac = '80:'
SELECT * from  test3 where mac = '80'

下面这些查询 返回为空
SELECT * from  test3 where mac = '80:ed:2c:ca:33:d'
SELECT * from  test3 where mac = '80:ed:2c:ca:3'
SELECT * from  test3 where mac = '80:ed:2c:c'
SELECT * from  test3 where mac = '80:ed:2c:'
SELECT * from  test3 where mac = '80:ed:2c'
SELECT * from  test3 where mac = '80:ed:2'
SELECT * from  test3 where mac = '80:e'
SELECT * from  test3 where mac = '8'

实在不懂为什么这样

**Comment by shi-yuan** [comment]
mac字段，用了哪个analyzer？不是keyword吧？

**Comment by dick318** [comment]
我不知道你说的，我是用的logstash采集的数据
配置如下
input {  
  file {  
    path => "/datacenter/web/data/*.log"  
    start_position => beginning  
    codec => plain
  }  
}  


filter {
  mutate {
    split => { "message" => "," }
      add_field => {
        "reporttime" => "%{message[0]}"
        "jzqchl" => "%{message[1]}"
        "mserialid" => "%{message[2]}"
        "mserialidbak" => "%{message[2]}"
        "mac" => "%{message[3]}"
        "macbak" => "%{message[3]}"
        "imei" => "%{message[4]}"
        "idfa" => "%{message[5]}"
        "idfabak" => "%{message[5]}"
        "androidid" => "%{message[6]}"
        "rss" => "%{message[7]}"
     }
     remove_field => [ "message" ]
  } 

  mutate {
        gsub => ["macbak", "[:]", ""]
	gsub => ["idfabak", "[-]", ""]
        gsub => ["mserialidbak", "[:]", ""]
      }

  date {  
     match => [ "reporttime", "yyyy-MM-dd HH:mm:ss" ]  
  } 

}


output {
  elasticsearch {
  hosts => "localhost:9200"
  index => "test1" 
  #index => "level-one-%{+YYYY.MM.dd}"
  codec => plain
  user => elastic
  password => changeme
  }
  stdout { codec => json_lines }
}

**Comment by ansjsun** [comment]
@dick318 冒号是不是需要转译一下...你试试 "80\:"

**Comment by dick318** [comment]
知道解决办法了  导入数据之后 es会自动产生一个keyword字段，比如mac字段会产生一个mac.keyword,用这个字段查询就没问题了
