### ISSUE TITLE
elasticsearch-sql 5.2.2提示illegal_argument_exception问题

### ISSUE THREAD

**Issue by pbgxh04007** [NLPchina/elasticsearch-sql#418]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No endpoint or operation is available at [sql]"}],"type":"illegal_argument_exception","reason":"No endpoint or operation is available at [sql]"},"status":400}

**Comment by harveysun** [comment]
How do you fix it?thank you

**Comment by pbgxh04007** [comment]
in order to use site on elasticsearch 5.x download and extract site[https://github.com/NLPchina/elasticsearch-sql/releases/download/5.0.1/es-sql-site-standalone.zip]
cd site-server
npm install express --save
node node-server.js
