### ISSUE TITLE
Filter field name contain "@" in join query

### ISSUE THREAD

**Issue by MaskedGarfield** [NLPchina/elasticsearch-sql#426]
Hi, I tried a join query:
```
SELECT * FROM A_index as A
 join B_index as B on A.col3 = B.col3
 where `B.@timestamp`>1491580800000 AND `B.@timestamp`<1492444800000
```

But it throw an error like this:
`
{"error":{"root_cause":[{"type":"sql_parse_exception","reason":"fieldName : `B.@timestamp` on codition:AND `B.@timestamp` GT 1491580800000 does not contain alias"}],"type":"sql_parse_exception","reason":"fieldName : `B.@timestamp` on codition:AND `B.@timestamp` GT 1491580800000 does not contain alias"},"status":500}
`

It seems result from "@", how could I make it work?

**Comment by shi-yuan** [comment]
```sql
SELECT * FROM A_index as A
 join B_index as B on A.col3 = B.col3
 where ['B.@timestamp']>1491580800000 AND ['B.@timestamp']<1492444800000
```
