### ISSUE TITLE
like "%百度%" no result

### ISSUE THREAD

**Issue by fanyoujian** [NLPchina/elasticsearch-sql#428]
when i run  sql = "select * from test where name like '%百%'" return 百度

when  sql = "select * from test where name like '%百度%'" no return 百度

why is ?

**Comment by shi-yuan** [comment]
The name field uses the standard analyzer？

**Comment by fanyoujian** [comment]
yes

**Comment by fanyoujian** [comment]
this my mapping 

![image](https://cloud.githubusercontent.com/assets/10875463/26087059/2d2f652c-3a21-11e7-9aef-7f55d809e737.png)

**Comment by fanyoujian** [comment]
this issue is ok , think you
