### ISSUE TITLE
notEqual

### ISSUE THREAD

**Issue by furiousbanana** [NLPchina/elasticsearch-sql#429]
What is the operator for not equal query? I tried !=, ≠, notEqual and none of them works. I need to run following query:
select * from logs where logId != "1234"

**Comment by furiousbanana** [comment]
Never mind. found it. Its <>

**Comment by zivszheng** [comment]
select * from logs where logId <> logId2 (logId2 假定是logs表的另一个字段)  怎么支持呢？

**Comment by shi-yuan** [comment]
用[Script Query](https://github.com/NLPchina/elasticsearch-sql/wiki/ScriptQuery)

**Comment by zivszheng** [comment]
我现在有如下SQL：
select * from trip where status.keyword = term('SUCCESS') and startSite <> endSite；(startSite, endSite 是trip表的两个字段）怎么实现？

**Comment by shi-yuan** [comment]
```sql
select * from trip where status.keyword = term('SUCCESS') and script('!Objects.equals(doc["startSite"].value,doc["endSite"].value)
```

**Comment by zivszheng** [comment]
tks！！！！
