### ISSUE TITLE
Underscore gets replaced with question mark

### ISSUE THREAD

**Issue by jheimbouch** [NLPchina/elasticsearch-sql#43]
When executing the following SQL query,

http://localhost:9200/_sql/_explain?sql=select+*+from+revisions+where+%28dDocTitle+LIKE+%27%251018_8161%25%27++OR++dDoc_Title+LIKE+%27%25AEIA-KPUMCN%25%27%29+AND+xGF_1+LIKE+%27MMI_App%25%27

The plugin generates the translated SQL into Elastic Syntax. It incorrectly turns the underscores into question marks. Please see the attached image to see it in action.

Is this something done on purpose? --EDIT: I see that on line 141 in Maker.java, you are explicitly doing the replace.
![rcsbase_win7](https://cloud.githubusercontent.com/assets/4997688/6603685/ac1cff2e-c7f1-11e4-8b29-95524ce36430.png)

**Comment by omershelef** [comment]
In sql LIKE the charcter _ represenets one character of any type this equivalant to the ? In elasticsearch wildcard query

**Comment by ansjsun** [comment]
could you help me try some case like 

"*123abc*"
"*abc def*"

what is you analysis is keyword ? or others ...

i think is analysis to split it ...

**Comment by jheimbouch** [comment]
@omershelef, if I wanted to use the string literal "_" in my LIKE clause, how would I do that?

When it sets the _ to ?, it could match something that doesn't actually have an _.
