### ISSUE TITLE
Having issues with Operator Precedence when enclosed with in brackets 

### ISSUE THREAD

**Issue by bsreekanth** [NLPchina/elasticsearch-sql#44]
We have a case  where we create dynamic queries depending on the user criteria and user permission.
with this we may land up creating queries like 

(firstname LIKE 'A%%' OR firstname LIKE 'B%%') AND (firstname LIKE 'C%%' OR firstname LIKE 'D%%')

this may end up giving no result when executing in sql . But when using elasticsearch-sql it is just adding up all the criteria under should{} with out considering AND .

**Comment by jheimbouch** [comment]
I can confirm, that this does not take into account the AND.

![desktop_json_ _src](https://cloud.githubusercontent.com/assets/4997688/6674000/e8d1f40a-cbe4-11e4-9290-67fd154a270f.png)

My evaluation, would be that this is the correct output:

![desktop_json_ _src](https://cloud.githubusercontent.com/assets/4997688/6674114/930aeabc-cbe5-11e4-9d27-0138673396b8.png)

**Comment by jstortz** [comment]
@bsreekanth have you found other combinations that don't work?

**Comment by jheimbouch** [comment]
@bsreekanth Pull Request #49 fixes this problem.
