### ISSUE TITLE
essql 打开文件句柄太多 无法回收问题

### ISSUE THREAD

**Issue by hungrytortoise** [NLPchina/elasticsearch-sql#440]
用essql 做一次查询 会打开很多文件句柄，并且无法回收 达到服务器上限后，查询服务就挂掉了。
es是：5.3.0的版本
![image](https://user-images.githubusercontent.com/25096206/26911444-1b3835c0-4c40-11e7-8d5d-6d7f08b8e7a6.png)
每查询一次 打开的文件句柄 就增加 并且无法回收。
在代码中的连接 也已经全部关闭了。

**Comment by sunsence** [comment]
@hungrytortoise 如何解决的这个问题呢

**Comment by shi-yuan** [comment]
文件句柄的问题，可以尝试用[File Leak Detector](http://file-leak-detector.kohsuke.org/)排查一下

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/pull/756
