### ISSUE TITLE
why response the error 401?

### ISSUE THREAD

**Issue by foreverjay** [NLPchina/elasticsearch-sql#441]
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/_sql]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication token for REST request [/_sql]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}

**Comment by shi-yuan** [comment]
Have you add authentication to request headers？

**Comment by xiaoxuan220** [comment]
You can try,like this    http://sql-server:8080/?username=test_user&password=test_password&base_uri=http://es_server:9200
