### ISSUE TITLE
multipolygon

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#442]
Does the sql polygon supports multipolygon ? If yes, can you provide an example ?

**Comment by shi-yuan** [comment]
```sql
SELECT * FROM location WHERE GEO_INTERSECTS(place,'MULTIPOLYGON (((30 20, 45 40, 10 40, 30 20)),
((15 5, 40 10, 10 20, 5 10, 15 5)))')
```

**Comment by satapsa** [comment]
I am on sql plugin version 1.4.8 and Elasticsearch 1.7. Are the values in MULTIPLOYGON  in lat, lon format ?

SELECT * FROM xxx WHERE GEO_INTERSECTS(location,'MULTIPOLYGON (((-106.137103  31.662889,-106.124132  31.656255,106.095866  31.634966)),
((-106.263776  31.666654,-106.242391 31.673099,-106.204974 31.554178)))')

location is defined as a geo_point

Getting the following error
 Error: {"error":"SqlParseException[couldn't create shapeBuilder from wkt: 'MULTIPOLYGON (((-106.137103 31.662889,-106.124132 31.656255,106.095866 31.634966)), ((-106.263776 31.666654,-106.242391 31.673099,-106.204974 31.554178)))']","status":500}
