### ISSUE TITLE
date type  compare

### ISSUE THREAD

**Issue by dlhzt** [NLPchina/elasticsearch-sql#443]
I want this:
SELECT insert_es_time,event_time FROM log_20170613
where (insert_es_time-event_time) < 3 min

AnyOne , How  to be achieved it ？  Thanks

@olleolleolle @fxsjy @mtdavidson @perlun

**Comment by shi-yuan** [comment]
```sql
SELECT insert_es_time,event_time FROM log_20170613 where script('doc["insert_es_time"].value - doc["event_time"].value < 180000')
```

**Comment by dlhzt** [comment]
@shi-yuan  thanks, But create error info :
 Error: {"error":{"root_cause":[{"type":"script_exception","reason":"scripts of type [inline], operation [search] and lang [groovy] are disabled"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"dfs","grouped":true,"failed_shards":[{"shard":0,"index":"log_20170613","node":"7bSWK084ROiPak49a3UBqA","reason":{"type":"script_exception","reason":"scripts of type [inline], operation [search] and lang [groovy] are disabled"}}]},"status":500}

**Comment by shi-yuan** [comment]
elasticsearch.yml:
```yml
script.inline: true
script.indexed: true
```

**Comment by dlhzt** [comment]
Thank you very much !!! @shi-yuan
