### ISSUE TITLE
Cannot POST /_sql

### ISSUE THREAD

**Issue by unbendingWind** [NLPchina/elasticsearch-sql#450]
按照官网上进行安装es-sql，访问http://localhost:8080后，在SQL QUERY里面请求SELECT * FROM test
但是提示
`"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /_sql</pre>\n</body>\n</html>\n"`

**Comment by shi-yuan** [comment]
这个地址，改了吗？
![image](https://user-images.githubusercontent.com/8057153/27208325-9d1b54e0-5277-11e7-8b5b-8c9e7a32e6ed.png)

**Comment by unbendingWind** [comment]
你好。我改成了8089，然后访问的是http://ip:8089

**Comment by unbendingWind** [comment]
抱歉，操作问题，2楼是对的，已经可以正常访问

**Comment by ly95** [comment]
Same issue.

es 5.4.1

"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /_sql/_explain</pre>\n</body>\n</html>\n"

**Comment by chenyg0911** [comment]
Maybe you should enable CORS on elasticsearch.yml and restart ES.

**Comment by ly95** [comment]
No affect result after enabled CORS.

**Comment by unbendingWind** [comment]
按照2楼说的看看，除了访问8080端口外，页面上面还要输入es的访问地址：http://ip:9200/

**Comment by chenzuoli** [comment]
![image](https://user-images.githubusercontent.com/28354442/47650850-764ea400-dbbc-11e8-9a14-92a642bd56e6.png)
已经改过右上角的es地址端口，但是search时出现Error occured! response is not avalible.
请问怎么办呢？

**Comment by shi-yuan** [comment]
这个地址能访问吗？
http://192.168.68.73:9200/_sql?sql=select * from report_es_receivables_20180323

**Comment by shi-yuan** [comment]
用的哪个版本？浏览器的请求能看看吗，后台日志，有吗？

**Comment by sdshw** [comment]
> 用的哪个版本？浏览器的请求能看看吗，后台日志，有吗？

打开elasticsearch的CORS, 问题解决
