### ISSUE TITLE
Getting 401 error if authentication is enabled Elasticsearch

### ISSUE THREAD

**Issue by has-star** [NLPchina/elasticsearch-sql#455]
I am connecting to ElasticSearch from ElasticSearch-SQL with authentication enabled.
These are my CORS setting in ElasticSearch
```
http.cors.enabled: true
http.cors.allow-credentials: true
http.cors.allow-origin: "/.*/"
http.cors.allow-headers: WWW-Authenticate,X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
```
In ElasticSearch-SQL page i am putting http://username:password@localhost:9200/ and getting this error

```
{  
   "error":{  
      "root_cause":[  
         {  
            "type":"security_exception",
            "reason":"missing authentication token for REST request [/_sql/_explain]",
            "header":{  
               "WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""
            }
         }
      ],
      "type":"security_exception",
      "reason":"missing authentication token for REST request [/_sql/_explain]",
      "header":{  
         "WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""
      }
   },
   "status":401
}
```
if tried from browser it is working fine using the below URL

http://username:password@localhost:9200/_sql?sql=select * from myindex limit 10

**Comment by shi-yuan** [comment]
have a look at [es-sql-site-standalone not working](https://github.com/NLPchina/elasticsearch-sql/issues/364)

**Comment by chenyg0911** [comment]
follow the issue #364 
use:
http://localhost:8080/?username=elastic&password=changeme&base_uri=encodedURI
I still can't connect to es correctly!
What's the problem?
use elasticsearch_head, the same manner:
http://localhost:9100/?auth_user=elastic&auth_password=changeme
working well on es head with CORS defineded.

**Comment by shi-yuan** [comment]
Did you use the latest？Request headers contains ‘Authorization’？

**Comment by chenyg0911** [comment]
what's u mean? es:5.4.1, sql-site I download it last month.

**Comment by chenyg0911** [comment]
![qq 20170721105505](https://user-images.githubusercontent.com/16010372/28447627-7da6887a-6e04-11e7-9fe8-c13dbf9200f5.png)

**Comment by chenyg0911** [comment]
anonymous? no auth on http head.

**Comment by chenyg0911** [comment]
Will re-download the lastest version to try.

**Comment by shi-yuan** [comment]
![image](https://user-images.githubusercontent.com/8057153/28450157-219a7fc8-6e18-11e7-9de4-07473d9cd834.png)

**Comment by chenyg0911** [comment]
update to  sql_site.It seam auth ok.
but still not working as normal.
should be add more cors in elasticsearch.yml?
my core definition:
#---------------------------------- http cors ---------------------------------
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: Authorization

![qq 20170721141408](https://user-images.githubusercontent.com/16010372/28451279-f30f7ed6-6e1e-11e7-9552-553f7cd646ea.png)

**Comment by chenyg0911** [comment]
不知道啥原因了。
![qq 20170721143037](https://user-images.githubusercontent.com/16010372/28451725-9a328f3a-6e21-11e7-8a18-32868f8048db.png)

**Comment by shi-yuan** [comment]
my config:
```yaml
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, Authorization"
```

**Comment by chenyg0911** [comment]
OK. updated the ES cors config, It work now. Thanks!
