### ISSUE TITLE
like语句的解析可以用match替换wildcard吗？

### ISSUE THREAD

**Issue by maskwang** [NLPchina/elasticsearch-sql#462]
语句： select * from xx where content like '%xx%'  数据量在2亿多
执行要80多秒。 
如果用match_phrase 只需要几百毫秒。
 所以我想问下的是，like的解析可以指定用match来解析去查询吗？

**Comment by shi-yuan** [comment]
```sql
select * from xx where content=matchPhrase('xx')
```

**Comment by maskwang** [comment]
thanks , it works for me!  O(∩_∩)O~
