### ISSUE TITLE
Use elasticsearch-sql for not local hosted ES

### ISSUE THREAD

**Issue by malsioufi** [NLPchina/elasticsearch-sql#463]
Thank you very much for the amazing plugin!
I want to use elasticsearch-sql to apply queries on an ES that is hosted on another host (not localhost) it is working fine right now but is there anyway to configure the frontend provided by you to use that host (to have the provided front-end running on the client machine not the server machine like we usually do with Kibana for example)

**Comment by shi-yuan** [comment]
you can edit the url:
![image](https://user-images.githubusercontent.com/8057153/28238205-541627a4-6981-11e7-89d5-94ecfe62e374.png)

Or, if it's possible, you can develop your own, then send http to server and render the response.

**Comment by shi-yuan** [comment]
you can try [chrome extension](https://github.com/shi-yuan/elasticsearch-sql-site-chrome)
