### ISSUE TITLE
如何使用elasticsearch-sql 去查询一个表内两个文档不相同？

### ISSUE THREAD

**Issue by token01** [NLPchina/elasticsearch-sql#465]
请问select * from table where clum1 <> clum2怎么查？

**Comment by chenyg0911** [comment]
用script

2017-07-13 11:05 GMT+08:00 token01 <notifications@github.com>:

**Comment by DimonHo** [comment]
能说的在详细一点吗？ 用script怎么个写法？
```
{
  "script": "ctx._source.keywords == ctx._source.keywordsCX"
}
```
这样写貌似是不行的。还请指教。。。

**Comment by chenyg0911** [comment]
类似：where script("doc['clum1'] == doc['clum2'] )
