### ISSUE TITLE
IS NULL or IS NOT NULL don't work

### ISSUE THREAD

**Issue by jheimbouch** [NLPchina/elasticsearch-sql#47]
When executing the simple query
```code:sql
select * from documents where xComment IS NULL
```
a QueryParsingException occurs from Elastic. *QueryParsingException[[documents] No text specified for text query*

The query:
```code:json
{
	"from": 0,
	"size": 200,
	"query": {
		"filtered": {
			"filter": {
				"bool": {
					"must": {
						"not": {
							"filter": {
								"query": {
									"match": {
										"xComment": {
											"query": null,
											"type": "phrase"
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
```
Should really be:
```code:json
{
  "query":{
    "constant_score": {
      "filter": {
        "missing": {
          "field": "xComment"
        }
      }
    }
  }
}
```

Also, the generated query does *not* make use of the "missing filter" or the "exists filter" from Elastic.
http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-missing-filter.html
http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-exists-filter.html

How can I assist in getting this fixed?

**Comment by ansjsun** [comment]
发自我的 iPhone

**Comment by jheimbouch** [comment]
@ansjsun, Your only comment was "Sent from my iPhone" - Did you mean to include something else?

**Comment by jheimbouch** [comment]
IS MISSING can be used in place of IS NULL
