### ISSUE TITLE
elasticsearch  sql 是否需要每个节点都安装？

### ISSUE THREAD

**Issue by jiaquanyu** [NLPchina/elasticsearch-sql#471]
es sql插件是否是需要集群内 每个节点都安装  还是ingest 节点就可以

**Comment by heyibo8888** [comment]
可以不安装，我觉得只要客户端包含elasticsearch sql 就可以了

**Comment by jiaquanyu** [comment]
@heyibo8888 是的 之前是curl http://hostname:port/_sql?sql= 这个语句解析的问题  有1个节点安装就可以了
