### ISSUE TITLE
Is dummy alias supported?

### ISSUE THREAD

**Issue by sivadas** [NLPchina/elasticsearch-sql#475]
Is 0 as alias_name supported?

Below SQL throwing Error 500 (null pointer exception)
select col_name_1, col_name_2, 0 as t from index_name;

**Comment by shi-yuan** [comment]
```sql
select col_name_1, col_name_2, script('t','0')  from index_name
```

**Comment by sivadas** [comment]
this doesn't work. It only returns col_name_1 and col_name_2 not t.

{
    "took": 5,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 35323,
        "max_score": 0,
        "hits": []
    },
    "aggregations": {
        "col_name_1": {
            "value": 4321.34454
        },
        "col_name_2": {
            "value": 1234.34454
        }
    }
}

**Comment by shi-yuan** [comment]
```sql
SELECT name,script('t','0') FROM test
```
```json
{
    "took": 6,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 1,
        "max_score": 1,
        "hits": [
            {
                "_index": "test",
                "_type": "test",
                "_id": "1",
                "_score": 1,
                "_source": {
                    "name": "test"
                },
                "fields": {
                    "t": [
                        0
                    ]
                }
            }
        ]
    }
}
```

**Comment by sivadas** [comment]
Thanks Yuan for helping out. I can see it now. But seems like it's only working with non-aggregation queries where "_source" attributes is expected not with "aggregations" attributes.

Ex: select col_1,col_2, script('t','0') from index_1 group by col_2, col_1 order by col_1

This don't have "fields" attributes in response.

**Comment by shi-yuan** [comment]
Yes !

**Comment by sivadas** [comment]
Thanks Yuan.  My first query was, can i use script('t','0') with aggregations? if yes, then how? Please give me a sample query.

**Comment by shi-yuan** [comment]
I think, you can't use script('t','0') with aggregations.
You can use :
```sql
select col_1,col_2 from index_1 group by col_2, col_1,script('t','0')
```
but it's not well !
