### ISSUE TITLE
Not able to query data which has space in column name

### ISSUE THREAD

**Issue by muthu1086** [NLPchina/elasticsearch-sql#48]
Not able to query data which has space in column name like

SELECT * FROM shanghairanking ORDER BY 'WORLD RANK' 

error it says  Error: {"error":"SqlParseException[unknow field name : 'WORLD RANK']","status":500}

SELECT * FROM shanghairanking    shows

Sample Results
World Rank |Institution*|Country /Region	|National Rank	|Total Score|Alumni|Award|HiCi|N&S|PUB|PCP
4|University of California-Berkeley|	|4|70.1|66.8|79.4|65.3|67.5|68.1|55.9

**Comment by muthu1086** [comment]
Hi Any pointers in this

**Comment by omershelef** [comment]
This bug have been fixed. your query should work now. Sorry for the long waiting.
