### ISSUE TITLE
time-zone on date_histogram

### ISSUE THREAD

**Issue by chenyg0911** [NLPchina/elasticsearch-sql#480]
es:5.5
SQL:SELECT count(*) FROM myindex
GROUP BY date_histogram(field='@Time','interval'='1d','time_zone'='+08:00')
Explain:

{
	"from": 0,
	"size": 0,
	"_source": {
		"includes": [
			"COUNT"
		],
		"excludes": []
	},
	"aggregations": {
		"date_histogram(field=@Time,interval=1d,time_zone=+08:00)": {
			"date_histogram": {
				"field": "@Time",
				"format": "yyyy-MM-dd HH:mm:ss",
				**"time_zone": "UTC",
				"interval": "1d",
				"offset": 0,**
				"order": {
					"_key": "asc"
				},
				"keyed": false,
				"min_doc_count": 0
			},
			"aggregations": {
				"COUNT(*)": {
					"value_count": {
						"field": "_index"
					}
				}
			}
		}
	}
}

**Comment by chenyg0911** [comment]
plugin要重装吗？

**Comment by shi-yuan** [comment]
需要用master分支，自己重新打包，然后重装
