### ISSUE TITLE
5.5.0的版本有问题

### ISSUE THREAD

**Issue by goodqinjin** [NLPchina/elasticsearch-sql#483]
安装直接报错，Error: 'elasticsearch' directory is missing in the plugin zip

**Comment by shi-yuan** [comment]
没问题的：
![1](https://user-images.githubusercontent.com/8057153/29102268-7a309358-7cea-11e7-858b-5eb56e490e05.png)

**Comment by chenyg0911** [comment]
正常安装，使用中。

2017-08-09 10:07 GMT+08:00 shiyuan <notifications@github.com>:
