### ISSUE TITLE
5.4.3 es-sql-site-standalone

### ISSUE THREAD

**Issue by goodqinjin** [NLPchina/elasticsearch-sql#484]
如何离线安装这个啊？服务器不能连接外网。

**Comment by chenyg0911** [comment]
这个就是下载解压，然后node node-server.js，OK了。

2017-08-09 12:14 GMT+08:00 goodqinjin <notifications@github.com>:

**Comment by goodqinjin** [comment]
@chenyg0911 
cd site-server
npm install express --save
node node-server.js 

我知道安装步骤，但是能否手动去安装不要运行npm&node命令？

**Comment by chenyg0911** [comment]
哦。npm是比较麻烦。你可以在联网的地方安装好，再全目录拷贝过去。

2017-08-09 13:09 GMT+08:00 goodqinjin <notifications@github.com>:

**Comment by goodqinjin** [comment]
@chenyg0911 我没有这样的环境去安装，你能帮忙安装下吗？谢谢

**Comment by chenyg0911** [comment]
找个能联网的地方的装啊。不能联网又怎么给你？

2017-08-09 13:46 GMT+08:00 goodqinjin <notifications@github.com>:

**Comment by shi-yuan** [comment]
也可以使用[Chrome插件](https://github.com/shi-yuan/elasticsearch-sql-site-chrome)
