### ISSUE TITLE
elasticsearch-sql解析sql生成dsl的部分怎么调用，望指教

### ISSUE THREAD

**Issue by vergilchiu** [NLPchina/elasticsearch-sql#489]
你好，
我们在修改es的hive handler，es自己写的解析hive的sql生成dsl的部分甚是简单，我们想自己解析sql生成dsl，发现dsl太过丰富难度太大，发现你这个解析sql生成dsl的语句还挺好用。刚才简单看了下你的代码，想求教下借助的你的jar解析sql生成dsl的部分怎么调用，望指教

**Comment by shi-yuan** [comment]
pom.xml:
```xml
<dependency>
        <groupId>org.nlpcn</groupId>
        <artifactId>elasticsearch-sql</artifactId>
        <version>X.X.X.X</version>
</dependency>
```
```java
new SearchDao(esClient.getClient()).explain(sql).explain().explain()
```

**Comment by xuziw** [comment]
@shi-yuan 您好
elasticsearch-sql-x.x.x.x.jar以及druid的r包在哪里下载了

**Comment by shi-yuan** [comment]
[elasticsearch-sql](https://mvnrepository.com/artifact/org.nlpcn/elasticsearch-sql)  & [druid](https://mvnrepository.com/artifact/com.alibaba/druid)

**Comment by wuchaooooo** [comment]
@shi-yuan 你好，我看maven仓库中，只有5.1.2.0版本。我在用的es是5.4版本，请问怎么将其引入我的java工程？

**Comment by ws2823147532** [comment]
自己编译一下 ，deploy到私有maven库，就能引了啊。我就是这样干的

**Comment by ws2823147532** [comment]
@wuchaooooo 自己编译一下 ，deploy到私有maven库或者install到本地仓库，就能引了啊。我就是这样干的

**Comment by wuchaooooo** [comment]
@ws2823147532 maven 编译的时候，需要我输入这个：GPG Passphrase: *，然后点回车，就报错了。

*gpg: WARNING: "--no-use-agent" is an obsolete option - it has no effect
gpg: directory '/Users/wuchaooooo/.gnupg' created
gpg: keybox '/Users/wuchaooooo/.gnupg/pubring.kbx' created
gpg: no default secret key: No secret key
gpg: signing failed: No secret key

**Comment by ws2823147532** [comment]
在 pom.xml里面有一个  GPG 的插件  注释掉就可以 @wuchaooooo

**Comment by wuchaooooo** [comment]
@ws2823147532 好的，谢谢！！

**Comment by seniorcandy** [comment]
这个有办法在不适用client的情况下，得到sql转dsl的结果吗？我只想要当做一个工具类来使用，不想依赖其他东西
`new SearchDao(esClient.getClient()).explain(sql).explain().explain()`

**Comment by ansjsun** [comment]
new一个空的client 就可以




在2019年11月22日 18:13，candy 写道：

这个有办法在不适用client的情况下，得到sql转dsl的结果吗？我只想要当做一个工具类来使用，不想依赖其他东西
new SearchDao(esClient.getClient()).explain(sql).explain().explain()

**Comment by shi-yuan** [comment]
![image](https://user-images.githubusercontent.com/8057153/69911445-8dfafa80-1456-11ea-9288-d53b82501870.png)，mave 仓库一直没有更新了哈
