### ISSUE TITLE
essql-site-standalone点击search按钮报错

### ISSUE THREAD

**Issue by goodqinjin** [NLPchina/elasticsearch-sql#492]
` Error: Error occured! response is not avalible.`

我的ES版本是5.4.3，使用node 运行js起来后能访问，但点击search按钮就报错，这个报错是什么原因呢？

**Comment by shi-yuan** [comment]
请问es和node有错误日志吗？浏览器的console里呢？能都提供吗？

**Comment by goodqinjin** [comment]
@shi-yuan 是elasticsearch.yml中没有配置
http.cors.enabled: true
http.cors.allow-origin: "*"
