### ISSUE TITLE
SELECT name AS n from table AS失效问题 

### ISSUE THREAD

**Issue by hongxingwz** [NLPchina/elasticsearch-sql#495]
Elasticsearch-sql version:2.3.5.0
当执行
`select name  as n from atlas`
时返回的字段名称是name，而不是n，也就是说as失效了
![image](https://user-images.githubusercontent.com/20805867/29512846-09d8cb56-8696-11e7-876d-7e1c023b8ba7.png)

**Comment by shi-yuan** [comment]
use `SELECT script('n', 'doc["name"].value') from atlas` instead
or
use [2.4.6.0](https://github.com/NLPchina/elasticsearch-sql/releases/tag/2.4.6.0)

**Comment by hongxingwz** [comment]
Thank you. I follow you advise.But the above statement can't execute. I have got followed errors
`{"error":{"root_cause":[{"type":"s_q_l_feature_not_supported_exception","reason":"Unsupported query: script('n', 'doc[\"name\"].value')"}],"type":"s_q_l_feature_not_supported_exception","reason":"Unsupported query: script('n', 'doc[\"name\"].value')"},"status":500}`

**Comment by hongxingwz** [comment]
Thanks! Our team have solved that problem by following your advise
