### ISSUE TITLE
 Error: Error occured! response is not avalible.

### ISSUE THREAD

**Issue by skvsree** [NLPchina/elasticsearch-sql#496]
Receiving error while trying to a basic select query.  ES version 5.0.1, Windows environment.  Where can I find the logs for this.  Below is the error
![image](https://user-images.githubusercontent.com/1096834/29516147-e10f00b8-868c-11e7-9e48-ecf3a65a951c.png)

**Comment by rajivchodisetti** [comment]
Am also facing the same issue

**Comment by rajivchodisetti** [comment]
Am using 5.5.1 version

**Comment by shi-yuan** [comment]
Config
```yml
http.cors.enabled: true
http.cors.allow-origin: "*"
```
or not ?

![image](https://user-images.githubusercontent.com/8057153/29569935-96f0b5fc-8787-11e7-9351-b052142ebf62.png)
no problem

**Comment by HuJake** [comment]
Hi I'm also have this problem,Using Elasticsearch Port 9200 and SHOW " Error: Error occured! response is not avalible."

Sorry Where is Config?
add down this commend?
```
http.cors.enabled: true
http.cors.allow-origin: "*"
```

**Comment by chenyg0911** [comment]
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length,
Authorization"


2017-08-23 10:55 GMT+08:00 Jake Hu <notifications@github.com>:

**Comment by HuJake** [comment]
Many Thanks.
```
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length,
Authorization"
```
This **http.cors.enabled: true**  adding where PATH or file?

**Comment by chenyg0911** [comment]
elasticsearch.yaml

2017-08-23 11:03 GMT+08:00 Jake Hu <notifications@github.com>:

**Comment by HuJake** [comment]
Hi Chenyg0911, Many thanks a lot.
Modify elasticsearch.yaml and add can using query search.

Nice!

**Comment by skvsree** [comment]
Had to change extension from elasticsearch.yml to elasticsearch.yaml, not sure if the issue is due to this.  Can close the issue
