### ISSUE TITLE
mvn package 后的 jar包如何安装?

### ISSUE THREAD

**Issue by jnuc093** [NLPchina/elasticsearch-sql#498]
这个zip文件我下载不了，我只能 mvn package后 plugin install 报格式不对，清问应该如何处理。
➜  target git:(5.4.0.0) ls
classes                               generated-sources                     surefire-reports
druid.jar                             guava.jar                             test-classes
elasticsearch-sql-5.4.0.0-sources.jar maven-archiver
elasticsearch-sql-5.4.0.0.jar         plugin-descriptor.properties

➜  elasticsearch-5.4.0 cd bin
➜  bin ./elasticsearch-plugin install http://127.0.0.1/\~qk/1_nanri/elk/sql/elasticsearch-sql-5.4.0.0.jar
-> Downloading http://127.0.0.1/~qk/1_nanri/elk/sql/elasticsearch-sql-5.4.0.0.jar
[=================================================] 100%
ERROR: `elasticsearch` directory is missing in the plugin zip
➜  bin ./elasticsearch-plugin install http://127.0.0.1/\~qk/1_nanri/elk/sql/elasticsearch-sql-5.4.0.0.jar.zip
-> Downloading http://127.0.0.1/~qk/1_nanri/elk/sql/elasticsearch-sql-5.4.0.0.jar.zip
[=================================================] 100%
ERROR: `elasticsearch` directory is missing in the plugin zip

**Comment by shi-yuan** [comment]
直接将这几个文件拷贝过去就行：
![image](https://user-images.githubusercontent.com/8057153/29567246-29862540-877f-11e7-8788-b1858671fa63.png)

**Comment by shi-yuan** [comment]
如果是zip，目录结构：
![image](https://user-images.githubusercontent.com/8057153/29567441-c977e21e-877f-11e7-91e4-52d86e4192f8.png)

**Comment by jnuc093** [comment]
https://github.com/NLPchina/elasticsearch-sql/releases/download/5.4.0.0/es-sql-site-standalone.zip

这个链接我下载不下来

**Comment by shi-yuan** [comment]
下载不了就本地打包吧，然后把上面截图的文件放到指定位置就行了

**Comment by jnuc093** [comment]
好的谢谢。
