### ISSUE TITLE
Aliases Problem：加上别名以后，为什么结果会有区别？

### ISSUE THREAD

**Issue by guoyang1996** [NLPchina/elasticsearch-sql#499]
Why "select user_id from menu where user_id <> ‘104000’" and "select menu1.user_id from menu as menu1 where menu1.user_id <> '104000'" has the different result?
the former has the right result but the latter returns all.

为什么加上别名以后，结果会有区别，我用前面那条语句，能得到正确的结果，用后面这条语句，却返回了所有的记录？ 

并且如果写成select user_id as id from menu where user_id <> '104000' 时检索结果中既有id，且所有的其它的属性都出来了，：（

**Comment by shi-yuan** [comment]
```sql
select user_id as id from menu where user_id <> '104000'
```
这个用的是[Script Fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-script-fields.html)
