### ISSUE TITLE
字段如何加权重？

### ISSUE THREAD

**Issue by 344399160** [NLPchina/elasticsearch-sql#500]
如题

**Comment by shi-yuan** [comment]
可以用[Query String Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html)试试：
```sql
SELECT address FROM bank where q=query('address:"880 Holmes Lane"^10')
```

**Comment by shi-yuan** [comment]
[How to add weight to the field search](https://github.com/NLPchina/elasticsearch-sql/issues/554)
