### ISSUE TITLE
nested类型如果嵌套有三层或者以上呢，如何使用？

### ISSUE THREAD

**Issue by sumpan** [NLPchina/elasticsearch-sql#508]
SELECT * FROM myindex where nested(binaryAnnotations.endpoint.serviceName="coupon")

报错 Error: {"error":{"root_cause":[{"type":"sql_parse_exception","reason":"unsupported nested condition"}],"type":"sql_parse_exception","reason":"unsupported nested condition"},"status":500}

**Comment by shi-yuan** [comment]
```sql
SELECT * FROM myindex where nested(binaryAnnotations.endpoint.serviceName)="coupon"
```
Have a look at [NestedTypes queries](https://github.com/NLPchina/elasticsearch-sql/wiki/NestedTypes-queries)
