### ISSUE TITLE
Problem in CSV result - Rest API ?

### ISSUE THREAD

**Issue by githubmui** [NLPchina/elasticsearch-sql#515]
ES 5.5.2: 
"flat=true" in URL results in an error 400 (bad request)
Same with "separator=;" within URL.
e.g. http://xxxx:9200/_sql?flat=true&separator=;&format=csv&sql=select field from index
Is this feature still supported or is it maybe a bug?

**Comment by shi-yuan** [comment]
`http://xxxx:9200/_sql?flat=true&separator=%3B&format=csv&sql=select field from index`

**Comment by yangjiajun2014** [comment]
ES 5.6.2 still has this bug?
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "request [/_sql] contains unrecognized parameter: [separator]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "request [/_sql] contains unrecognized parameter: [separator]"
  },
  "status": 400
}

**Comment by shi-yuan** [comment]
use elasticsearch-sql version 5.6.2.1

**Comment by yangjiajun2014** [comment]
But I can not find this version on the download site.

**Comment by shi-yuan** [comment]
yeah, you should build by yourself.
:point_right: [elasticsearch-sql-5.6.2.1.zip](https://github.com/NLPchina/elasticsearch-sql/files/1610956/elasticsearch-sql-5.6.2.1.zip)
