### ISSUE TITLE
Order By nested fields doesn't work

### ISSUE THREAD

**Issue by KristapsF** [NLPchina/elasticsearch-sql#516]
SQL ORDER BY nested(person.name) for example doesn't work.
Version 2.4.5

**Comment by shi-yuan** [comment]
Support [Order by Nested Fields](https://github.com/NLPchina/elasticsearch-sql/issues/387)
![image](https://user-images.githubusercontent.com/8057153/31175030-5f35d41e-a940-11e7-8117-9838925d167c.png)
