### ISSUE TITLE
Date column

### ISSUE THREAD

**Issue by norberto-enomoto** [NLPchina/elasticsearch-sql#52]
I have date column. How can I write a SQL statement based on that column in where clause?

Example: SELECT count(*) FROM logstash-2015.03.18 where @datetime between '2015-03-18' and '2015-03-18' 

@datetime format: 2015-03-18T12:17:20.000Z

**Comment by yelouati** [comment]
did you find a solution?

**Comment by omershelef** [comment]
This query should work... have you tried running it and got an error?
we actually have test which pass that running this query:
```
SELECT insert_time FROM %s/online WHERE insert_time BETWEEN '2014-08-18' AND '2014-08-21' LIMIT 3
```

**Comment by kyunam** [comment]
I tried it but it didn't work.

**Comment by KangYongKyun** [comment]
You need to follow date format 

```
Exampe : SELECT count(*) FROM logstash-2015.03.18 where @datetime between '2015-03-18T00:00:00+00' and '2015-03-18T23:59:59+00'
```

**Comment by KangYongKyun** [comment]
If it is possible to use format in sql query, query is converted to like this. 

```  
{
    "range" : {
        "@datetime" : {
            "gte": "2015-03-18",
            "lte": "2015-03-18",
            "format": "dd/MM/yyyy"
        }
    }
}
```

**Comment by kyunam** [comment]
Thank you Sir! All your replies worked.
Also, one correction - the one I said it didn't work (BETWEEN '2014-08-18' AND '2014-08-21'), it works.

As references, the followings worked.
1.
SELECT * FROM bulk_points/point where CREATED_DATE between '2015-03-18' and '2016-03-18'

2.
SELECT * FROM bulk_points/point where CREATED_DATE between '2015-03-18T00:00:00+00' and '2016-03-18T23:59:59+00'

3.
GET bulk_points/point/_search
{
  "from": 0,
  "size": 3,
  "query": {
    "filtered": {
      "filter": {
        "bool": {
          "must": {
            "range": {
              "CREATED_DATE": {
                "gte": "2015-03-18",
                "lte": "2016-03-18",
                "format": "yyyy-MM-dd"
              }
            }
          }
        }
      }
    }
  }
}

4.
GET bulk_points/point/_search
{
	"from": 0,
	"size": 3,
	"query": {
		"filtered": {
			"filter": {
				"bool": {
					"must": {
						"range": {
							"CREATED_DATE": {
								"from": "2015-03-18",
								"to": "2016-03-18",
								"include_lower": true,
								"include_upper": true
							}
						}
					}
				}
			}
		}
	}
}

5.
{
  "from": 0,
  "size": 3,
  "query": {
    "filtered": {
      "filter": {
        "bool": {
          "must": {
            "range": {
              "CREATED_DATE": {
                "gte": "2015-03-18 00:00:00",
                "lte": "2016-03-18 00:00:00",
                "format": "yyyy-MM-dd HH:mm:ss"
              }
            }
          }
        }
      }
    }
  }
}

**Comment by KangYongKyun** [comment]
If date field(example:@timestamp) mapping is like below 

```
@timestamp: {
format: dateOptionalTime
type: date
}
```

related documents
- https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html
- http://joda-time.sourceforge.net/api-release/org/joda/time/format/ISODateTimeFormat.html#dateOptionalTimeParser()

dateOptionalTime format 
It accepts formats described by the following syntax:

 date-opt-time     = date-element ['T' [time-element] [offset]]
 date-element      = std-date-element | ord-date-element | week-date-element
 std-date-element  = yyyy ['-' MM ['-' dd]]
 ord-date-element  = yyyy ['-' DDD]
 week-date-element = xxxx '-W' ww ['-' e]
 time-element      = HH [minute-element] | [fraction]
 minute-element    = ':' mm [second-element] | [fraction]
 second-element    = ':' ss [fraction]
 fraction          = ('.' | ',') digit+

**Comment by kyunam** [comment]
thanks again!
