### ISSUE TITLE
求助时间范围内的查询问题

### ISSUE THREAD

**Issue by xinqiyang** [NLPchina/elasticsearch-sql#535]
where 里面， 有一个 date 类型的createTime 现在需要查询时间范围，比如几天以内的，使用where时间范围，结果没有一个能跑的，求助，大家都咋个用时间的查询？ 

mapping 里面设定   "createTime": {
          "type": "date"
        }

where  createTime between '2016-05-11' and '2016-05-12'

where date_format(createTime,'yyyy-MM-dd')  >= '2016-05-11' and date_format(createTime,'yyyy-MM-dd') < '2016-05-12'

where  createTime>= '2016-05-01T00:00+08:00' and createTime < '2016-05-10T00:00+08:00'

where  createTime>= '2016-05-01' and createTime < '2016-05-10'

这样的查询，大家咋个实现的？

**Comment by shi-yuan** [comment]
my case:
![case](https://user-images.githubusercontent.com/8057153/31921302-47373568-b8a1-11e7-9629-47c3277d41d1.png)

**Comment by xinqiyang** [comment]
@shi-yuan  太感谢了， 把时间格式修改了之后，带上时区了之后，就可以了。 

where createTime>= "2017-09-01T00:00:00+00:00" and createTime < "2017-09-02T00:00:00+00:00"
