### ISSUE TITLE
Support for Elasticsearch 1.5

### ISSUE THREAD

**Issue by djui** [NLPchina/elasticsearch-sql#54]
I am not sure if that's currently an issue, but when installing the plugin into an Elasticsearch 1.5 cluster, I can't see anything happening when navigating to the plugin url.

**Comment by haoyixin** [comment]
me, too

**Comment by MaheshSankaran** [comment]
am also seeing this issue.Kindly solve it.

**Comment by omershelef** [comment]
I opened a feature issue #62.
