### ISSUE TITLE
case when 不能使用+-*/

### ISSUE THREAD

**Issue by goodqinjin** [NLPchina/elasticsearch-sql#540]
select (case when a = 0 then b * 0.01 else b end) as f1 from index

a和b都是字段名，SQL执行会报错， 但是将b * 0.01改成b就没有问题

**Comment by shi-yuan** [comment]
+-*/，可以试试[Script Fields](https://github.com/NLPchina/elasticsearch-sql/wiki/Script-Fields)
```sql
select script("f1","doc['a'].value==0?doc['b'].value*0.01:doc['b'].value") from index
```

**Comment by goodqinjin** [comment]
我试过这个方法， 但是有个语法报错：select script('field', '**painless**', 'doc[\'a\'].value') from index
指定painless 或者 groovy就会报错

**Comment by goodqinjin** [comment]
@shi-yuan

**Comment by goodqinjin** [comment]
我看了下5.4.3分支下的代码， 在DefaultQueryAction.java下有个handleScriptField方法， 有个判断
else if(params.size() == 3) {
   request.addScriptField(......, params:null)
}
这里params不能为null， 需要改成Collections.emptyMap()
