### ISSUE TITLE
es ElasticSearchResultSetMetaDataBase getColumns() return empty list 

### ISSUE THREAD

**Issue by xbkaishui** [NLPchina/elasticsearch-sql#541]
es ElasticSearchResultSetMetaDataBase getColumns() return empty list  

sql as 
select * from index_a limit 10

**Comment by xbkaishui** [comment]
ResultSetMetaData metaData = resultSet.getMetaData();
            int columnCnt = metaData.getColumnCount();
            for (int i = 0; i < columnCnt; i++) {
                columnNames.add(metaData.getColumnName(i + 1));
            }

**Comment by shi-yuan** [comment]
Please see [fix issues 541](https://github.com/NLPchina/elasticsearch-sql/commit/09ea2f598b375fa57f857c8f4f75a9508f2a8d59)

**Comment by when520** [comment]
@shi-yuan  your share the url can't solve the problem

**Comment by shi-yuan** [comment]
[ResultSetMetaData.getColumnCount() get the value is zero??? ](https://github.com/NLPchina/elasticsearch-sql/issues/633)
