### ISSUE TITLE
How can i implement elasticsearch-sql in Node.js ?

### ISSUE THREAD

**Issue by KalaiselvanMahendran** [NLPchina/elasticsearch-sql#542]
Hi @allwefantasy @ansjsun , Is there any support or documentation to implement elasticsearch-sql in Node.js? or Integrating with Elasticsearch official [npm module](https://www.npmjs.com/package/elasticsearch) for Nodejs?

**Comment by shi-yuan** [comment]
```nodejs
require('request').post('http://localhost:9200/_sql', {body: "select * from cars"}, function (error, response, body) {
    console.log(body);
});

```
