### ISSUE TITLE
如何在site server 中添加认证信息

### ISSUE THREAD

**Issue by hjxhjh** [NLPchina/elasticsearch-sql#543]
如何在site server 中添加认证信息

**Comment by shi-yuan** [comment]
have a look at [es-sql-site-standalone not working](https://github.com/NLPchina/elasticsearch-sql/issues/364)

**Comment by hjxhjh** [comment]
it works with url parameter. Can we support settings in the site_configuration.json?

**Comment by shi-yuan** [comment]
[Maybe, it's not a good idea](https://github.com/NLPchina/elasticsearch-sql/commit/86f64f2efa3cd3edd8d18d7151f0fe5c47065a1f)
