### ISSUE TITLE
execute sql err

### ISSUE THREAD

**Issue by wangping886** [NLPchina/elasticsearch-sql#547]
i run sql=select * from admin* where uid like '%angpin%' in your web_console it returns datas;
but when i  browser   /_sql?sql=select * from admin* where uid like '%angpin%' it will be error;
and when i use in server_code sql=select * from admin* where uid = 'wangping'. i must encode it that won't error . i wonder what cause this  and what should i do？

**Comment by wangping886** [comment]
maybe i should use _sql by POST . that will be ok

**Comment by shi-yuan** [comment]
http://localhost:9200/_sql?sql=select * from admin where uid like '%25angpin%25'

**Comment by wangping886** [comment]
i use http://localhost:9200/_sql by POST that will be ok
