### ISSUE TITLE
"distinct" keyword not working 

### ISSUE THREAD

**Issue by bsreekanth** [NLPchina/elasticsearch-sql#55]
hi
 we are trying to user distinct with selecting multiple columns . But the result end up in showing same data in multiple rows .

we are trying some thing like 
select  count(distinct HC1_LEVEL_05_CD,HC1_LEVEL_05_DESC,HC2_LEVEL_04_CD,HC2_LEVEL_04_DESC,HC3_LEVEL_03_CD,HC3_LEVEL_03_DESC )
from vwsearchview where HC1_LEVEL_03_CD = 'P0LI8' 

even we tried with group by 

select  count(*)
from vwsearchview where HC1_LEVEL_03_CD = 'P0LI8' group by HC1_LEVEL_05_CD,HC1_LEVEL_05_DESC,HC2_LEVEL_04_CD,
HC2_LEVEL_04_DESC,HC3_LEVEL_03_CD,HC3_LEVEL_03_DESC 

out intention is to get count of distinct columns .

**Comment by omershelef** [comment]
What about using one "count distinct" per column. for example:
```
SELECT COUNT(DISTINCT column1), COUNT(DISTINCT column2) FROM myindex
```
