### ISSUE TITLE
when i traverse resultSet there is an error(5.5.0.1)

### ISSUE THREAD

**Issue by zhangwenhao** [NLPchina/elasticsearch-sql#551]
when i debug the program ,there is an error , is i did something wrong with my program? can you give me a hand?
my verion：elasticsearch-sql is 5.5.0.1 and elasticsearch is 5.5.0
![1510814119 1](https://user-images.githubusercontent.com/29791129/32877385-400d0824-cadc-11e7-9982-d6a59be3b65f.jpg)
![1510814155 1](https://user-images.githubusercontent.com/29791129/32877386-41da4748-cadc-11e7-8c17-b51f30322ff4.jpg)
![1510814221 1](https://user-images.githubusercontent.com/29791129/32877387-42681c62-cadc-11e7-8fa4-a476a147fb65.jpg)

**Comment by shi-yuan** [comment]
Yeah, you may have a look at [ElasticSearchResultSetMetaDataBase](https://github.com/NLPchina/elasticsearch-sql/blob/master/src/main/java/com/alibaba/druid/pool/ElasticSearchResultSetMetaDataBase.java)
