### ISSUE TITLE
Wish elasticsearch-sql-5.x to support chrome extension

### ISSUE THREAD

**Issue by huangsusu** [NLPchina/elasticsearch-sql#552]
It is known that es 5.x doesn't support _site plugins anymore. Instead,  we can run es-sql alone using npm. But it is really complicated to install the running environment,.
        So , would you brilliant guys like to make it as a chrome extension just like elasticsearch-head ? That will be awsome. 
       Many thanks...

**Comment by shi-yuan** [comment]
[elasticsearch-sql-site-chrome](https://github.com/shi-yuan/elasticsearch-sql-site-chrome)

**Comment by huangsusu** [comment]
Really appreciate your work ！！ !
