### ISSUE TITLE
elasticsearch-sql for elasticsearch 6.0.0

### ISSUE THREAD

**Issue by genial-media** [NLPchina/elasticsearch-sql#553]
Is there already a release date for the support of Elasticsearch 6.0.0?

**Comment by betarelease** [comment]
update on this would be great

**Comment by reportico-web** [comment]
HI I use this plugin a lot, and we just upgraded to version 6.0.0 .. any chance Elastic 6.0.0 can be supported?

**Comment by shi-yuan** [comment]
[commit for 6.0.0 - compiling but not working, most tests are broken](https://github.com/NLPchina/elasticsearch-sql/commit/268725bd896d11253e639c995b1723f1a225e2fa)

**Comment by reportico-web** [comment]
Very grateful you are looking at this :-) ... I hope you find a fix ...

**Comment by shi-yuan** [comment]
[elasticsearch 6.0.0 support](https://github.com/NLPchina/elasticsearch-sql/releases/tag/6.0.0.0)
