### ISSUE TITLE
How to add weight to the field search

### ISSUE THREAD

**Issue by xiangHannibal** [NLPchina/elasticsearch-sql#554]
How to add weight to the field search
like match().boost

**Comment by shi-yuan** [comment]
可以试试
```sql
SELECT address FROM bank where q=query('address:"880 Holmes Lane"^10')
```

**Comment by shi-yuan** [comment]
```sql
select address from bank where address= matchPhrase('880 Holmes Lane', 10)
```

**Comment by xiangHannibal** [comment]
This score is a bit wrong

select * from test66 where name.mix = matchPhrase('马铃薯', 1.0) or common_name.mix = matchPhrase('马铃薯', 0.1)

name = {total=2, rows=[{name=很好, time=2017-12-03 16:23:05, common_name=马铃薯}, {name=马铃薯, time=2017-12-03 16:22:31, common_name=ces}]}

**Comment by xiangHannibal** [comment]
searchResponse = {"took":38,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":2,"max_score":0.0,"hits":[{"_index":"test66","_type":"test66","_id":"5bf4b0e5-87d5-40a1-bc6c-ba5128413dba","_score":0.0,"_source":{"name":"很好","time":"2017-12-03 16:23:05","common_name":"马铃薯"}},{"_index":"test66","_type":"test66","_id":"6752a9d9-f7a7-441e-acda-ccef59adbaa9","_score":0.0,"_source":{"name":"马铃薯","time":"2017-12-03 16:22:31","common_name":"ces"}}]}}

评分咋都是0 哦

**Comment by xiangHannibal** [comment]
select * from test66 where name.mix = matchQuery('马铃薯', 1.0) or common_name.mix = matchQuery('马铃薯', 0.1)

**Comment by xiangHannibal** [comment]
哦 要加上order by _score desc才计分
select * from test66 where name.mix = matchQuery('马铃薯', 1.0) or common_name.mix = matchQuery('马铃薯', 0.1) order by _score desc
