### ISSUE TITLE
es 5.1.1 install es-sql-site failed

### ISSUE THREAD

**Issue by y1170328179s** [NLPchina/elasticsearch-sql#558]
es 5.1.1 install es-sql-site failed， please help me，thank you for all
![1](https://user-images.githubusercontent.com/7701684/33475511-a939001c-d6b9-11e7-9e03-302bf7ac1429.png)

**Comment by shi-yuan** [comment]
![image](https://user-images.githubusercontent.com/8057153/33516443-cc747b20-d7ad-11e7-8f57-b11d4696b9cc.png)
