### ISSUE TITLE
Fix all broken tests.

### ISSUE THREAD

**Issue by omershelef** [NLPchina/elasticsearch-sql#56]
@jheimbouch The tests is broken after your last commits. Please you make sure that all tests are running before drafting a new Release.

**Comment by jheimbouch** [comment]
The tests all passed locally before I committed the code. A screenshot can be seen here: 
![elasticsearch-sql_ _bash_ _179x52](https://cloud.githubusercontent.com/assets/4997688/7734745/dac09546-fefd-11e4-8ec5-968954cbf0b4.png)


@omershelef Can you help me determine why this fails when running against Travis CI ?
