### ISSUE TITLE
Do you support query nested?

### ISSUE THREAD

**Issue by xumingbei** [NLPchina/elasticsearch-sql#560]

**Comment by shi-yuan** [comment]
[NestedTypes queries](https://github.com/NLPchina/elasticsearch-sql/wiki/NestedTypes-queries)

**Comment by xumingbei** [comment]
Thanks

**Comment by wanghu198343** [comment]
@xumingbei 您好！用中文提问可以么？我用的是java api导入数据到ES5.6.3，请问如何在导入的时候，指定字段的类型？
我有一个字段，ES默认的类型是text，但是该字段需要在聚合时使用，text类型会被分词，我想在导入数据的时候，指定字段类型为keyword类型，不知道在哪里设置。
谢谢指教！！

**Comment by xumingbei** [comment]
@wanghu198343 
您好，mapping映射，在创建索引的时候进行mapping映射操作即可。
网址为：https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html

**Comment by xumingbei** [comment]
@wanghu198343  
http://www.cnblogs.com/Creator/p/3722408.html

**Comment by wanghu198343** [comment]
@xumingbei 谢谢您的回复，我研究一下在java api中，怎样在创建索引的时候映射类型。
