### ISSUE TITLE
Getting Class Cast Exception error

### ISSUE THREAD

**Issue by amitbsconcept** [NLPchina/elasticsearch-sql#562]
`SELECT sum(case when is_published = 1 then 1 else 0 END) as total_published, sum(case when is_published = 0 then 1 else 0 END) as total_unpublished from articles`

When i run through the above query,  it gives me class cast exception error
**Cannot cast java.lang.Boolean to java.lang.Integer**

`is_published` is of the type BOOLEAN.

How can i accomplish the output for the same?

**Comment by shi-yuan** [comment]
```sql
SELECT sum(script("published","if (doc['is_published'].value) {1} else {0}")) as total_published, sum(script("unpublished","if (doc['is_published'].value) {0} else {1}")) as total_unpublished from articles
```

**Comment by amitbsconcept** [comment]
It worked like a charm. Cool thanx.
