### ISSUE TITLE
elasticsearch集群环境下的安装elasticsearch-sql

### ISSUE THREAD

**Issue by licz009** [NLPchina/elasticsearch-sql#569]
我在两台服务器上装了4个elasticsearch节点，每台服务器2个els , 
1、我是要在每个node上都安装elasearch-sql和site_server吗?
2、一台服务器上装了2个节点（9200，9201），启动的site_server连接的是哪个，怎么建立的关联关系？

**Comment by shi-yuan** [comment]
site_server只需要放在一处就行，访问的时候，填写es的访问url：

**Comment by licz009** [comment]
感谢您的及时回复，我现在的情况是运行http://x.x.x.x:9200/_sql?select...能正确出来结果，但是在site_server返回的是“Response is not avalible”，site_server的es地址配置是正确的（http://x.x.x.x:9200/）,请问node node_site.js输出日志在哪里？ 我用的es及es_sql用的都是5.6.4

**Comment by ansjsun** [comment]
是不是es没配置跨域支持。。


#开启跨域访问支持，默认为false  
  
http.cors.enabled: true  
  
#跨域访问允许的域名地址，(允许所有域名)以上使用正则  
  
http.cors.allow-origin: /.*/

**Comment by licz009** [comment]
非常感谢，ok了；
