### ISSUE TITLE
Is there a possibility to check missing / not missing in nested field?

### ISSUE THREAD

**Issue by amitbsconcept** [NLPchina/elasticsearch-sql#570]
I tried applying the missing field value in nested field. 

GET _sql?sql=SELECT * FROM articles WHERE classifications.classification_id is missing order by created_on desc

now when i issued this query, it did return me results .. but then i cross checked - it was not filtering data / records.. it was rather throwing in all the records. Is there a possibility to check if the missing / not missing works for the nested fields? 
(Please if there is a way, do share the possibility for checking in missing and not missing)

**Comment by shi-yuan** [comment]
```sql
SELECT * FROM articles WHERE nested(classifications.classification_id) is missing order by created_on desc
```

**Comment by amitbsconcept** [comment]
Well i tried the same - but it dose not return any value
Below is the result for the same
```
{
  "took": 3,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}
```

But when i give in the below query

`SELECT * FROM articles WHERE nested(classifications.classification_id) is not missing order by created_on desc
`
I get proper output... i get in the expected result.

**Comment by shi-yuan** [comment]
No problem!
![image](https://user-images.githubusercontent.com/8057153/34648249-eb7a631e-f3d1-11e7-8e14-0c0238a5ede4.png)
![image](https://user-images.githubusercontent.com/8057153/34648254-f8a0eacc-f3d1-11e7-8554-61cbf8973aa4.png)
![image](https://user-images.githubusercontent.com/8057153/34648258-ffee8ece-f3d1-11e7-8ef6-c319a0f9bbe7.png)

**Comment by shi-yuan** [comment]
[nested类型字段不存在的情况下，用elasticsearch-sql无法查询到](https://github.com/NLPchina/elasticsearch-sql/issues/628)
