### ISSUE TITLE
sql重命名报错

### ISSUE THREAD

**Issue by qq494679975** [NLPchina/elasticsearch-sql#574]
SELECT    
adminTeamCode  AS team ,
count(*) AS result1   
FROM 
  health_edu_article_patient_test3	
group by 
adminTeamCode

=====================error===============
Error:{"error":{"root_cause":[{"type":"script_exception","reason":"scripts of type [inline], operation [search] and lang [groovy] are disabled"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"health_edu_article_patient_test3","node":"ew3BZFG1SIC80NHzqTJnCg","reason":{"type":"script_exception","reason":"scripts of type [inline], operation [search] and lang [groovy] are disabled"}}]},"status":500}

**Comment by shi-yuan** [comment]
elasticsearch.yml:

**Comment by qq494679975** [comment]
3QQQQQQQQQQQQQQQQQQQQQQQQQQQ,完美解决

**Comment by qq494679975** [comment]
对了 2.4版本的ES  
delete from health_edu_article_patient_test3 where doctorCode="xh1D2017031502222" 执行delete报错 
我有装好delete-by-query插件  也重启了 但是还是报错
java.lang.UnsupportedOperationException: currently not support delete on elastic 2.x

**Comment by shi-yuan** [comment]
应该是不支持删除操作的

**Comment by shi-yuan** [comment]
最新版本支持的[347](https://github.com/NLPchina/elasticsearch-sql/issues/347)
