### ISSUE TITLE
If there's a way to use scroll_id in sql?

### ISSUE THREAD

**Issue by imqishi** [NLPchina/elasticsearch-sql#575]
Well, I read the controller.js and find that it seems the first fetch we got a scroll_id and following data is got by raw curl request... I just want to check if there's a method to use sql when fetch following data, or I will follow your code

**Comment by shi-yuan** [comment]
Sorry, not yet !

**Comment by imqishi** [comment]
OK~Thank you~

**Comment by WhisperLoli** [comment]
@shi-yuan 程序中使用SQL查询，结果集中如何拿到scroll id呢，我看了一下返回字段只有_source中的字段和 _id，没有返回_scroll_id字段啊
![image](https://user-images.githubusercontent.com/31977300/60939576-d6c8e000-a30a-11e9-8550-17ebc7d12d03.png)

**Comment by WhisperLoli** [comment]
![image](https://user-images.githubusercontent.com/31977300/60952610-28369680-a32e-11e9-8a93-0c32d0810d65.png)

**Comment by shi-yuan** [comment]
用jdbc的话，直接：
```sql
select /*! USE_SCROLL*/ gender,lastname,age,_scroll_id from elasticsearch-sql_test_index_account where lastname='Heath'
```

**Comment by WhisperLoli** [comment]
用/*! USE_SCROLL*/的话没有指定scroll id存活时间，而且如果要获取下一批次呢？也没有提供上一批次的scroll id

**Comment by ssjjcao** [comment]
/! USE_SCROLL/应该是有默认值的。以及，如果没有返回_scroll_id字段，应该是版本不对，需要6.7.2.0+

**Comment by ssjjcao** [comment]
@WhisperLoli  hello
如果想在结果中拿到_scroll_id字段，需要在select语句中明确写出_scroll_id，只写 * 应该不行；
/! USE_SCROLL/是有默认值的，默认存活时间是60000(ms)[https://github.com/NLPchina/elasticsearch-sql/wiki/Scroll](Scroll)

**Comment by ssjjcao** [comment]
@WhisperLoli  hello
1. 想要获取_scroll_id字段的话，应该是需要在select语句中明确写出的
2. /! USE_SCROLL/是有默认存活时间的，60000(ms) 具体可以参考：[Scroll](https://github.com/NLPchina/elasticsearch-sql/wiki/Scroll)

**Comment by shi-yuan** [comment]
可以指定存活时间，30000就是存活时间（单位毫秒）：
```sql
SELECT /*! USE_SCROLL(100,30000)*/ firstname , balance FROM accounts
SELECT /*! USE_SCROLL("DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAABFklUS2VfQnVIU2k2U3h4UUVKM1d4ZFEAAAAAAAAAAhZJVEtlX0J1SFNpNlN4eFFFSjNXeGRRAAAAAAAAAAMWSVRLZV9CdUhTaTZTeHhRRUozV3hkUQAAAAAAAAAEFklUS2VfQnVIU2k2U3h4UUVKM1d4ZFEAAAAAAAAABRZJVEtlX0J1SFNpNlN4eFFFSjNXeGRR" ,30000)*/ firstname , balance FROM accounts
```

**Comment by ZQbd** [comment]
这个是有问题的，第二次返回的scrollid和第一次返回的scrollid是一样的，然后第三次查询就会报错
@shi-yuan

**Comment by shi-yuan** [comment]
scrollid不一定会每次都变的，本地测试，是可以一直查的
![image](https://user-images.githubusercontent.com/8057153/63647754-9a393280-c758-11e9-9372-e8663cfec6f0.png)
![image](https://user-images.githubusercontent.com/8057153/63647756-a1f8d700-c758-11e9-84b0-49db6cd27c6e.png)
![image](https://user-images.githubusercontent.com/8057153/63647757-ab823f00-c758-11e9-93a4-565350838e8f.png)
![image](https://user-images.githubusercontent.com/8057153/63647758-afae5c80-c758-11e9-8e82-1cd4bc416e2c.png)

**Comment by fu19900808** [comment]
为什么我用JDBC的方式，一直没有往前滚动，一直返回同样的数据，请问是哪里设置的问题吗？
----"select /*! USE_SCROLL(1,30000)*/ id,username,description,_scroll_id from chery_bpm_wf_hist_taskflow order by id"，工具页面查也是一样，没有先前滚动，一直是重复数据

**Comment by liyongfei011426** [comment]
使用jdbc怎么拿到

> @shi-yuan 程序中使用SQL查询，结果集中如何拿到scroll id呢，我看了一下返回字段只有_source中的字段和 _id，没有返回_scroll_id字段啊 ![image](https://user-images.githubusercontent.com/31977300/60939576-d6c8e000-a30a-11e9-8550-17ebc7d12d03.png)


> 可以指定存活时间，30000就是存活时间（单位毫秒）：
> 
> ```sql
> SELECT /*! USE_SCROLL(100,30000)*/ firstname , balance FROM accounts
> SELECT /*! USE_SCROLL("DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAABFklUS2VfQnVIU2k2U3h4UUVKM1d4ZFEAAAAAAAAAAhZJVEtlX0J1SFNpNlN4eFFFSjNXeGRRAAAAAAAAAAMWSVRLZV9CdUhTaTZTeHhRRUozV3hkUQAAAAAAAAAEFklUS2VfQnVIU2k2U3h4UUVKM1d4ZFEAAAAAAAAABRZJVEtlX0J1SFNpNlN4eFFFSjNXeGRR" ,30000)*/ firstname , balance FROM accounts
> ```

使用jdbc怎么拿到scrollid，没看到返回

**Comment by liyongfei011426** [comment]
> 可以指定存活时间，30000就是存活时间（单位毫秒）：
> 
> ```sql
> SELECT /*! USE_SCROLL(100,30000)*/ firstname , balance FROM accounts
> SELECT /*! USE_SCROLL("DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAABFklUS2VfQnVIU2k2U3h4UUVKM1d4ZFEAAAAAAAAAAhZJVEtlX0J1SFNpNlN4eFFFSjNXeGRRAAAAAAAAAAMWSVRLZV9CdUhTaTZTeHhRRUozV3hkUQAAAAAAAAAEFklUS2VfQnVIU2k2U3h4UUVKM1d4ZFEAAAAAAAAABRZJVEtlX0J1SFNpNlN4eFFFSjNXeGRR" ,30000)*/ firstname , balance FROM accounts
> ```

使用jdbc怎么拿到这个scrollid了，没看到返回

**Comment by shi-yuan** [comment]
> 用jdbc的话，直接：
> 
> ```sql
> select /*! USE_SCROLL*/ gender,lastname,age,_scroll_id from elasticsearch-sql_test_index_account where lastname='Heath'
> ```

带上`_scroll_id`
