### ISSUE TITLE
About query LIKE with special characters

### ISSUE THREAD

**Issue by imqishi** [NLPchina/elasticsearch-sql#581]
When I use LIKE to search an url such as LIKE   '\*store-images.s-microsoft.com\*', it can not work correctly. But search 'microsoft.com' (use LIKE) can get related rows. So I doubt that the special character '-' cause this error. 
Also, use WHERE to search 'store-images.s-microsoft.com' is OK, so if LIKE has something wrong?

**Comment by imqishi** [comment]
Well, I test in mysql, LIKE '%some-thing%' with '-' is OK, so is it not compatible?

**Comment by shi-yuan** [comment]
mapping:
```json
{
  "test" : {
    "mappings" : {
      "test" : {
        "properties" : {
          "a" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          }
        }
      }
    }
  }
}
```
document:
```json
{
	"a":"store-images.s-microsoft.com"
}
```
test:
![image](https://user-images.githubusercontent.com/8057153/34827986-f850db34-f716-11e7-9b3d-b9005ab175d4.png)

**Comment by imqishi** [comment]
Wow, thanks! It works when use ".keyword"
