### ISSUE TITLE
How to remove default limit(maybe 200,max in 1024) in SELECT query ?

### ISSUE THREAD

**Issue by CoolGrancy** [NLPchina/elasticsearch-sql#591]
like this sql
`select * from table1 where  phone in (select phone in table2 where condition=a)  and phone in (select phone in table2 where condition=b)`

If you have a maximum limit in both condition a and b in query for table2, the result will be inaccurate, there will not the union that I want, so give me some help please

**Comment by shi-yuan** [comment]
you could add limit:
```sql
select * from table2 limit 3000
```
```json
{
	"from": 0,
	"size": 3000
}
```

**Comment by CoolGrancy** [comment]
@shi-yuan yes, when I try then function `IN_TERMS`, the maximum even can be 10000, but the value is much smaller then I want yet.

query result in table2 can also bigger than 10,000,000 , so this solution with `limit` cannot be useful

**Comment by shi-yuan** [comment]
Very large terms query!
I think, you could use [Joining queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/joining-queries.html), or you could submit a series of queries and join the result hits
