### ISSUE TITLE
support for SQL with SubQuery

### ISSUE THREAD

**Issue by sim1st** [NLPchina/elasticsearch-sql#60]
In source code, there is an class includes method that adds Subquery in class named 'org.nlpcn.es4sql.query.maker.Querymaker'

But SQL like [  select * from where fieldname in (select ~)  ] doesn't support I think.

Did I used wrong expression?

Or does it support yet?

**Comment by omershelef** [comment]
Subqueries is not supported in elasticsearch-sql.

**Comment by umaxfun** [comment]
Test query:
```select * from web inner join (select * from web where props.Article like '%alfa%') qwe on web.props.Article = qwe.props.Article```

Result:
```{"error":"ClassCastException[com.alibaba.druid.sql.ast.statement.SQLSubqueryTableSource cannot be cast to com.alibaba.druid.sql.ast.statement.SQLJoinTableSource]","status":500}```

Are they supported now but I use them unsupported way? :)

**Comment by eliranmoyal** [comment]
Well by sub queries I meant 
`select * from x where in ( select..)`

On joins both need to be tables.. just push the where to the end.
like that:
```sql
select w1.props from web w1 
join web qwe 
on w1.props.Article = qwe.props.Article
where qwe.props.Article like '%alfa%'
```

**Comment by satapsa** [comment]
In Elasticsearch - when you sat 2 tables - do you mean 2 indices - where w1 is one index and w2 is another ?

**Comment by umaxfun** [comment]
My real problem is that my index has self references. We have kind of a table
```
ID | Name | ReferenceToAnotherId
1  | Jack | null
2  | Bill | 1 -- < here 1 is a reference to the first record 
```

I'm trying to get how to make a query like this:
```
SELECT w.ID, w.Name, o.Name 
FROM web w
INNER_JOIN web o on w.ReferenceToAnotherId=o.ID  
WHERE name = 'Bill' 
``` 

so that result was ```1, Bill, Jack```

**Comment by eliranmoyal** [comment]
Your query was just fine until the where. just put the o.name ='Bill'
and just call it join, there is no meaning for inner here
like this:

```SELECT w.ID, w.Name, o.Name 
FROM web w
JOIN web o on w.ReferenceToAnotherId=o.ID  
WHERE o.name = 'Bill'```

**Comment by umaxfun** [comment]
Wow! It was just a typo, thank you very much for your help!

And does the machinery of joins work when field type is an [array](https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html)? We have arrays of ids stored in one field (kind of one to many relationship). So the table above becomes this one:
```
ID | Name | RelatedIDs
1  | Jack | null
2  | Bill | null
3  | Mary | [1,2]  -- < here is a reference to the records 1 and 2 
```

The expected result after some joiny sql query I cannot imagine is:
```{ ID: 3, Name: 'Mary', SomeField: ['Jack', 'Bill'] } ```

Am I missing a helper function or something?

**Comment by eliranmoyal** [comment]
Haven't tried I think it should work (because elasticsearch can search terms in arrays ) but you will have 2 results and not one..
Try this:
{ ID: 3, Name: 'Mary', RelatedName: 'Jack' }
{ ID: 3, Name: 'Mary', RelatedName: 'Bill' }
```
select w2.ID , w2.Name , w1.Name  from web w1
join web w2 on w2.RelatedIDs in w1.ID
```

Or this
```
select w2.ID , w2.Name , w1.Name  from web w1
join web w2 on w2.RelatedIDs  = TERM(w1.ID)
```
