### ISSUE TITLE
Sql Query in Elastic Search

### ISSUE THREAD

**Issue by devanshusharma19** [NLPchina/elasticsearch-sql#601]
Hi 
I have two index both have 1 lac. more then data. I want to apply inner join with column condition. We have apply join then result get more then 1 lac. but i get only 1lac. data.
Why please tell how to solve that one problem.
index 1 = 265191429v5 and data size = 1157603
index 1 = 265191429v3 and data size = 1157603
Query :- SELECT t0.*,t1.* FROM 265191429v5 t0 INNER JOIN 265191429v3 t1 ON ([t0.order_id] = [t1.order_id]) limit 2315206

******************************code*************************
SearchDao searchDao = new SearchDao(esClient);
SqlElasticRequestBuilder explain = searchDao.explain(query).explain();
ElasticJoinExecutor executor = ElasticJoinExecutor.createJoinExecutor(searchDao.getClient(), explain);
executor.run();
SearchHits hits = executor.getHits();
*************************************************************
I have got only 1 lac. hit but result more then 1 lac.
Please tell me solution....
Thank You

**Comment by shi-yuan** [comment]
you could explain your sql first：
```
HashJoin  
first query:
{
  "from": 0,
  "size": 200,
  "_source": {
    "includes": [
      "",
      "order_id"
    ],
    "excludes": []
  }
}
second query:
{
  "from": 0,
  "size": 200,
  "_source": {
    "includes": [
      "",
      "order_id"
    ],
    "excludes": []
  }
}
```
