### ISSUE TITLE
_id in query returns all results if the list is empty

### ISSUE THREAD

**Issue by SadasiSn** [NLPchina/elasticsearch-sql#602]
**Select data from index where _id in ()_** 
returns all results if the list is empty. I used an inner query to get the ids as:

**Select data from index where _id in (select someid from index where CONDITION)_**

When the inner query returns empty resultset, I expect an empty result for the first query as well. But the first query returns all collections in the index.

**Comment by shi-yuan** [comment]
```sql
SELECT data FROM index WHERE id = IN_TERMS(SELECT someid FROM index WHERE CONDITION)
```
