### ISSUE TITLE
Multiple index to apply inner join with condition

### ISSUE THREAD

**Issue by devanshusharma19** [NLPchina/elasticsearch-sql#605]
HI Friends
I want to inner join apply on multiple indexs more then two.
How can apply in elastic-sql. 
example query = SELECT * FROM 4456450v1 t0 INNER JOIN 4456449v1 t1 INNER JOIN 4456451mv1 t2 ON t0.student_id=t1.StudentId=t2.StudentId limit 5001 
can you explain me...
if you know about any function or method please tell me...
thank you...
*****************************code*****************************************
SearchDao searchDao = new SearchDao(esClient);
			SqlElasticRequestBuilder explain = searchDao.explain(query).explain();
			ElasticJoinExecutor executor = ElasticJoinExecutor.createJoinExecutor(searchDao.getClient(), explain);
			executor.run();
			SearchHits hits = executor.getHits();

**Comment by shi-yuan** [comment]
Only support 2 tables join. 
I think you can query:
```sql
SELECT * FROM 4456450v1 t0 INNER JOIN 4456449v1 t1 ON t0.student_id=t1.StudentId WHERE t1.StudentId = IN_TERMS(SELECT t2.StudentId FROM 4456451mv1 t2) limit 5001
```
