### ISSUE TITLE
group by twofields

### ISSUE THREAD

**Issue by sim1st** [NLPchina/elasticsearch-sql#61]
Is this plugin doesn't support group by two fields?  Like 'select f1, f2 from index/type groupby f1, f2'

I think QueryDSL is generated well, but response is different with query done in ES head plugin.

**Comment by omershelef** [comment]
That query actually should work.
Can you give a concrete example of this query and why you think the results is wrong?

**Comment by ansjsun** [comment]
i think if you used group by .you must use agg function ! like this ... select count(*) from index group by f1,f2
