### ISSUE TITLE
Is that possible to run NLPchina with AWS elasticsearch

### ISSUE THREAD

**Issue by BoABC** [NLPchina/elasticsearch-sql#611]
Hi,

This is an awesome package. But my problem is that AWS elasticsearch does not allow customers to install their own plugins. Is it possible to run NLPchina as a node.js application without installing any plugin in elasticsearch?

Thanks,
Bo

**Comment by shi-yuan** [comment]
You could import
```xml
<dependency>
	<groupId>org.nlpcn</groupId>
	<artifactId>elasticsearch-sql</artifactId>
	<version>x.x.x.x</version>
</dependency>
```
Then 
```java
SearchDao searchDao = new SearchDao(esClient);
String result = searchDao.explain(sql).explain().get().toString();
```

**Comment by BoABC** [comment]
Thank you very much@shi-yuan 
It's cool to use the programming API directly.
But I'm wondering is that possible to stand up a service by setting up an elasticsearch endpoint like this package https://github.com/lmenezes/cerebro

**Comment by shi-yuan** [comment]
[elasticsearch-site](https://github.com/NLPchina/elasticsearch-site)

**Comment by BoABC** [comment]
Thank you. I see elasticsearch-site uses transport client. But aws elasticsearch only supports RESTful api. Is there a way to solve it or I missed anything again?

**Comment by shi-yuan** [comment]
Start [elasticsearch-site](https://github.com/NLPchina/elasticsearch-site), http://localhost:8080/apidoc

![1](https://user-images.githubusercontent.com/8057153/36707347-de4dc542-1ba8-11e8-969a-5dbcac02391b.png)

Three API

**Comment by shi-yuan** [comment]
For explain api:
http://localhost:8080/api/SqlApi/explain?sql=SELECT * FROM index
![1](https://user-images.githubusercontent.com/8057153/36707475-69807b5a-1ba9-11e8-83ca-716ff98933c5.png)

**Comment by BoABC** [comment]
I don't understand. Did you post on the wrong issue?

**Comment by shi-yuan** [comment]
elasticsearch-site connnect to elasticsearch and supports RESTful api, you can send request to elasticsearch-site

**Comment by colourmeamused** [comment]
@shi-yuan AWS provides Elasticsearch as a managed service with no access via HTTP transport client or to install plugins. Basically you can't configure [ioc.js](https://github.com/NLPchina/elasticsearch-site/blob/master/jcoder_home/resource/ioc.js) to connect to the AWS Elasticsearch service.

@BoABC My understanding is elastisearch-site would need to be modified to use the new [Java REST client](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-level-migration.html). I might give it a shot to see how tricky it is.

**Comment by shi-yuan** [comment]
Yeah，elastisearch-site use transport client now！
