### ISSUE TITLE
[Feature request]Provide option to get query as locally on client, without connection to ES

### ISSUE THREAD

**Issue by siddv29** [NLPchina/elasticsearch-sql#618]
i am trying to use elasticsearch-sql with [elasticsearch-knapsack](https://github.com/jprante/elasticsearch-knapsack) to dump data from index to file/another index/another cluster, without any transfer of data to client.

If I could get the query, as a string locally on the client, the transfer of data on client would be avoided. And using knapsack, the data would be dumped in file/index from the cluster itself.

**Comment by siddharth-verma-guavus** [comment]
Hi, if someone has encountered this issue, could you please provide your $0.02 on how to solve it.

**Comment by shi-yuan** [comment]
You could explain your sql to get the elasticsearch query dsl, then export search results

**Comment by siddv29** [comment]
Thanks for your reply :-)
Yup, that would be the way forward.
I was trying to use `ExplainTest.searchSanity` to get an idea to explain the query. But it requires connection to ES. 
Could you please suggest the way to do that.

**Comment by shi-yuan** [comment]
```java
SearchDao searchDao = new SearchDao(null);
String dsl = searchDao.explain("SELECT * FROM index").explain().explain();
System.out.println(dsl);
```

**Comment by siddv29** [comment]
Worked like a charm!! 
Thanks a lot!!...

**Comment by siddharth-verma-guavus** [comment]
Updating on how to use it for ES 5.6
1. checkout elastic5.6.0
2. git cherry-pick ae34a7bace00bc7be32e367eaf56e13f7e5b21ae

use the following code snippet to generate ES query 
`Client client = new Client() {
            @Override
            public AdminClient admin() {
                return null;
            }

            @Override
            public ActionFuture<IndexResponse> index(IndexRequest indexRequest) {
                return null;
            }

            @Override
            public void index(IndexRequest indexRequest, ActionListener<IndexResponse> actionListener) {

            }

            @Override
            public IndexRequestBuilder prepareIndex() {
                return null;
            }

            @Override
            public ActionFuture<UpdateResponse> update(UpdateRequest updateRequest) {
                return null;
            }

            @Override
            public void update(UpdateRequest updateRequest, ActionListener<UpdateResponse> actionListener) {

            }

            @Override
            public UpdateRequestBuilder prepareUpdate() {
                return null;
            }

            @Override
            public UpdateRequestBuilder prepareUpdate(String s, String s1, String s2) {
                return null;
            }

            @Override
            public IndexRequestBuilder prepareIndex(String s, String s1) {
                return null;
            }

            @Override
            public IndexRequestBuilder prepareIndex(String s, String s1, String s2) {
                return null;
            }

            @Override
            public ActionFuture<DeleteResponse> delete(DeleteRequest deleteRequest) {
                return null;
            }

            @Override
            public void delete(DeleteRequest deleteRequest, ActionListener<DeleteResponse> actionListener) {

            }

            @Override
            public DeleteRequestBuilder prepareDelete() {
                return null;
            }

            @Override
            public DeleteRequestBuilder prepareDelete(String s, String s1, String s2) {
                return null;
            }

            @Override
            public ActionFuture<BulkResponse> bulk(BulkRequest bulkRequest) {
                return null;
            }

            @Override
            public void bulk(BulkRequest bulkRequest, ActionListener<BulkResponse> actionListener) {

            }

            @Override
            public BulkRequestBuilder prepareBulk() {
                return null;
            }

            @Override
            public ActionFuture<GetResponse> get(GetRequest getRequest) {
                return null;
            }

            @Override
            public void get(GetRequest getRequest, ActionListener<GetResponse> actionListener) {

            }

            @Override
            public GetRequestBuilder prepareGet() {
                return null;
            }

            @Override
            public GetRequestBuilder prepareGet(String s, String s1, String s2) {
                return null;
            }

            @Override
            public ActionFuture<MultiGetResponse> multiGet(MultiGetRequest multiGetRequest) {
                return null;
            }

            @Override
            public void multiGet(MultiGetRequest multiGetRequest, ActionListener<MultiGetResponse> actionListener) {

            }

            @Override
            public MultiGetRequestBuilder prepareMultiGet() {
                return null;
            }

            @Override
            public ActionFuture<SearchResponse> search(SearchRequest searchRequest) {
                return null;
            }

            @Override
            public void search(SearchRequest searchRequest, ActionListener<SearchResponse> actionListener) {

            }

            @Override
            public SearchRequestBuilder prepareSearch(String... strings) {
                return null;
            }

            @Override
            public ActionFuture<SearchResponse> searchScroll(SearchScrollRequest searchScrollRequest) {
                return null;
            }

            @Override
            public void searchScroll(SearchScrollRequest searchScrollRequest, ActionListener<SearchResponse> actionListener) {

            }

            @Override
            public SearchScrollRequestBuilder prepareSearchScroll(String s) {
                return null;
            }

            @Override
            public ActionFuture<MultiSearchResponse> multiSearch(MultiSearchRequest multiSearchRequest) {
                return null;
            }

            @Override
            public void multiSearch(MultiSearchRequest multiSearchRequest, ActionListener<MultiSearchResponse> actionListener) {

            }

            @Override
            public MultiSearchRequestBuilder prepareMultiSearch() {
                return null;
            }

            @Override
            public ActionFuture<TermVectorsResponse> termVectors(TermVectorsRequest termVectorsRequest) {
                return null;
            }

            @Override
            public void termVectors(TermVectorsRequest termVectorsRequest, ActionListener<TermVectorsResponse> actionListener) {

            }

            @Override
            public TermVectorsRequestBuilder prepareTermVectors() {
                return null;
            }

            @Override
            public TermVectorsRequestBuilder prepareTermVectors(String s, String s1, String s2) {
                return null;
            }

            @Override
            public ActionFuture<TermVectorsResponse> termVector(TermVectorsRequest termVectorsRequest) {
                return null;
            }

            @Override
            public void termVector(TermVectorsRequest termVectorsRequest, ActionListener<TermVectorsResponse> actionListener) {

            }

            @Override
            public TermVectorsRequestBuilder prepareTermVector() {
                return null;
            }

            @Override
            public TermVectorsRequestBuilder prepareTermVector(String s, String s1, String s2) {
                return null;
            }

            @Override
            public ActionFuture<MultiTermVectorsResponse> multiTermVectors(MultiTermVectorsRequest multiTermVectorsRequest) {
                return null;
            }

            @Override
            public void multiTermVectors(MultiTermVectorsRequest multiTermVectorsRequest, ActionListener<MultiTermVectorsResponse> actionListener) {

            }

            @Override
            public MultiTermVectorsRequestBuilder prepareMultiTermVectors() {
                return null;
            }

            @Override
            public ExplainRequestBuilder prepareExplain(String s, String s1, String s2) {
                return null;
            }

            @Override
            public ActionFuture<ExplainResponse> explain(ExplainRequest explainRequest) {
                return null;
            }

            @Override
            public void explain(ExplainRequest explainRequest, ActionListener<ExplainResponse> actionListener) {

            }

            @Override
            public ClearScrollRequestBuilder prepareClearScroll() {
                return null;
            }

            @Override
            public ActionFuture<ClearScrollResponse> clearScroll(ClearScrollRequest clearScrollRequest) {
                return null;
            }

            @Override
            public void clearScroll(ClearScrollRequest clearScrollRequest, ActionListener<ClearScrollResponse> actionListener) {

            }

            @Override
            public FieldStatsRequestBuilder prepareFieldStats() {
                return null;
            }

            @Override
            public ActionFuture<FieldStatsResponse> fieldStats(FieldStatsRequest fieldStatsRequest) {
                return null;
            }

            @Override
            public void fieldStats(FieldStatsRequest fieldStatsRequest, ActionListener<FieldStatsResponse> actionListener) {

            }

            @Override
            public FieldCapabilitiesRequestBuilder prepareFieldCaps() {
                return null;
            }

            @Override
            public ActionFuture<FieldCapabilitiesResponse> fieldCaps(FieldCapabilitiesRequest fieldCapabilitiesRequest) {
                return null;
            }

            @Override
            public void fieldCaps(FieldCapabilitiesRequest fieldCapabilitiesRequest, ActionListener<FieldCapabilitiesResponse> actionListener) {

            }

            @Override
            public Settings settings() {
                return null;
            }

            @Override
            public Client filterWithHeader(Map<String, String> map) {
                return null;
            }

            @Override
            public <Request extends ActionRequest, Response extends ActionResponse, RequestBuilder extends ActionRequestBuilder<Request, Response, RequestBuilder>> ActionFuture<Response> execute(Action<Request, Response, RequestBuilder> action, Request request) {
                return null;
            }

            @Override
            public <Request extends ActionRequest, Response extends ActionResponse, RequestBuilder extends ActionRequestBuilder<Request, Response, RequestBuilder>> void execute(Action<Request, Response, RequestBuilder> action, Request request, ActionListener<Response> actionListener) {

            }

            @Override
            public <Request extends ActionRequest, Response extends ActionResponse, RequestBuilder extends ActionRequestBuilder<Request, Response, RequestBuilder>> RequestBuilder prepareExecute(Action<Request, Response, RequestBuilder> action) {
                return null;
            }

            @Override
            public ThreadPool threadPool() {
                return null;
            }

            @Override
            public void close() {

            }
        };
        SearchDao searchDao = new SearchDao(client);
        System.out.println(searchDao.explain(sqlQuery).explain().explain());
`
Maven dependencies 
`
		<dependency>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch</artifactId>
			<version>5.6.0</version>
		</dependency>
		<dependency>
			<groupId>org.elasticsearch.client</groupId>
			<artifactId>transport</artifactId>
			<version>5.6.0</version>
		</dependency>
		<dependency>
			<groupId>org.nlpcn</groupId>
			<artifactId>elasticsearch-sql</artifactId>
			<version>5.6.0.0</version>
		</dependency>
`
