### ISSUE TITLE
Support Elasticsearch 1.5

### ISSUE THREAD

**Issue by omershelef** [NLPchina/elasticsearch-sql#62]
We need to make the plugin support in elasticsearch 1.5.X. As described in #54 it currently not working...

**Comment by norberto-enomoto** [comment]
What is the roadmap to have the plugin support for Elasticsearch 1.5.x?

**Comment by jstortz** [comment]
Just noting here that ElasticSearch 1.6 was released on June 9th.

**Comment by yehosef** [comment]
+1
