### ISSUE TITLE
这样的嵌套查询怎么写啊？

### ISSUE THREAD

**Issue by xuan321** [NLPchina/elasticsearch-sql#620]
满足这样的需求:
SELECT  * FROM gd_resource a  
WHERE (
SELECT count(*) FROM gd_resource b WHERE b.GOODS_CATE_ID=a.GOODS_CATE_ID AND b.RESOURCE_ID>a.RESOURCE_ID 
)<2

**Comment by shi-yuan** [comment]
分两次查询吧，
首先SELECT * FROM gd_resource a，
然后bulk查询判断SELECT count(*) FROM gd_resource b WHERE b.GOODS_CATE_ID=a.GOODS_CATE_ID 
 AND b.RESOURCE_ID>a.RESOURCE_ID)<2

**Comment by xuan321** [comment]
这样的话，查询全部，还不如用每个的cateId去查询前2条呢(●ˇ∀ˇ●)。。

**Comment by shi-yuan** [comment]
也可以分组GOODS_CATE_ID,RESOURCE_ID，然后取出RESOURCE_ID倒序排的前两个，经判断后得到GOODS_CATE_ID,RESOURCE_ID，之后再来获取数据

**Comment by xuan321** [comment]
非常感谢你，这个sql是分组查每组的前几条，现在使用每个cateid解决，这样的语法是不能支持的啊

**Comment by shi-yuan** [comment]
```sql
SELECT COUNT(*) FROM gd_resource GROUP BY GOODS_CATE_ID, TERMS('field'='RESOURCE_ID','order'='desc')
```

**Comment by xuan321** [comment]
@shi-yuan 可以的，还要其他的属性怎么办，还要其他的属性。😝

**Comment by shi-yuan** [comment]
量不大的话，可以试试topHits，否则二次搜索吧
