### ISSUE TITLE
Can't POST error in web UI

### ISSUE THREAD

**Issue by EndlessTundra** [NLPchina/elasticsearch-sql#623]
I've seen some other issues filed that are similar but I couldn't find any actual solutions.  I'm running elasticsearch-sql 6.2.2 and I am able to successfully query the API with a curl command like this:

`curl -H "Content-Type: application/json" -XPOST 'http://localhost:9200/_sql' -d 'SELECT * FROM index LIMIT 10'`

However, if I try and use the Web UI I get this message:
`"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /_sql</pre>\n</body>\n</html>\n"`

I've enabled cors with the below lines in elasticsearch.yml:
```
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
```

What am I missing here?

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/wiki/Installation-Guide#elasticsearch-5x6x

**Comment by RainTown67** [comment]
Same here.  ES cluster is available on port 9200, and this works:

curl -s -u elastic:mypassword -H "Content-Type: application/json" -XPOST 'http://localhost:9200/_sql' -d 'SELECT FCID FROM myindex LIMIT 10' 

I can reach webUI on localhost:8080 but search or explain give errors.

# rpm -q elasticsearch
elasticsearch-6.2.2-1.noarch

# tail -3 /etc/elasticsearch/elasticsearch.yml
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, Authorization"

Used latest plugin

elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/6.2.2.0/elasticsearch-sql-6.2.2.0.zip

what are EndlessTundra  and I missng?

**Comment by shi-yuan** [comment]
![image](https://user-images.githubusercontent.com/8057153/37262622-4154a1f2-25df-11e8-90d5-157e351f489f.png)

**Comment by EndlessTundra** [comment]
Ah I see what you mean.  It defaults to http://servername:8080.  Thanks for the help it works now!

**Comment by muppidimanisha** [comment]
Hi,

I need help in installing this plugin:
I Ran below command :
./bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/6.6.1.0/elasticsearch-sql-6.6.1.0.zip

Documentation shows next steps as 👍 : On elasticsearch 5.x/6.x, use elasticsearch sql site chrome extension (make sure to enable cors on elasticsearch.yml). 
 
How and here should i enable this elastic-sql site chrome extension.
I have included below parameters in elasticsearch.yml where this plugin is installed:
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, Authorization"

We are having 13 nodes in our cluster ,do i need to include above 3 parameters in all the hosts or just the host where plugin is installed?
Thanks in Advance!

**Comment by shi-yuan** [comment]
you can select one node to config，then access the node in chrome extension

**Comment by muppidimanisha** [comment]
Hi Yuan,

Thanks for the reply!
I tried to access through port 8080 or 9200 but it was saying site can't be reached.
Our environment is https enabled ,does this plugin support https?
If it does support https is there any other configuration that needs to b done?

Thanks,
Manisha.

**Comment by shi-yuan** [comment]
Yes, support https

![image](https://user-images.githubusercontent.com/8057153/71774045-c1273100-2fa2-11ea-9bd0-ed9a6d083f5b.png)

**Comment by mani-arch** [comment]
Hi,


Could you please provide me the configuration information for this.
We are using 6.6 environment.
