### ISSUE TITLE
should must install at ES server , why cann't be use in client ? i don't want install as a plugin ,just use it as a client jar

### ISSUE THREAD

**Issue by javait90** [NLPchina/elasticsearch-sql#624]
es-sql must install at ES server , why can't be use in client ? i don't want install as a plugin ,just use it as a client jar

**Comment by shi-yuan** [comment]
[[Feature request]Provide option to get query as locally on client, without connection to ES](https://github.com/NLPchina/elasticsearch-sql/issues/618)
