### ISSUE TITLE
Select date filed as time millis.

### ISSUE THREAD

**Issue by yangjiajun2014** [NLPchina/elasticsearch-sql#632]
I want to get timemills form date  in my result.How should I write the sql?

**Comment by leonlu001** [comment]
Their is a field named xx_to_time , if your field type is date. 发自我的华为手机

**Comment by shi-yuan** [comment]
```sql
SELECT script("timemills","doc['date'].value.getMillis()") FROM indexName
```

**Comment by yangjiajun2014** [comment]
But it does not work.I use 5.6.2  version.
{
	"from": 0,
	"size": 200,
	"_source": {
		"includes": [],
		"excludes": []
	},
	"script_fields": {
		"timemills": {
			"script": {
				"source": "doc['timestamp'].value.getMillis()",
				"lang": "painless"
			},
			"ignore_failure": false
		}
	}
}

**Comment by shi-yuan** [comment]
```sql
SELECT script("timemills","doc['date'].value") FROM indexName
```

**Comment by yangjiajun2014** [comment]
Thanks.
