### ISSUE TITLE
ResultSetMetaData.getColumnCount() get the value is zero???

### ISSUE THREAD

**Issue by when520** [NLPchina/elasticsearch-sql#633]
ResultSetMetaData metaData = resultSet.getMetaData();
int columnCnt = metaData.getColumnCount();

I get the columnCnt  is zero 
and metaData.getColumnName(i) get null

**Comment by shi-yuan** [comment]
![1](https://user-images.githubusercontent.com/8057153/37873873-654e867c-3057-11e8-9834-b3571350ef4f.png)

**Comment by when520** [comment]
What version of the Elasticsearch are you using?
Before get your message, I thought only Elasticsearch 5.6.3  can use the getColumnCount function

**Comment by when520** [comment]
Are you Chinese? In this I can use 中文

**Comment by shi-yuan** [comment]
Elasticsearch 6.2.1
