### ISSUE TITLE
Unable to query indexes with names starting with a number 

### ISSUE THREAD

**Issue by neerav-salaria-guavus** [NLPchina/elasticsearch-sql#634]
My index name in ES is **15jan-conn-2018.01.09**. When i am trying to run command:
**SELECT * FROM 15jan-conn-2018.01.09 limit 10**
Version used : es-sql : 5.6.2

Getting following error:
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"15jan - conn-2018.01.09","index_uuid":"_na_","index":"15jan - conn-2018.01.09"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"15jan - conn-2018.01.09","index_uuid":"_na_","index":"15jan - conn-2018.01.09"},"status":404}

Here the index name got changed from **"15jan-conn-2018.01.09"** to **"15jan - conn-2018.01.09".** One can see extra white spaces in the index name. 

If i remove the number i am able to fetch the data. Is there any limitation that an index name should not start with a number

**Comment by shi-yuan** [comment]
```sql
SELECT * FROM ['15jan-conn-2018.01.09'] limit 10
```
