### ISSUE TITLE
DATE_FORMAT is not supported

### ISSUE THREAD

**Issue by apratapi** [NLPchina/elasticsearch-sql#635]
HI Team,
I was trying to convert the SQL query in ES ,here is my sql query 

SELECT **DATE_FORMAT**(transaction_timestamp, '%Y-%m-%d %H') AS date_hour,partner_id,service_id,
servicename,(CASE WHEN service_type=1 THEN 'PPU' WHEN service_type=2 THEN 'Subscription' END)
 AS service_type,servicegroup,SUM(Counts) AS total_requests_count,SUM((CASE WHEN STATUS=0 THEN Counts ELSE 0 END))
  AS Billing_Status_Success,SUM(CASE WHEN STATUS =1   THEN Counts ELSE 0 END)
   AS Billing_Status_Failure FROM reports.diameter_in WHERE transaction_timestamp >= '2018-03-21 00:00:00'
 AND  transaction_timestamp <= '2018-03-21 23:59:59'   ORDER BY date_hour DESC LIMIT 0,10
 

**DATE_FORMAT** is unable to handled by switch case

**Comment by shi-yuan** [comment]
```sql
SELECT date_format(transaction_timestamp, '%Y-%m-%d %H') AS date_hour,partner_id,service_id,
servicename,(CASE WHEN service_type=1 THEN 'PPU' WHEN service_type=2 THEN 'Subscription' END)
AS service_type,servicegroup,SUM(Counts) AS total_requests_count,SUM((CASE WHEN STATUS=0 THEN Counts ELSE 0 END))
AS Billing_Status_Success,SUM(CASE WHEN STATUS =1 THEN Counts ELSE 0 END)
AS Billing_Status_Failure FROM reports.diameter_in WHERE transaction_timestamp >= '2018-03-21 00:00:00'
AND transaction_timestamp <= '2018-03-21 23:59:59' ORDER BY date_hour DESC LIMIT 0,10
```

**Comment by ggzone** [comment]
Help me.How to resolve this problem?

http://xxxx:9200/_sql?sql=select * from my_date1 limit 10
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 3,
    "max_score": 1,
    "hits": [
      {
        "_index": "my_date1",
        "_type": "ty",
        "_id": "2",
        "_score": 1,
        "_source": {
          "date": "2015-01-01T12:10:30Z"
        }
      },
      {
        "_index": "my_date1",
        "_type": "ty",
        "_id": "1",
        "_score": 1,
        "_source": {
          "date": "2015-01-01"
        }
      },
      {
        "_index": "my_date1",
        "_type": "ty",
        "_id": "3",
        "_score": 1,
        "_source": {
          "date": 1420070400001
        }
      }
    ]
  }
}

query:
http://xxxx:9200/_sql?sql=select date_format(date,'%Y-%m-%d %H') as dt from my_date1 limit 10
Response:
{
  "took": 8,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 2,
    "skipped": 0,
    "failed": 3,
    "failures": [
      {
        "shard": 2,
        "index": "my_date1",
        "node": "eN5Wc77sTUWWmkxG38tuhw",
        "reason": {
          "type": "script_exception",
          "reason": "runtime error",
          "script_stack": [
            "date_format_924910292 = new SimpleDateFormat('%Y-%m-%d %H').format(new Date(doc['date'].value - 8*1000*60*60));",
            "                                                                                       ^---- HERE"
          ],
          "script": "def date_format_924910292 = new SimpleDateFormat('%Y-%m-%d %H').format(new Date(doc['date'].value - 8*1000*60*60));return date_format_924910292;",
          "lang": "painless",
          "caused_by": {
            "type": "class_cast_exception",
            "reason": "class_cast_exception: Cannot apply [-] operation to types [org.joda.time.MutableDateTime] and [java.lang.Integer]."
          }
        }
      }
    ]
  },
  "hits": {
    "total": 3,
    "max_score": 1,
    "hits": []
  }
}

**Comment by amitbsconcept** [comment]
Even i was having similar problems with date_format function when tried to apply - but when i arrived looking for the solution i applied the changes and framed up the following query:

`SELECT date_format(mentioned_on,'%Y-%m-%d') as mentioned_on, topic_name, count(*) as total_mentions FROM mentions brand_id = '7' and mentioned_on > '2018-03-27 00:00:00' and mentioned_on <= '2018-04-03 23:59:59' and topic_name <> '' GROUP BY date_format(mentioned_on,'%Y-%m-%d'), topic_name ORDER BY mentioned_on ASC
`
Now when i try to execute the same - it gives me the following output

{
  "message": "Client request error: socket hang up",

  "statusCode": 502,

  "error": "Bad Gateway"
}

How can we fix up the same?

**Comment by shi-yuan** [comment]
[The question of date_format](https://github.com/NLPchina/elasticsearch-sql/issues/643)
