### ISSUE TITLE
代码里没有找到语法定义的文件

### ISSUE THREAD

**Issue by yiguolei** [NLPchina/elasticsearch-sql#639]
你好，SQL的语法声明文件不在代码库里吗？

**Comment by shi-yuan** [comment]
没有SQL的语法声明文件，可以看看[wiki](https://github.com/NLPchina/elasticsearch-sql/wiki)，或者[testcase](https://github.com/NLPchina/elasticsearch-sql/tree/master/src/test/java/org/nlpcn/es4sql)
