### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by kbylmz** [NLPchina/elasticsearch-sql#64]
Hi,

I failed to install this plugin. Exception message : "failed to download out of all possible locations"

I think this exception about proxy.

How can i change proxy settings? 

Thank you

**Comment by ansjsun** [comment]
cd es

like this  pwd
/home/ansj/soft/elasticsearch-1.6.0

input 

./bin/plugin -u https://github.com/NLPchina/elasticsearch-sql/releases/download/1.3.4/elasticsearch-sql-1.3.4.zip --install sql



and wait it ok !!



if not you can open  https://github.com/NLPchina/elasticsearch-sql/releases/download/1.3.4/elasticsearch-sql-1.3.4.zip  to down it ..and unzip in plugin dir!


if you can not down it .check you network !
