### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by trumanliu** [NLPchina/elasticsearch-sql#642]
使用 6.2.3 版本后，单独部署 site ，运行后，填入 es 地址，点击 explain 后报错，浏览器 console 中的错误为：
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource
~~看到有一个 chrome 插件版本，但是在应用市场没有搜索到，能否提供一下插件构建的文档？~~
已经安装本地插件，可以使用。site 的还是不会用

**Comment by shi-yuan** [comment]
elasticsearch.yml中配置
http.cors.enabled: true
http.cors.allow-origin: "*"

**Comment by trumanliu** [comment]
@shi-yuan 已解决，非常感谢！
