### ISSUE TITLE
The question of  date_format

### ISSUE THREAD

**Issue by myamor163** [NLPchina/elasticsearch-sql#643]
Fields Info:
  aa: date
   aa.value : 2018-01-03
Query：
   SELECT * FROM my_index date_format(aa,'yyyy-MM-dd') >'2018-01-01'

Error Info:
{"took":33,"timed_out":false,"_shards":{"total":5,"successful":3,"skipped":0,"failed":2,"failures":[{"shard":2,"index":"my_index","node":"BoagSNMCQVKQi7NKWgaovA","reason":{"type":"script_exception","reason":"runtime error","script_stack":["date_format_906303741 = new SimpleDateFormat('yyyy-MM-dd').format(new Date(doc['aa'].value - 8*1000*60*60));","                                                                                    ^---- HERE"],"script":"def date_format_906303741 = new SimpleDateFormat('yyyy-MM-dd').format(new Date(doc['aa'].value - 8*1000*60*60));date_format_906303741 > '2018-01-01'","lang":"painless","caused_by":{"type":"class_cast_exception","reason":"class_cast_exception: Cannot apply [-] operation to types [org.joda.time.MutableDateTime] and [java.lang.Integer]."}}}]},"hits":{"total":0,"max_score":null,"hits":[]}}

**Comment by shi-yuan** [comment]
```sql
SELECT * FROM my_index where date_format(aa,'yyyy-MM-dd') >'2018-01-01'
```
```json
{
  "from": 0,
  "size": 200,
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "script": {
                  "script": {
                    "source": "def date_format_1475564593 = DateTimeFormatter.ofPattern('yyyy-MM-dd').withZone(ZoneId.systemDefault()).format(Instant.ofEpochMilli(doc['aa'].value.getMillis()));date_format_1475564593 > '2018-01-01'",
                    "lang": "painless"
                  },
                  "boost": 1
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  }
}
```

**Comment by leonlu001** [comment]
aa type is date, by default, the date value is long, your can change the time string '2018-01-01' to unix long time value, then compare them.

**Comment by Jacky0312** [comment]
Does it support date_format now?
