### ISSUE TITLE
how to query if @ in index name? 

### ISSUE THREAD

**Issue by wangxiangyu** [NLPchina/elasticsearch-sql#644]
![image](https://user-images.githubusercontent.com/3917969/38187977-74df225a-368c-11e8-9082-ccf4e08c885b.png)
if @ exists in index name, error occurred when query. How to solve this problem? Thank you!

**Comment by shi-yuan** [comment]
```sql
SELECT * FROM ['billions-main.account.relation-admin-@2018.04.02']
```
