### ISSUE TITLE
i use the curl,when the url is too long,there is a false report.help

### ISSUE THREAD

**Issue by qazdcc** [NLPchina/elasticsearch-sql#647]
curl_setopt($ch, CURLOPT_URL, 'http:/............',very long.

error message:
string(546) "HTTP/1.0 401 Unauthorized
WWW-Authenticate: Basic realm="security" charset="UTF-8"
content-type: application/json; charset=UTF-8
content-length: 391

{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/bad-request]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication token for REST request [/bad-request]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}"

**Comment by shi-yuan** [comment]
https://www.elastic.co/guide/en/x-pack/current/http-clients.html
