### ISSUE TITLE
No enum constant org.nlpcn.es4sql.domain

### ISSUE THREAD

**Issue by harveysun** [NLPchina/elasticsearch-sql#649]
![image](https://user-images.githubusercontent.com/8164746/39116777-dac479b2-4717-11e8-96c7-418ebb9f8f88.png)

Does it support the grammar as below?

SELECT did
FROM user_profiler 
where **bh119.l_3 + bh119.l_7>10**
limit 10

**Comment by shi-yuan** [comment]
[ScriptQuery](https://github.com/NLPchina/elasticsearch-sql/wiki/ScriptQuery)
