### ISSUE TITLE
COUNT and GROUP BY

### ISSUE THREAD

**Issue by kyunam** [NLPchina/elasticsearch-sql#65]
I have documents like this:

"_index": "bulk_points",
"_type": "point",
"_id": "AU271DbeU5WrEKITY13S",
"_score": 1,
"_source": {
   "LOCATION": "23.454193,-132.883428",
   "CREATED_DATE": "2015-01-01T08:00:00.000Z",
   "orig_hex100": "4580:-120046",
}

I want to run 

"SELECT orig_hex100 AS mykey, COUNT(orig_hex100) AS myvalue FROM bulk_points/point GROUP BY orig_hex100"

and I want to receive the result like this

mykey                                        myvalue
"4580:-120046"                          798
"21077:-111932"        345

But the actual result looks like this

orig_hex100	myvalue
551	68
1476	62

and the raw response is

"aggregations": {
    "orig_hex100": {
      "doc_count_error_upper_bound": 45,
      "sum_other_doc_count": 1995897,
      "buckets": [
        {
          "key": "551",
          "doc_count": 34,
          "myvalue": {
            "value": 68
          }
        },
        {
          "key": "1476",
          "doc_count": 31,
          "myvalue": {
            "value": 62
          }
        },

- Why don't the "key" field values look like "4580:-120046" (a string delimited by ':' ) ?
- How do I get the result like this?

mykey                                        myvalue
"4580:-120046"                          798
"21077:-111932"        345

Any help is appreciated.
Thanks!
Q

**Comment by KangYongKyun** [comment]
if you will create index like below or set mapping configuration to index, It will works like that you want.

curl -XPOST localhost:9200/bulk_points -d '{
    "mappings" : {
        "point" : {
            "_source" : { "enabled" : true },
            "properties" : {
                "orig_hex100" : { "type" : "string", "index" : "not_analyzed" }
            }
        }
    }
}'

You must read elasticsearch's analysis and mapping.

elasticsearch analysis : https://www.elastic.co/guide/en/elasticsearch/guide/current/analysis-intro.html#analysis-intro
elasticsearch mapping : https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-intro.html

**Comment by kyunam** [comment]
ah  "not_analyzed"!
It works like a charm!
Thank you!

**Comment by omershelef** [comment]
By the way, the `orig_hex100 AS mykey` still return `orig_hex100` as the column name instead of `mykey`. the `AS` keyword is supported only for functions (aggregations have name in elasticsearch) for now. that is because oridinary field name change is not supported by elasticsearch query. (but can be achieved by transform the results from the query by the plugin.)

**Comment by kyunam** [comment]
Thanks for pointing this out. I was wondering about it too!
