### ISSUE TITLE
是否支持 exists 和case when查询

### ISSUE THREAD

**Issue by youzhagui2006** [NLPchina/elasticsearch-sql#654]
是否支持 exists 和case when查询？

**Comment by JinCheng-Huang** [comment]
@shi-yuan

**Comment by JinCheng-Huang** [comment]
@shi-yuan 
我使用你给的例子去做case when,如下：
SELECT *,
(case 
  when floor(overdue_level) = 2 then 'A' 
  when floor(overdue_level) < 2 then 'b'
  when floor(overdue_level) > 2 then 'c'
  else 'd' end) AS bee
FROM table_a
WHERE overdue_level is not missing
LIMIT 1000
执行后出现如下错误：
{
	"error": {
		"root_cause": [{
			"type": "script_exception",
			"reason": "compile error",
			"script_stack": ["if((def floor_1301571636 = Math.f ...", " ^---- HERE"],
			"script": "if((def floor_1301571636 = Math.floor(doc['overdue_level'].value);floor_1301571636 == 2)){'A'} else if((def floor_1736438494 = Math.floor(doc['overdue_level'].value);floor_1736438494 < 2)){'b'} else if((def floor_1870172313 = Math.floor(doc['overdue_level'].value);floor_1870172313 > 2)){'c'} else {'d'}",
			"lang": "painless"
		}],
		"type": "search_phase_execution_exception",
		"reason": "all shards failed",
		"phase": "query_fetch",
		"grouped": true,
		"failed_shards": [{
			"shard": 0,
			"index": "table_a",
			"node": "aN3h2t_CQyGJ1UFEuHrsYg",
			"reason": {
				"type": "script_exception",
				"reason": "compile error",
				"caused_by": {
					"type": "illegal_argument_exception",
					"reason": "invalid sequence of tokens near ['floor_1301571636'].",
					"caused_by": {
						"type": "no_viable_alt_exception",
						"reason": "no_viable_alt_exception: null"
					}
				},
				"script_stack": ["if((def floor_1301571636 = Math.f ...", " ^---- HERE"],
				"script": "if((def floor_1301571636 = Math.floor(doc['overdue_level'].value);floor_1301571636 == 2)){'A'} else if((def floor_1736438494 = Math.floor(doc['overdue_level'].value);floor_1736438494 < 2)){'b'} else if((def floor_1870172313 = Math.floor(doc['overdue_level'].value);floor_1870172313 > 2)){'c'} else {'d'}",
				"lang": "painless"
			}
		}],
		"caused_by": {
			"type": "script_exception",
			"reason": "compile error",
			"caused_by": {
				"type": "illegal_argument_exception",
				"reason": "invalid sequence of tokens near ['floor_1301571636'].",
				"caused_by": {
					"type": "no_viable_alt_exception",
					"reason": "no_viable_alt_exception: null"
				}
			},
			"script_stack": ["if((def floor_1301571636 = Math.f ...", " ^---- HERE"],
			"script": "if((def floor_1301571636 = Math.floor(doc['overdue_level'].value);floor_1301571636 == 2)){'A'} else if((def floor_1736438494 = Math.floor(doc['overdue_level'].value);floor_1736438494 < 2)){'b'} else if((def floor_1870172313 = Math.floor(doc['overdue_level'].value);floor_1870172313 > 2)){'c'} else {'d'}",
			"lang": "painless"
		}
	},
	"status": 500
}
