### ISSUE TITLE
6.2.2.0别名问题

### ISSUE THREAD

**Issue by l786170309** [NLPchina/elasticsearch-sql#655]
查询语句：
![query](https://user-images.githubusercontent.com/24506890/39559453-e3a17b1c-4ec8-11e8-9876-c661dd979c01.png)
结果：
![result](https://user-images.githubusercontent.com/24506890/39559461-f6d56ce8-4ec8-11e8-99e1-47e40b596fc0.png)
这是哪里有问题？

**Comment by shi-yuan** [comment]
别名用的是[Script Fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-script-fields.html)

year的类型是text？需要开启fielddata

**Comment by l786170309** [comment]
嗯，year是text类型，已经开启fielddata了，现在好使了，多谢！

**Comment by l786170309** [comment]
我又有另一个问题了：
查询语句：
![sql-agg](https://user-images.githubusercontent.com/24506890/39562628-47c08d0c-4edf-11e8-8521-250fe440d825.png)
_explain结果：
![agg](https://user-images.githubusercontent.com/24506890/39562647-6bb7dea4-4edf-11e8-86bb-d1656d0fc7d0.png)

GROUP BY查询结果数据少了，只有10条数据，原本应该是4071条结果。aggregations里的两个size是固定的么？把这两个size改大一些后， GROUP BY结果才是正确的-4071条。

**Comment by l786170309** [comment]
@shi-yuan

**Comment by shi-yuan** [comment]
200是插件里代码写的，10是es默认的
