### ISSUE TITLE
有关GROUP BY的问题

### ISSUE THREAD

**Issue by l786170309** [NLPchina/elasticsearch-sql#656]
我又有另一个问题了：
查询语句：
![sql-agg](https://user-images.githubusercontent.com/24506890/39563856-6a0bd2ea-4ee4-11e8-8e8f-6608c05b4bc5.png)

_explain结果：
![agg](https://user-images.githubusercontent.com/24506890/39563867-7280539c-4ee4-11e8-9266-3e318cff1653.png)

GROUP BY查询结果数据少了，只有10条数据，原本应该是4071条结果。aggregations里的两个size是固定的么？把这两个size改大一些后， GROUP BY结果才是正确的-4071条。

**Comment by shi-yuan** [comment]
200是插件里代码写的，10是es默认的

**Comment by l786170309** [comment]
嗯，明白了
