### ISSUE TITLE
sum() How to calculate the decimal ? sum() 如何计算小数?

### ISSUE THREAD

**Issue by iweisi** [NLPchina/elasticsearch-sql#660]
select sum(column_name) from index_name 
sum() How to calculate the decimal ?
sum() 如何计算小数?

I try the sql:
SELECT scripted_metric('init_script' = '_agg["sum"]=[];','map_script'='_agg.sum.add(doc["column_name"].value);' ,'combine_script'='double sum = 0.0; for (t in _agg.sum) { sum += t; } return sum;', 'reduce_script'='double sum = 0.0; for (t in _agg.sum) { sum += t; } return sum;') FROM index_name

result:
{"error":{"root_cause":[{"type":"parser_exception","reason":"unclosed str"}],"type":"parser_exception","reason":"unclosed str"},"status":500}

**Comment by shi-yuan** [comment]
```sql
SELECT scripted_metric(
  'init_script' = 'params._agg.sum=[];',
  'map_script'='params._agg.sum.add(doc["column_name"].value);' ,
  'combine_script'='double sum = 0.0; for (t in params._agg.sum) { sum += t; } return sum;', 
  'reduce_script'='double sum = 0.0; for (t in params._aggs) { sum += t; } return sum;') 
FROM index_name
```

**Comment by iweisi** [comment]
is wrong.
test sql : 
http://10.209.5.46:9200/_sql?sql=SELECT sum(yka315) FROM test/KC22K2
result: 
{
    "took": 153,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 641399,
        "max_score": 0,
        "hits": []
    },
    "aggregations": {
        "SUM(yka315)": {
            "value": 30831924
        }
    }
}

use Scripted Metric Aggregation:
http://10.209.5.46:9200/_sql?sql=SELECT scripted_metric(
  'init_script' = 'params._agg.sum=[];',
  'map_script'='params._agg.sum.add(doc["yka315"].value);' ,
  'combine_script'='double sum = 0.0; for (t in params._agg.sum) { sum += t; } return sum;', 
  'reduce_script'='double sum = 0.0; for (t in params._aggs) { sum += t; } return sum;') 
FROM test/KC22K2

result:
{
    "error": {
        "root_cause": [
            {
                "type": "parser_exception",
                "reason": "unclosed str"
            }
        ],
        "type": "parser_exception",
        "reason": "unclosed str"
    },
    "status": 500
}

**Comment by iweisi** [comment]
it's ok，thnaks.
