### ISSUE TITLE
how to use curl to get data use elastic-search sql 5.6.4

### ISSUE THREAD

**Issue by miaojianxin** [NLPchina/elasticsearch-sql#666]
i have installed elastic-search sql 5.6.4 ,and in the web html ,i can get data use select sql.
but i can't get data use curl in my program.
in  elasticsearch2.4.3 i can get data use curl  like this
 curl -XPOST http://10.93.18.34:9200/_sql -d 'SELECT * FROM audit where dDelay=-2053867461'

so how to use curl in  elastic-search sql 5.6.4 when  the nodejs  started.  thank you

**Comment by shi-yuan** [comment]
```bash
curl -XPOST http://10.93.18.34:9200/_sql -H 'Content-Type: application/json' -d 'SELECT * FROM audit where dDelay=-2053867461'
```

**Comment by miaojianxin** [comment]
thank you ，that'ok
