### ISSUE TITLE
求助multi_query查询这个fields只允许传2个值吗？

### ISSUE THREAD

**Issue by fenian7788** [NLPchina/elasticsearch-sql#675]
<code>
select * from mybook where q=multimatch(query="java 高级",fields="title^10,author^10,attachment.content",type="cross_fields",operator="and") 
</code>
<br/>
被解析成
<code>
fields:[
  "title^10",
   "author^10,attachment.content"
]
</code>

**Comment by shi-yuan** [comment]
[#638](https://github.com/NLPchina/elasticsearch-sql/issues/638)
