### ISSUE TITLE
Histograms: using datetime field on arithmetic operations and group by

### ISSUE THREAD

**Issue by belerophon** [NLPchina/elasticsearch-sql#677]
Hi there,

I have a use case where I want to run a query more or less like this:

```select ("timestamp" / 1000 / 3600) as bucket, count(*) as count from some_table group by bucket order by bucket```

Basically, creating a histogram from time buckets.

My immediate problem is how to deal with the `datetime` field I have in elasticsearch. I have a "timestamp" field with the mapping set to `"timestamp":{"type":"date"}` (e.g. "2018-06-06T00:04:21.782Z"). 
This prevents me from doing things like `("timestamp" / 1000 / 3600)`.

I've seen #142, where we are advised to use script fields, but I don't think this works to let me use arithmetics on it, or even reference the new field in the group by.

Do you have any suggestions on how to solve for this use case?
Thanks!!

***

EDIT:
- I should've mentioned that I am interested in solving this with standard SQL syntax. Elastisearch already allows me to solve this with [Date Histogram Aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html) but my use case only allows me to run SQL queries like the one shown above.

**Comment by shi-yuan** [comment]
Why not to use [Date Histogram Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html), set interval to hour

**Comment by belerophon** [comment]
@shi-yuan yeah, that's the standard way to solve this with elasticsearch. However (and I should've mentioned this on the issue), I am forced to use standard SQL syntax. My application generates some standard subset of the SQL syntax and I am using it to generate queries on different backends. Elasticsearch is one of those backends.

Thoughts?

**Comment by shi-yuan** [comment]
have a look at [date histogram aggregation](https://github.com/NLPchina/elasticsearch-sql/wiki/Aggregations)
