### ISSUE TITLE
Support geographic queries

### ISSUE THREAD

**Issue by dmfenton** [NLPchina/elasticsearch-sql#68]
This is really amazing work, thanks for making it public.

I'd really love to use this plugin in some work I'm doing on http://github.com/koopjs/koop-escache, but I really need support for bounding box searches and other kinds of geographic queries.

**Comment by eliranmoyal** [comment]
+1
Starting to working on it

**Comment by robertogyn19** [comment]
Great job with the support to GeoShape Filter.
Are there any plans to add support for [Geo Polygon Filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-polygon-filter.html)?

**Comment by eliranmoyal** [comment]
Hey i'll add the rest of them today:  PolygonFilter, GeoHashCellFilter and GeoDistanceRangeFilter
