### ISSUE TITLE
elasticsearch-sql maven about v6.2.2?

### ISSUE THREAD

**Issue by kervin521** [NLPchina/elasticsearch-sql#680]
> elasticsearch-sql的v6.2.2版本在哪个maven库

> which maven  is published by v6.2.2.x

**Comment by shi-yuan** [comment]
http://mvnrepository.com/artifact/org.nlpcn/elasticsearch-sql

没有v6.2.2， @ansjsun 是不是可以发布一版新的呢？

**Comment by ansjsun** [comment]
已发布.可能索引需要两天才能看到.

**Comment by harveysun** [comment]
@ansjsun   https://mvnrepository.com/artifact/org.nlpcn/elasticsearch-sql  5.1.2.0到6.2.2.0 中间的那些版本怎么没有呢？到哪里可以引入他们呢？谢谢
