### ISSUE TITLE
关于join的代码

### ISSUE THREAD

**Issue by rjm1990** [NLPchina/elasticsearch-sql#682]
为什么代码里面没有找到join最后的实现呢
JoinRequestBuilder中的这个方法并没有体现连个结果集进行join啊
public String explain() {
        try {
            XContentBuilder firstBuilder = XContentFactory.contentBuilder(XContentType.JSON).prettyPrint();
            firstTable.getRequestBuilder().request().source().toXContent(firstBuilder, ToXContent.EMPTY_PARAMS);

            XContentBuilder secondBuilder = XContentFactory.contentBuilder(XContentType.JSON).prettyPrint();
            secondTable.getRequestBuilder().request().source().toXContent(secondBuilder, ToXContent.EMPTY_PARAMS);
            String explained = String.format(" first query:\n%s\n second query:\n%s", firstBuilder.string(), secondBuilder.string());

            return explained;
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

**Comment by shi-yuan** [comment]
[ESJoinQueryAction](https://github.com/NLPchina/elasticsearch-sql/blob/master/src/main/java/org/nlpcn/es4sql/query/join/ESJoinQueryAction.java)

**Comment by zhangzhenhua92** [comment]
请问，该插件是否支持关联查询？

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/wiki/Join
