### ISSUE TITLE
ubuntu 18.04 : Getting error while installing `elasticsearch-sql-6.3.0.0.zip`

### ISSUE THREAD

**Issue by thamaraikrishnan** [NLPchina/elasticsearch-sql#686]
ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip

**Comment by developer-devPHP** [comment]
This issue still exists, even if using mater branch

**Comment by shi-yuan** [comment]
It's OK in mater branch ！

**Comment by developer-devPHP** [comment]
@shi-yuan sorry, currently it is working for me too.
Thank you so much for quick reply and one more time sorry for wrong alert.
