### ISSUE TITLE
Support json_batch format result？

### ISSUE THREAD

**Issue by yangjiajun2014** [NLPchina/elasticsearch-sql#689]
Example:
[
{
 "filed1":"1"，
 "filed2":"2"
}，
{
 "filed1":"3"，
 "filed2":"4"
}
]
This format is frequently used in reality and more friendly than csv format.Can elasticsearch-sql support it?

**Comment by shi-yuan** [comment]
```bash
curl -X POST "localhost:9200/_sql?pretty" -H "Content-Type: application/json" -d"SELECT * FROM test LIMIT 100"
```
