### ISSUE TITLE
ip 转换的问题

### ISSUE THREAD

**Issue by bookup** [NLPchina/elasticsearch-sql#690]
能不能提供ip_to_city(ip_field),ip_To_Provine(ip_field) 方法，这种现实中经常要用到

**Comment by shi-yuan** [comment]
这个需要IP地址数据库的吧

**Comment by bookup** [comment]
可以跟ingestgeo的模式一样，用geolite免费数据库，提供一个借口https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by shi-yuan** [comment]
- Install plugin [elasticsearch-painlesswhitelist-geoip](https://github.com/shi-yuan/elasticsearch-painlesswhitelist-geoip)

- Use [Script Fields](https://github.com/NLPchina/elasticsearch-sql/wiki/Script-Fields)

**Comment by shi-yuan** [comment]
```sql
SELECT script('province', 'GeoIpProcessor.process(doc["ip_field"].value).get("region_name")'),script('city', 'GeoIpProcessor.process(doc["ip_field"].value).get("city_name")') FROM test
```
