### ISSUE TITLE
请问数组内容如何搜索

### ISSUE THREAD

**Issue by Yuanxiangz** [NLPchina/elasticsearch-sql#691]
三个doc如下，请问如何从中查到names中有Jim的结果(select * from my_index where names = IN_TERMS(Jim) 这样查询不到结果)

{
“names”:["Tom", "Jim", "Jane"]
},
{
“names”:["Jim"]
},
{
“names”:["Tom","Jane"]
}
-----------------------------------------------------------------
期望结果如下：
{
“names”:["Tom", "Jim", "Jane"]
},
{
“names”:["Jim"]
}

**Comment by shi-yuan** [comment]
是可以的，您的names的mapping是啥？

**Comment by shi-yuan** [comment]
我的是keyword

**Comment by Yuanxiangz** [comment]
非常感谢，数组字段我没有设置mapping，改成keyword后可以搜出来   多谢
