### ISSUE TITLE
How to query values=""?

### ISSUE THREAD

**Issue by yutaolife** [NLPchina/elasticsearch-sql#696]
I means that my json like following example:
{
   "values":""
   "name": "mike"
}

how to use elasticsearc-sql, query all values=""

**Comment by shi-yuan** [comment]
```sql
select * from test where values.keyword=TERMS('')
```

**Comment by yutaolife** [comment]
@shi-yuan , not working for me.....

query size is 0.

**Comment by shi-yuan** [comment]
What's your mapping ?
