### ISSUE TITLE
请教 从ES索引中先取出汇总金额最大的5个客户倒排序，然后把这5个客户按照金额、年份进行汇总按年份排序的SQL应该怎么写？

### ISSUE THREAD

**Issue by neo0820** [NLPchina/elasticsearch-sql#699]
请教这种原始SQL应该如何通过es-sql来实现呢？
原始需求是 从索引中先取出汇总金额最大的5个客户，然后把这5个客户按照金额、年份进行汇总排序。

下面的写法执行会报错，执行不了，实际应该怎么写好？
SELECT  FCustomerName,FYear,SUM(FAMOUNT)
	FROM  batsaleindex  
where FCustomerName in (
                                      SELECT  FCustomerName
	                                  FROM  batsaleindex  
		                                        GROUP BY FCustomerName
			                                       order by SUM(FAMOUNT) desc limit 5
                                         )
		GROUP BY FCustomerName,FYear
			order by FYear asc

**Comment by shi-yuan** [comment]
分两次查询吧，先查询5个客户名，再根据客户名去查

**Comment by neo0820** [comment]
@shi-yuan 谢谢，另外有嵌套查询的计划吗？应用场景比较广泛。

**Comment by shi-yuan** [comment]
不好意思哈，目前可能没有的
