### ISSUE TITLE
Aggregation for "group by" has something wrong when the group by field is Chinese characters

### ISSUE THREAD

**Issue by dengkane** [NLPchina/elasticsearch-sql#70]
E.g. have an index and the columns are member_name and city, and the city column is Chinese character, such as '北京','上海',etc.

select count(*) from indexName group by city

will return 

北    2
京    2
上    5
海    5

I want this result

北京    2
上海    5

How can I get the result I want?

Thank you.

**Comment by omershelef** [comment]
Is it possible that the standard analyzer tokenize chinese by characte? If this is the case, you must group by field which is not analyzed. The group by works by terms aggregation.

**Comment by ansjsun** [comment]
对于需要聚合查询的字段最好用keyword方式，也就是不分词的方式。
