### ISSUE TITLE
Terms里面的Order选项是不是比较简单只有asc和desc，如果Terms向按照另外一个字段进行排序呢？

### ISSUE THREAD

**Issue by neo0820** [NLPchina/elasticsearch-sql#700]
正常单一个聚合排序可以写成
SELECT  SUM(FAMOUNT) 
	FROM  batsaleindex  
		GROUP BY TERMS(field='FCustomerName', size='5', alias='FCustomerName')
                 order by SUM(FAMOUNT)  desc

如果把排序放入到TERMS里面就只能写成根据Terms字段（FCustomerName）的asc或者desc了，不能按照SUM(FAMOUNT) 进行倒排序。
SELECT  SUM(FAMOUNT) 
	FROM  batsaleindex  
		GROUP BY TERMS(field='FCustomerName', size='5', alias='FCustomerName', order='asc')

如果单一一个 TERMS可以按照第一种写法基本就满足了。如果两个 TERMS里面都要按照不同的字段进行过滤，是不是就有扩充TERMS order选项的必要了？

看见源码这里关于Terms的Order目前是没有其他选项的。
![qq 20180712110725](https://user-images.githubusercontent.com/39484553/42610368-cb5d3294-85c3-11e8-8731-03fadf5fd24a.jpg)

**Comment by shi-yuan** [comment]
说得对，这一块是不支持的，可以改改，order可以支持写json数组

**Comment by neo0820** [comment]
@shi-yuan 非常感谢，我改下试试。

**Comment by shi-yuan** [comment]
```sql
SELECT SUM(FAMOUNT)
FROM batsaleindex
GROUP BY TERMS(field='FCustomerName', size='5', alias='FCustomerName', order='[{ "_count":"desc"},{ "_key":"asc"}]')
```
