### ISSUE TITLE
数据展现工具调取elasticsearch-sql  jdbc的时候，Driver应该填什么呢？

### ISSUE THREAD

**Issue by neo0820** [NLPchina/elasticsearch-sql#701]
如图，有个数据展现工具，需要填入对应的Driver,
![222222222222222](https://user-images.githubusercontent.com/39484553/42611371-5e3eddb6-85c8-11e8-8f31-93126c0d4e0e.jpg)

试过填写com.alibaba.druid.pool.DruidDataSource，不行
![333333333](https://user-images.githubusercontent.com/39484553/42611549-4d2ab76a-85c9-11e8-9b23-02e41cbfd343.jpg)

填写com.mysql.jdbc.Driver也不行
![44444444444444](https://user-images.githubusercontent.com/39484553/42611599-7a79ebdc-85c9-11e8-97e4-8d2dd094ac56.jpg)

用DbVisualizer查找对应的Driver发现如下
![11111111111111111](https://user-images.githubusercontent.com/39484553/42618435-8bc37ffc-85e7-11e8-81e2-fb19eb029cc1.jpg)

**Comment by shi-yuan** [comment]
您可以参考示例代码：
https://github.com/NLPchina/elasticsearch-sql/blob/master/src/test/java/org/nlpcn/es4sql/JDBCTests.java

**Comment by hexiaobing5880** [comment]
@neo0820 因最新版的ES内置了SQL功能，但是SQL特性并不是很完全。所以采用此插件，但是遇见了和你一样的问题，想对报表软件配置ES数据源，结果发现只能配置com.alibaba.druid.mock.MockDriver，虽然连接成功了，但是并没有通过这个插件进行解析SQL。请问你解决了吗？

**Comment by neo0820** [comment]
@hexiaobing5880 
自己先写了个JDBC Driver暂时先用有需要再完善，https://github.com/neo0820/elasticsearch-sql-JDBCDriver 

@shi-yuan 
从C#转过来的，没做过java 参考一下网上别人做的JDBC，Driver不知道这样写是否合理。写了一个test能连通。

**Comment by hexiaobing5880** [comment]
@neo0820 十分感谢，通过你提供的思路，试着应用到ES6.3.0上，结果发现可以应用。不过，ES读取大数据量的数据时，有些缓慢，请问你有遇见过此类问题吗。

**Comment by shi-yuan** [comment]
数据量大的话，用scroll去查

**Comment by fanjun1980** [comment]
@hexiaobing5880  使用DbVisualizer需要加入哪些jar，我这里加了Driver还是报各种找不到类。
