### ISSUE TITLE
是否还会支持6.3.1

### ISSUE THREAD

**Issue by stopit** [NLPchina/elasticsearch-sql#705]
6.31.版本的x-pack开放sql之后，elasticsearch-sql是否还会继续支持后续版本

**Comment by shi-yuan** [comment]
会维护的，主要是修复一些bug和一些小功能的添加。也很期待es官方的sql功能越来越健全

**Comment by shi-yuan** [comment]
最新版本已发布，谢谢

**Comment by stopit** [comment]
感谢！  es里面jdbc还是要收费，支持项目继续发展！
