### ISSUE TITLE
多字段聚合问题

### ISSUE THREAD

**Issue by wenfang6** [NLPchina/elasticsearch-sql#707]
多字段聚合时，当es中的document出现field1的字段为null的时候，该条件还会往下聚合吗？（即使filed2字段有值）

**Comment by shi-yuan** [comment]
es聚会的话，不会的。聚合的时候，可以指定[missing](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_missing_value_12)或者索引的时候指定[null_value](https://www.elastic.co/guide/en/elasticsearch/reference/current/null-value.html)
