### ISSUE TITLE
elasticsearch集群环境下是否需要每个节点都安装sql插件？ 

### ISSUE THREAD

**Issue by Birdflying1005** [NLPchina/elasticsearch-sql#708]
之前有问题问过， 但是没有看到确切的回答， 只是说可以只装一个site-server.

**Comment by Birdflying1005** [comment]
可否给一个确切的回答，是不是需要在每一个节点下安装sql插件？

**Comment by shi-yuan** [comment]
建议是都安装，不过也可以只安装部分节点，安装了的节点，客户端就可以连接访问sql插件提供的功能

**Comment by Birdflying1005** [comment]
@shi-yuan 谢谢回答。还想多问一些， 我是不是需要明确的制定访问的url , 还是说服务端会自动做负载？

**Comment by shi-yuan** [comment]
插件本身是不会做的

**Comment by Birdflying1005** [comment]
现在 es 6.3  已经开放了 sql 的功能， 我们这项目还会继续做下去吗？

**Comment by Birdflying1005** [comment]
@shi-yuan 另外一个问题，用这个插件对标es的rest 接口， 性能有多少的损耗 ？ 我们有没有测试和数据？

**Comment by shi-yuan** [comment]
首先当然希望官方功能越来越完善，这个项目近期的话，还是会做同步升级和一个bug的修复的；
这个插件做的只是将sql转成es dsl，至于性能，不好意思哈，我这边没有做过压测， :sweat:

**Comment by Birdflying1005** [comment]
@shi-yuan  我调研了一下最新的6.3.2的 xpack/sql 的使用。 发现有2个问题很难受
1. 没有返回总记录数目
2.cursor是单向游标，只能用一次，如果跳页选择的化， 需要在应用端连续的自己处理cursor 移动， 如果我先用translate把sql转换成为dsl， 又需要2次调用～  非常不方便

所以， 我觉得还是你的这个插件用起来比较舒服

**Comment by shi-yuan** [comment]
可以的，但是有的sql是不行的，比如说：show index

**Comment by Birdflying1005** [comment]
@shi-yuan 谢谢你的回答， 那我怎样使用？ 有没有代码例子？

**Comment by shi-yuan** [comment]
```java
public String explain(String sql) throws Exception {
    SearchDao searchDao = new SearchDao(null);
    SqlElasticRequestBuilder requestBuilder = searchDao.explain(sql).explain();
    return requestBuilder.explain();
}
```
