### ISSUE TITLE
how  to get results when i use elasticsearch-sql as my local APIs?

### ISSUE THREAD

**Issue by mlc0202** [NLPchina/elasticsearch-sql#71]
firstly, i am awesome when i find elasticsearch-sql ,it is a very greatful tool,thanks to authors!
now ,when i import it as my local library,i invoke SearchDao.class,but find result is number insteand of the result that include the index datas,so,in order to get the index datas ,what is i need to do or which method i can invoke?

**Comment by omershelef** [comment]
Currently there is no better way then to call directly the REST api. if you want use elasticsearch-sql as a library instead of elasticsearch plugin, see issue #58

**Comment by mlc0202** [comment]
thanks,it settle up my problem
