### ISSUE TITLE
联表查询 or 条件不生效 ，查出来效果和 and 条件结果一致，求大神帮忙解决

### ISSUE THREAD

**Issue by songrd** [NLPchina/elasticsearch-sql#712]
select news.news_title,news.news_id,news_tag.tag_name from 
jiwei_search_news_tag/news_tag news_tag join jiwei_search_news/news news 
on news.news_id = news_tag.news_id
where news.news_title like "%%iphone%%" or news_tag.tag_name = "股票"

**Comment by shi-yuan** [comment]
针对join，可以考虑：
1、字段融合到一张表
2、nested，parent/child，terms-lookup
3、先查询，再根据查询结果聚合
4、MultiSearchRequest两个查询，自己做结果合并（具体到合并逻辑实现）
