### ISSUE TITLE
求助sql中like中文，无法查询出结果

### ISSUE THREAD

**Issue by songrd** [NLPchina/elasticsearch-sql#716]
select news_id,news_title,published_time,search_tags  from jiwei_search_news where news_title like '%三星%' or search_tags like '%iphone%' order by news_id desc limit 10

curl 'http://xxx/_sql?sql=select news_id,news_title,published_time,search_tags  from jiwei_search_news where news_title like '%三星%' or  search_tags like '%iphone%' order by news_id desc limit 10'

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"invalid version format: NEWS_ID,NEWS_TITLE,PUBLISHED_TIME,SEARCH_TAGS  FROM JIWEI_SEARCH_NEWS WHERE NEWS_TITLE LIKE %Ä¸Æ% OR  SEARCH_TAGS LIKE %IPHONE% ORDER BY NEWS_ID DESC LIMIT 10 HTTP/1.1"}],"type":"illegal_argument_exception","reason":"invalid version format: NEWS_ID,NEWS_TITLE,PUBLISHED_TIME,SEARCH_TAGS  FROM JIWEI_SEARCH_NEWS WHERE NEWS_TITLE LIKE %Ä¸Æ% OR  SEARCH_TAGS LIKE %IPHONE% ORDER BY NEWS_ID DESC LIMIT 10 HTTP/1.1"},"status":400}

看到中文乱码，这个怎么破呀？

**Comment by songrd** [comment]
explain 后的结果
{
	"from": 0,
	"size": 10,
	"query": {
		"bool": {
			"filter": [
				{
					"bool": {
						"must": [
							{
								"bool": {
									"should": [
										{
											"wildcard": {
												"news_title": {
													"wildcard": "**三星**",
													"boost": 1
												}
											}
										},
										{
											"wildcard": {
												"search_tags": {
													"wildcard": "*iphone*",
													"boost": 1
												}
											}
										}
									],
									"adjust_pure_negative": true,
									"boost": 1
								}
							}
						],
						"adjust_pure_negative": true,
						"boost": 1
					}
				}
			],
			"adjust_pure_negative": true,
			"boost": 1
		}
	},
	"_source": {
		"includes": [
			"news_id",
			"news_title",
			"published_time",
			"search_tags"
		],
		"excludes": []
	},
	"sort": [
		{
			"published_time": {
				"order": "desc"
			}
		}
	]
}

**Comment by shi-yuan** [comment]
没有乱码的：
![1](https://user-images.githubusercontent.com/8057153/43046588-a6858736-8dfd-11e8-90e7-c69f433e1097.png)

**Comment by songrd** [comment]
@shi-yuan 是啊，我看也没有乱码，但是中文查不出结果，是我少了什么东西吗？

**Comment by shi-yuan** [comment]
中文查不出来？如何查的呢？
