### ISSUE TITLE
请问这么怎么写sql

### ISSUE THREAD

**Issue by hw1992** [NLPchina/elasticsearch-sql#729]
GET search_index_v1/_search
{
  "query": {
    "multi_match": {
      "query": "s",
      "fields": ["keyword.FPY","keyword","keyword.IKS"]
    }
  }
}

数据是这样的
{
        "_index": "search_index_v1",
        "_type": "suggest",
        "_id": "N-h6C2UBlf6bqwuiOg5I",
        "_score": 6.848856,
        "_source": {
          "order": 0,
          "cate": 1,
          "count": 1,
          "desc": "huasbdashjb",
          "id": "7920015ac69f47e5a2a1cc0911847fe6",
          "keyword": "adssa",
          "site": "420102"
        }
      }

**Comment by shi-yuan** [comment]
```sql
SELECT * FROM search_index_v1 WHERE q=multimatch(query='s',fields='keyword.FPY,keyword,keyword.IKS')
```
