### ISSUE TITLE
使用date_histogram查询时，time_zone参数不支持正时区

### ISSUE THREAD

**Issue by newidingh** [NLPchina/elasticsearch-sql#731]
查询字符串如下：
`localhost:9200/_sql?sql=SELECT count(*) FROM test WHERE time BETWEEN '2018-08-02T00:00:00' AND '2018-08-02T23:59:59' GROUP BY date_histogram(field='time', 'interval'='1h', 'alias'='query_by_hour', 'time_zone'='+08:00')`
报错：
`[2018-08-13T17:37:43,845][WARN ][r.suppressed             ] path: /_sql, params: {sql=SELECT count(*) FROM waf*_waf_server_nginx WHERE time BETWEEN '2018-08-02T00:00:00' AND '2018-08-02T23:59:59' GROUP BY date_histogram(field='time', 'interval'='1h', 'alias'='query_by_hour', 'time_zone'=' 08:00')}
java.time.DateTimeException: Invalid ID for ZoneOffset, plus/minus not found when expected:  08:00
        at java.time.ZoneOffset.of(ZoneOffset.java:245) ~[?:1.8.0_172]
        at org.nlpcn.es4sql.query.maker.AggMaker.dateHistogram(AggMaker.java:488) ~[?:?]
`
经查询，JAVA只支持以下时区格式：
`Z - for UTC
+h
+hh
+hh:mm
-hh:mm
+hhmm
-hhmm
+hh:mm:ss
-hh:mm:ss
+hhmmss
-hhmmss`
由此可得，如果'+'被转义成空格，则不能查询正时区，需要判断并取消这里的转义。
麻烦开发者完善程序，感谢！

**Comment by shi-yuan** [comment]
我觉得，如果用querystring传参，client端应该做encode的
