### ISSUE TITLE
and条件如何做到精确匹配呢

### ISSUE THREAD

**Issue by xinlan** [NLPchina/elasticsearch-sql#735]
如 and='中文'
可以查出 and='中文A' 来

要求只查询 '中文' 的结果

**Comment by shi-yuan** [comment]
```sql
SELECT * FROM index WHERE a=TERMS('中文')
```

**Comment by xinlan** [comment]
SELECT * FROM index WHERE a=TERMS('中文')   还是查不出数据，

SELECT * FROM index WHERE a=TERMS('中') 
和
SELECT * FROM index WHERE a=TERMS('文') 都可以查出‘中文’数据 
是不是给分词了？如果设置查询的时候不分词?

**Comment by shi-yuan** [comment]
分词了吧，默认是standard的
