### ISSUE TITLE
Field names with a ' ' (space) character in them don't seem to work in the WHERE clause

### ISSUE THREAD

**Issue by zeigernz** [NLPchina/elasticsearch-sql#736]
Plugin version: 6.3.2.0
Elasticsearch version: 6.3.2

It looks like when there is a ' ' (space) character in the field name in the where clause, it doesn't match any document.

Test:
Step 1. Index a document (this will automatically create an index as well)
```
curl -X PUT \
  http://localhost:9200/foobarbaz/quux/12345 \
  -H 'Content-Type: application/json' \
  -d '{
	"name": "foo",
	"last name": "bar"
}'
```
Step 2. Query documents with the query: 

> select * from foobarbaz where \`last name\` = 'bar'

```
curl -X GET \
  'http://localhost:9200/_sql?sql=select%20%2A%20from%20foobarbaz%20where%20`last%20name`%20=%20%27bar%27'
```

Step 2 should return 1 hit (the document that we indexed in step 1). But it doesn't.

**Comment by shi-yuan** [comment]
````
http://localhost:9200/_sql?sql=SELECT%20*%20FROM%20test%20WHERE%20%5B'last%20name'%5D%3D'bar'
````

**Comment by zeigernz** [comment]
Thank you. That resolves the problem.

How does this test pass though?
https://github.com/NLPchina/elasticsearch-sql/blob/38ad264f2838a7d3c92a41ceeaeb5cd8ce50adb3/src/test/java/org/nlpcn/es4sql/QueryTest.java#L65

It (and other similar tests) should be updated and some documentation added around this.

**Comment by shi-yuan** [comment]
Thanks!
