### ISSUE TITLE
jdbc读取ResultSetMetaData的列名为0

### ISSUE THREAD

**Issue by FeiLiu0519** [NLPchina/elasticsearch-sql#738]
`ResultSetMetaData rsmd=rs.getMetaData();

getColumCount()`

但是调试时，ResultSetMetaData 里有两个columns 第一个有列名存在，第二个没有
@shi-yuan 

![1](https://user-images.githubusercontent.com/42425845/44184782-2b87c900-a143-11e8-8ee7-52258479267b.jpg)

![2](https://user-images.githubusercontent.com/42425845/44184765-20cd3400-a143-11e8-9d18-b7d47f4f7bed.jpg)
![3](https://user-images.githubusercontent.com/42425845/44184787-34789a80-a143-11e8-881e-9443e63a3c0c.jpg)

**Comment by FeiLiu0519** [comment]
![1](https://user-images.githubusercontent.com/42425845/44184782-2b87c900-a143-11e8-8ee7-52258479267b.jpg)

![2](https://user-images.githubusercontent.com/42425845/44184765-20cd3400-a143-11e8-9d18-b7d47f4f7bed.jpg)
![3](https://user-images.githubusercontent.com/42425845/44184787-34789a80-a143-11e8-881e-9443e63a3c0c.jpg)

**Comment by shi-yuan** [comment]
问题解决了？

**Comment by FeiLiu0519** [comment]
算是吧。我的es版本是2.4.5
然后下载了源码跟踪调试  发现继承阿里连接的子类多了一个column属性  后来我把源码改了  重新封了下包🌚
