### ISSUE TITLE
ES中的关键字作为搜索条件，应该怎么转义呢？

### ISSUE THREAD

**Issue by huansoo** [NLPchina/elasticsearch-sql#740]
现在有如下sql:
SELECT count(*) FROM log4a-20180817/comptroller  WHERE  function = TERM("函数test63")，
其中function是imc_client_comptroller表中的一个字段名称，如果使用转义·function·查询，语法不报错了，但是结果不对，请教下如果where条件中如果包含关键字应该怎么转义才能查询到结果呢?

**Comment by shi-yuan** [comment]
```sql
SELECT count(*) FROM log4a-20180817/comptroller WHERE ['function'] = TERM("函数test63")
```
