### ISSUE TITLE
{"error":"Incorrect HTTP method for uri [/_plugin/sql] and method [GET], allowed: [POST]","status":405}

### ISSUE THREAD

**Issue by fengme** [NLPchina/elasticsearch-sql#741]
通过浏览器chrome打开URL时出错：
http://192.168.1.**:9200/_plugin/sql

就像这样报题目的错误，请教正确的打开UI的姿势

**Comment by shi-yuan** [comment]
请问您用的版本是？

**Comment by fengme** [comment]
6.2.3

**Comment by fengme** [comment]
ELK全套的6.2.3
我想在这个环节下体验下你们的UI

**Comment by fengme** [comment]
http://essql.nlpcn.org/

就像这里的UI

**Comment by shi-yuan** [comment]
[Elasticsearch 5.x/6.x](https://github.com/NLPchina/elasticsearch-sql/wiki/Installation-Guide#elasticsearch-5x6x)

**Comment by fengme** [comment]
Error:"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /_sql</pre>\n</body>\n</html>\n"

杯具在UI上执行SQL时提示这个错误，请教该怎么办？
![image](https://user-images.githubusercontent.com/15841387/44340738-557d1a80-a4b8-11e8-94c2-08aa08419546.png)

**Comment by shi-yuan** [comment]
配置了http.cors.enabled和http.cors.allow-origin吗？

**Comment by fengnex** [comment]
记得配置了
因为访问_sql、_sql/_explain是正常的，所以才想看看UI

**Comment by fengnex** [comment]
就是指定正确的SQL看查询结果以及翻译了的painless正常，但是无法通过UI提交执行SQL

**Comment by shi-yuan** [comment]
应该不会的吧？后台有错误日志吗？或者前端console的日志呢？用的哪个包？

**Comment by fengnex** [comment]
日志要等等，我现在拿不到日志，到时候会我看看
用的包是从首页上指定的链接下载的：
https://github.com/NLPchina/elasticsearch-sql/releases/download/5.4.1.0/es-sql-site-standalone.zip

**Comment by shi-yuan** [comment]
1.配置了http.cors.enabled和http.cors.allow-origin
2.地址填写正确
![1](https://user-images.githubusercontent.com/8057153/44456853-491dcc80-a634-11e8-9913-fc55d573601c.png)
