### ISSUE TITLE
如何实现部分字段更新

### ISSUE THREAD

**Issue by sxsboat** [NLPchina/elasticsearch-sql#744]
想添加一个"点击次数“字段，请教如何实现。
没找到update语法，需要每次删除文档再重建么？

以下sql不可用，求实现
update table1 set count = 99 where _id = 1

**Comment by shi-yuan** [comment]
update不支持的噢，您可以看看es的官方[Update API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html)
