### ISSUE TITLE
how to retrieve Query ResultSet Metadata?

### ISSUE THREAD

**Issue by meijies** [NLPchina/elasticsearch-sql#749]
if I get ResultSet of any query, how I can know the type(such as text and so on) of columns returned,  I have dived into InternalSearchHit, but i can't found related information.

**Comment by meijies** [comment]
I think I can reference to https://github.com/Anchormen/sql4es. more completable implemete of jdbc interface.

**Comment by shi-yuan** [comment]
https://github.com/stopit/elasticsearch-sql/commit/651ffa2e340aaacd05248cef32f035804c161b2c
