### ISSUE TITLE
在使用like的时候如下

### ISSUE THREAD

**Issue by danchaobing** [NLPchina/elasticsearch-sql#750]
sql语句：
_sql?sql=select * from movies/movie where title like '电影%'

异常信息
[WARN ][r.suppressed             ] path: /_sql, params: {sql=select * from movies/movie where title like '电影%27}
com.alibaba.druid.sql.parser.ParserException: unclosed str

**Comment by shi-yuan** [comment]
哪个版本呢，请问？试了试，没啥问题呢
````
curl -X POST "localhost:9200/_sql/_explain" -H "Content-Type: application/json" -d"select * from movies/movie where title like '电影%'"
````

**Comment by danchaobing** [comment]
版本是6.3.2，看着像是%后面的单引号被转义了

**Comment by danchaobing** [comment]
另外想问下，在java中怎么和elasticsearch集成使用

**Comment by danchaobing** [comment]
哈，原来是打成jar包就可以了
