### ISSUE TITLE
JDBC中使用ResultSet获取MetaData对象中没有列数等信息

### ISSUE THREAD

**Issue by stopit** [NLPchina/elasticsearch-sql#751]
metaData.getColumnCount() 调用无法获取正常的列数信息。

**Comment by shi-yuan** [comment]
谢谢！不过merge的时候有冲突哦。。。

**Comment by stopit** [comment]
@shi-yuan     能具体展示下冲突的具体内容么，我检查一下~~

**Comment by shi-yuan** [comment]
冲突已解决，已经merge了，谢谢了哈

**Comment by stopit** [comment]
谢谢你发起了这么好的项目，我们已经在好几个生产系统上使用了。xpack的jdbc貌似依然收费，还是离不开elasticsearch-sql  ~~

**Comment by shi-yuan** [comment]
谢谢！这个项目不是我发起的哈，我也仅仅是尽自己的绵薄之力。
