### ISSUE TITLE
查询不到结果

### ISSUE THREAD

**Issue by deadjoker** [NLPchina/elasticsearch-sql#753]
web使用的是elasticsearch-site，es版本5.6.1。终于把验证的问题解决了，但是无法查询到结果，显示如下：
![image](https://user-images.githubusercontent.com/1702258/44932608-c49c1e00-ad98-11e8-87a9-719fe1e9b395.png)
请问这是什么问题，怎么才能解决呢

**Comment by shi-yuan** [comment]
测试explain，没啥问题呢。elasticsearch-site用的5.x，es用的5.6.6

![1](https://user-images.githubusercontent.com/8057153/44952927-e7742280-aebd-11e8-9e13-9f021841d9e3.png)

**Comment by deadjoker** [comment]
不知道是什么问题，虽然没报错，但就是显示不出结果，explain和search都会返回图里的结果

**Comment by deadjoker** [comment]
请问results里边报的是什么意思，因为整体没有报错，所以只能从返回的数据来查看下是什么问题了

**Comment by deadjoker** [comment]
想确认下，右上角的地址，我写的是 http://10.211.121.44:8080/?username=elastic&password=abcdefg&base_uri=http://10.211.121.44:9200 这个是正确的嘛

**Comment by deadjoker** [comment]
搞定了，页面终于显示正常了 谢谢

**Comment by deadjoker** [comment]
页面显示正常了，要怎样才能显示结果而不是数量呢？
![image](https://user-images.githubusercontent.com/1702258/46077259-cc49b980-c1c2-11e8-9fb8-a56b22d683f8.png)

**Comment by shi-yuan** [comment]
点击Search按钮，就可以显示结果了吧

**Comment by deadjoker** [comment]
不好意思再问下，search显示报错，这个是我在哪里配置错了
![image](https://user-images.githubusercontent.com/1702258/46121974-f0e87480-c248-11e8-8594-018c5974b36e.png)

**Comment by shi-yuan** [comment]
9300连不了？还是权限验证？

**Comment by deadjoker** [comment]
解决了，是配置的问题，改过就能显示结果了 谢谢
