### ISSUE TITLE
ES SQL 是否支持cross cluster search（跨集群搜索）

### ISSUE THREAD

**Issue by matthew0701** [NLPchina/elasticsearch-sql#754]
开发者：
       您们好！
       请问elasticsearch-sql 什么时候能够支持cross cluster search（跨集群搜索）？
       使用场景是这样的：
              我们线上有三个集群分布在三个机房。机房内机器的日志就近接入。因此需要用到ES的CCS功能。

**Comment by matthew0701** [comment]
试了下，支持SELECT * FROM cluster_one:twitter,twitter这种模式。

请问：
比如我有三个集群。cluster_one, cluster_two, cluster_three。我想查出分布在这三个集群上的同一个命名的索引数据，貌似不支持SELECT * FROM *:twitter,twitter 这种通配符写法。这个如何实现？

**Comment by shi-yuan** [comment]
通配符的，本身就不支持的吧

**Comment by matthew0701** [comment]
试了下，支持通配符。但是不支持通配符开头。

三个集群。cluster_one, cluster_two, cluster_three
支持SELECT * FROM cluster_*:twitter
不支持 支持SELECT * FROM *:twitter

**Comment by shi-yuan** [comment]
不好意思哈，确实支持的：
```sql
SELECT * FROM ['*:twitter']
```
