### ISSUE TITLE
not found  PreBuiltXPackTransportClient this version 6.3.2

### ISSUE THREAD

**Issue by SmileTower** [NLPchina/elasticsearch-sql#758]
![1](https://user-images.githubusercontent.com/17945169/45284993-88915780-b514-11e8-90c9-ddc9cbd9c66a.png)

**Comment by shi-yuan** [comment]
What's wrong ? mine is ok

![1](https://user-images.githubusercontent.com/8057153/45398600-7419a000-b677-11e8-8e63-ffa4026f5b85.png)
