### ISSUE TITLE
Support wildcard in index name

### ISSUE THREAD

**Issue by raviv** [NLPchina/elasticsearch-sql#76]
Would be very useful for daily indexes, like Logstash and Marvel does, e.g. "logstash-2015.08.01"
Thanks :)

**Comment by omershelef** [comment]
Wildcard is already supported please make us know if you having any problems

**Comment by raviv** [comment]
Hi Omer,

You're right. There was a different problem in my query.

Thanks,
Raviv.

**Comment by oryband** [comment]
:+1: @motidavid @ofir-petrushka
