### ISSUE TITLE
关于两张表关联的查询策略及效率

### ISSUE THREAD

**Issue by frontgoo** [NLPchina/elasticsearch-sql#762]
HashJoinElasticExecutor 中对于两张表关联的策略，在where 条件 在 firstTable 不在secondTable中时，会最多默认查出secondTable10000笔的数据，一个问题是数据查询不准确，另一个是效率不是最优

**Comment by shi-yuan** [comment]
是的。

针对join，可能实现：
1、不走join，把字段都融合到一个index
2、走nested，parent/child，terms-lookup
3、先查询，再根据查询结果聚合
4、MultiSearchRequest两个查询，自己做结果合并

个人建议还是尽量不要不走join，把字段都融合到一个index

**Comment by frontgoo** [comment]
> 个人建议还是尽量不要走join，把字段都融合到一个index

嗯嗯 有调研过类似的方案，一种是所有的文档汇总到同一个INDEX，一种是建立多个索引。
但是文档都放在一起也会带来一些问题，查询到时方便了，但是文档更新引起的索引重建就有点得不偿失了【可能只是一小块数据的变化】。我们目前的文档设计比较大，也在纠结两个方案选哪种。

**Comment by shi-yuan** [comment]
嗯。另外减少es的数据量吧，仅仅放要用于搜索的几个关键字段即可

**Comment by frontgoo** [comment]
我们的场景是要用es基于文档字段做些规则，字段还是要保证多一点，不然规则调整的灵活性会差一点

**Comment by frontgoo** [comment]
> 好吧。。。 😓

我们找到了新的方案：
图数据库+ES, 关系类的交给图数据库，单维度的数据匹配交给es

**Comment by shi-yuan** [comment]
neo4j + es ?
