### ISSUE TITLE
find interface  ，class expected

### ISSUE THREAD

**Issue by QingMingXia** [NLPchina/elasticsearch-sql#765]
es2升级到es5.4.2 使用elasticsearch-sql执行到下图报错 find interface class expected
![findinterfaceexpectedclass](https://user-images.githubusercontent.com/24218234/45586433-edd8b480-b929-11e8-9013-0ba4b3f4d248.png)

**Comment by QingMingXia** [comment]
请问楼主，这个错误是包冲突了吗，试了很多种仍然无法解决

**Comment by shi-yuan** [comment]
sql在es2里没问题，在es5.4.2里出错？

**Comment by QingMingXia** [comment]
是的，升级的时候报错 这个是我的新的依赖
![dependency](https://user-images.githubusercontent.com/24218234/45586532-655b1380-b92b-11e8-9ad4-65e225bfe8c9.png)

**Comment by QingMingXia** [comment]
结果都取出来了，就是获取结果的时候解析出错

**Comment by shi-yuan** [comment]
请问这条sql，通过rest接口调的话，能正常explain吗，能search出结果吗？
http://localhost:9200/_sql?sql=xxxxx
http://localhost:9200/_sql/_explain?sql=xxxxx

**Comment by QingMingXia** [comment]
elasticsearch-sql 5.1.2.0 报java.lang.IncompatibleClassChangeError: Found class org.elasticsearch.search.SearchHits, but interface was expected ；  5.5.2是报上面的那个错误；其他版本也不可用
![1](https://user-images.githubusercontent.com/24218234/45586578-15308100-b92c-11e8-994b-a44eb3f53619.png)

**Comment by QingMingXia** [comment]
es-sql 5.5.2.0查询非聚合操作是可以的，聚合操作不了，5.1.2.0的聚合操作可以，但是普通的查询单个字段就不行

**Comment by shi-yuan** [comment]
请问explain可以吗？

**Comment by QingMingXia** [comment]
我目前无法访问我司的服务器，等礼拜一我再发一下；用的阿里的druid

**Comment by QingMingXia** [comment]
我调试的，sum的值都查出来了，就是在解析的时候，解析出错

**Comment by QingMingXia** [comment]
目前还没有找到能够兼容5.4.2的es-sql 试了很多版本
![20180915213912](https://user-images.githubusercontent.com/24218234/45586857-d270a800-b92f-11e8-9a68-279b31fe09d5.png)
