### ISSUE TITLE
failed to explain sql to elasticsearch query  dsl

### ISSUE THREAD

**Issue by hello-wn** [NLPchina/elasticsearch-sql#766]
请问一下各位大神，官方文档描述 explain可以把sql转化为es的dsl，但是实际操作，发现explain返回了一些奇怪的json数据。

get /
http://localhost:9200/_sql/_explain?sql=SELECT * FROM order_info o JOIN order_item i ON o.order_id = i.order_id

返回：
HashJoin  first query:
{
  "from" : 0,
  "size" : 200,
  "ext" : { }
}
 second query:
{
  "from" : 0,
  "size" : 200,
  "ext" : { }
}

请问返回的json数据什么意思，如何才能将sql转为dsl呢？
es版本是5.1.2。
非常感谢～～～

**Comment by hello-wn** [comment]
es版本：5.1.2

**Comment by QingMingXia** [comment]
要是查询数据 http://localhost:9200/_sql?sql=SELECT * FROM order_info o JOIN order_item i ON o.order_id = i.order_id  就行了

**Comment by shi-yuan** [comment]
join是分两次查询实现的噢

**Comment by hello-wn** [comment]
非常感谢回复。

所以，join没办法使用explain转化为dsl吗？

如果是分两次查询，那每次查询的dsl为啥explain也不显示呢？

**Comment by shi-yuan** [comment]
先scroll查询order_info：
```json
{"from":0,"size":10000}
```

再scroll查询order_item：
```json
{"from":0,"size":200}
```

之后做的结果合并
