### ISSUE TITLE
使用jdbc连接es时，es的用户密码认证该怎么做 version6.2.4

### ISSUE THREAD

**Issue by jeremeyjiang** [NLPchina/elasticsearch-sql#769]
使用了 https://github.com/NLPchina/elasticsearch-sql/issues/703 这套方式
显示 None of the configured nodes are available 
根绝https://github.com/NLPchina/elasticsearch-sql/commit/01f6d3c55b4f9d1c229b1cbf69f994115f0bb818 这里 引入x-pack-transport做了相应修改 
结果不变 

elasticsearch.yml 存在如下配置
xpack.security.transport.ssl.enabled: true
xpack.security.enabled: true

http.cors.enabled: true
http.cors.allow-origin: "*"
bootstrap.memory_lock: false
bootstrap.system_call_filter: false
thread_pool.bulk.queue_size: 200

**Comment by shi-yuan** [comment]
用的6.2.4.4？代码这样的？
````
Properties properties = new Properties();
properties.put(PROP_URL, "jdbc:elasticsearch://127.0.0.1:9300/test");
properties.put(PROP_CONNECTIONPROPERTIES, "client.transport.ignore_cluster_name=true;xpack.security.user=elastic:5laftq1NilavFTibKOaZ");
DruidDataSource dds = (DruidDataSource) ElasticSearchDruidDataSourceFactory.createDataSource(properties);
Connection connection = dds.getConnection();
PreparedStatement ps = connection.prepareStatement("SELECT * from  test");
ResultSet resultSet = ps.executeQuery();
while (resultSet.next()) {
    System.out.println(resultSet.getString("name"));
}
ps.close();
connection.close();
dds.close();
````

**Comment by shi-yuan** [comment]
9300连接不上？

**Comment by jeremeyjiang** [comment]
就是9300连不上 有点奇怪
kibana上看了一下   GET _nodes/hot_threads
结果如下
::: {node-1}{7dx7XSQHTGuvfhn7Lo_SgQ}{RvSja3tDQNySf_0ho24eqA}{192.168.5.109}{192.168.5.109:9300}{ml.machine_memory=4151914496, ml.max_open_jobs=20, ml.enabled=true}
   Hot threads at 2018-09-25T01:58:01.634Z, interval=500ms, busiestThreads=3, ignoreIdleThreads=true:

**Comment by shi-yuan** [comment]
只能先测通TransportClient了。。。
