### ISSUE TITLE
在jdbc中使用scroll如何翻页？

### ISSUE THREAD

**Issue by luofeng1994** [NLPchina/elasticsearch-sql#776]
想在jdbc中连接es并返回所有查询结果（上万条），使用如下代码
Properties properties = new Properties();
properties.put("url", "jdbc:elasticsearch://127.0.0.1:9300/test_index");
try (DruidDataSource dds = (DruidDataSource) ElasticSearchDruidDataSourceFactory.createDataSource(properties);
    ResultSet resultSet = dds.getConnection().prepareStatement("SELECT /*! USE_SCROLL(100,30000)*/ lastname, age, gender FROM test_index WHERE lastname='Heath'").executeQuery()) {
    while (resultSet.next()) {
        System.out.println(resultSet.getString("lastname") + "," + resultSet.getInt("age") + "," + resultSet.getString("gender"));
    }
}

只能返回100条数据，请问如何在jdbc连接下进行翻页？

**Comment by luofeng1994** [comment]
@allwefantasy

**Comment by luofeng1994** [comment]
@shi-yuan

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/issues/613
