### ISSUE TITLE
How to do case insensitive search on fields?

### ISSUE THREAD

**Issue by thamaraikrishnan** [NLPchina/elasticsearch-sql#778]
Ex:
SELECT firstname , balance FROM accounts where firstname.keyword like '%ram%'

It should provide data like below:
RAMAN,
rAMkumar,
ramu

But it gives data like below:
ramu

**Comment by shi-yuan** [comment]
[Regexp Query](https://github.com/NLPchina/elasticsearch-sql/issues/345) or [Script Query](https://github.com/NLPchina/elasticsearch-sql/wiki/ScriptQuery)

**Comment by thamaraikrishnan** [comment]
Is there a way to fetch data like MySQL?

LIKE BINARY '%ram%'
LIKE '%ram%'

I am new to this plugin, can you give me a sample to write regexp script using first name field to satisfy "LIKE and LIKE BINARY" functions?

**Comment by shi-yuan** [comment]
````
SELECT firstname , balance FROM accounts WHERE firstname.keyword = REGEXP_QUERY('.*[rR][aA][mM].*')

SELECT firstname , balance FROM accounts WHERE script('def firstname=doc["firstname.keyword"].value;firstname!=null&&firstname.toLowerCase().contains("ram")')
````

Alternatively, you can lowercase term, then use match query
