### ISSUE TITLE
from后面的表名可以带有*吗

### ISSUE THREAD

**Issue by wjphero** [NLPchina/elasticsearch-sql#780]
hi，各位前辈
    我这里有几个索引，分别是db-appname1-2018.09.25，db-appname1-2018.09.26，db-appname1-2018.09.27，如果想同时查询这几个索引，语句可以使用select * from db-appname1-*吗，但是我发现只能得到db-appname1-2018.09.25索引中的数据。怎样才能获取三个索引?

**Comment by shi-yuan** [comment]
可以带的
