### ISSUE TITLE
中文查询无结果

### ISSUE THREAD

**Issue by jgq2008303393** [NLPchina/elasticsearch-sql#781]
ES版本：5.6.4

查询语句：
GET _sql?sql=select id,name from products_index where  name=matchQuery('长裤') order by _score desc limit 2

explain结果如下：
{
  "from" : 0,
  "size" : 2,
  "query" : {
    "bool" : {
      "must" : [
        {
          "match" : {
            "name" : {
              "query" : "�",
              "operator" : "OR",
              "prefix_length" : 0,
              "max_expansions" : 50,
              "fuzzy_transpositions" : true,
              "lenient" : false,
              "zero_terms_query" : "NONE",
              "boost" : 1.0
            }
          }
        }
      ],
      "disable_coord" : false,
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  },
  "_source" : {
    "includes" : [
      "id",
      "name"
    ],
    "excludes" : [ ]
  },
  "sort" : [
    {
      "_score" : {
        "order" : "desc"
      }
    }
  ]
}

初步怀疑编码处理有问题，请教下社区大神，帮忙看看这个是什么问题？

**Comment by shi-yuan** [comment]
编码的问题吧，怎么请求的

**Comment by jgq2008303393** [comment]
> 编码的问题吧，怎么请求的

是的，使用urlencode编码后能正常发送，但是英文查询可以不用编码。请求发送的方式是在kibana的dev tools中直接发送下面命令：
GET _sql?sql=select id,name from products_index where name=matchQuery('长裤') order by _score desc limit 2

这个和具体的kibana版本有关系吗？大神平时是怎么发送的，也需要编码吗？

**Comment by shi-yuan** [comment]
这一块，近期会改，兼容post传参

**Comment by shi-yuan** [comment]
![1](https://user-images.githubusercontent.com/8057153/47198444-c77dbd00-d39e-11e8-9a79-6f16d2d63267.png)

**Comment by jgq2008303393** [comment]
赞

**Comment by hexian55** [comment]
这个是在哪个版本开始fix的？

**Comment by shi-yuan** [comment]
5.x没有啊，可以参考https://github.com/NLPchina/elasticsearch-sql/commit/4bdd75478c65fbfa7c83d01e97fad9597c86e851，自己fix
