### ISSUE TITLE
安装了X-Pack需要账户密码怎么配置

### ISSUE THREAD

**Issue by wjf662** [NLPchina/elasticsearch-sql#782]
设置了账户密码,需要账户密码登录
"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /_sql</pre>\n</body>\n</html>\n"

**Comment by shi-yuan** [comment]
[如何在site server 中添加认证信息](https://github.com/NLPchina/elasticsearch-sql/issues/543)
