### ISSUE TITLE
date_format error

### ISSUE THREAD

**Issue by Jacky0312** [NLPchina/elasticsearch-sql#797]
### error message: 
```
Caused by: java.lang.ClassCastException: Cannot apply [-] operation to types [org.joda.time.MutableDateTime] and [java.lang.Integer].
	at org.elasticsearch.painless.DefMath.sub(DefMath.java:488) ~[?:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_102]
	at org.elasticsearch.painless.DefBootstrap$MIC.fallback(DefBootstrap.java:373) ~[?:?]
	at org.elasticsearch.painless.PainlessScript$Script.execute(def date_format_652098545 = new SimpleDateFormat('dd/MM/YYYY').format(new Date(doc['phDOB'].value - 8*1000*60*60));date_format_652098545 >= '22/11/2018':92) ~[?:?]
```
**Why will subtract 8*1000*60*60 when converting to script?**
`def date_format_652098545 = new SimpleDateFormat('dd/MM/YYYY').format(new Date(doc['phDOB'].value - 8 * 1000 *60 * 60));date_format_652098545 >= '22/11/2018'`

### My usage
```
 def sdf = new SimpleDateFormat('dd/MM/YYYY')
            sdf.setTimeZone(TimeZone.getTimeZone(ZoneId.systemDefault()))
            if (criteria.phDOBDateRange) {
                if (criteria.phDOBDateRange.from) {
                    basicSQL.append("and date_format(phDOB,'dd/MM/YYYY') >= '${sdf.format(criteria.phDOBDateRange.from)}' ")
                }
                if (criteria.phDOBDateRange.to) {
                    Date to = new DateTime(criteria.phDOBDateRange.to).plusDays(1).toDateMidnight().toDate()
                    basicSQL.append("and phDOB < '${to.getTime()}' ")
                }
            }
```

**Comment by Jacky0312** [comment]
> master branch

So the bug has been fixed in the latest version.
By the way, whether the version of elasticsearch-sql corresponds to the version of elasticsearch.
The version of elasticsearch-sql I use is 6.2.2.
Thanks!

**Comment by shi-yuan** [comment]
yeah，the version of elasticsearch-sql corresponds to the version of elasticsearch

**Comment by Jacky0312** [comment]
> yeah，the version of elasticsearch-sql corresponds to the version of elasticsearch

Ok, thank you very much.

**Comment by palbiplab** [comment]
`SELECT * FROM my_index where date_format(phDOB,'dd/MM/YYYY') >'22/11/2018' `

`{
  "from": 0,
  "size": 200,
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "script": {
                  "script": {
                    "source": "def date_format_1266264528 = DateTimeFormatter.ofPattern('dd/MM/YYYY').withZone(ZoneId.systemDefault()).format(Instant.ofEpochMilli(doc['phDOB'].value.getMillis()));date_format_1266264528 > '22/11/2018'",
                    "lang": "painless"
                  },
                  "boost": 1
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  }
} `

Above query/explain throws > cannot be used for string type with elastic search version 6.4.2, does it work with later version or im missing something?

**Comment by shi-yuan** [comment]
> `SELECT * FROM my_index where date_format(phDOB,'dd/MM/YYYY') >'22/11/2018' `
> 
> `{ "from": 0, "size": 200, "query": { "bool": { "filter": [ { "bool": { "must": [ { "script": { "script": { "source": "def date_format_1266264528 = DateTimeFormatter.ofPattern('dd/MM/YYYY').withZone(ZoneId.systemDefault()).format(Instant.ofEpochMilli(doc['phDOB'].value.getMillis()));date_format_1266264528 > '22/11/2018'", "lang": "painless" }, "boost": 1 } } ], "adjust_pure_negative": true, "boost": 1 } } ], "adjust_pure_negative": true, "boost": 1 } } } `
> 
> Above query/explain throws > cannot be used for string type with elastic search version 6.4.2, does it work with later version or im missing something?

resolved https://github.com/NLPchina/elasticsearch-sql/issues/807
```json
{
  "from": 0,
  "size": 1000,
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "script": {
                  "script": {
                    "source": "def date_format_463022828 = DateTimeFormatter.ofPattern('dd/MM/YYYY').withZone(ZoneId.systemDefault()).format(Instant.ofEpochMilli(doc['phDOB'].value.getMillis()));((Comparable)date_format_463022828).compareTo('22/11/2018') > 0",
                    "lang": "painless"
                  },
                  "boost": 1
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  }
}
```

**Comment by palbiplab** [comment]
Thanks @shi-yuan , appreciate your prompt response.
