### ISSUE TITLE
1.3.5 no longer accepts newline as space?

### ISSUE THREAD

**Issue by daledude** [NLPchina/elasticsearch-sql#80]
We just upgraded to 1.3.5 from 1.2 (i think). We have queries with \n in them that used to work but now fail with:

```
SQLFeatureNotSupportedException[Unsupported query
```

Using the web interface to test it seems that I must have a space before the \n (doesn't work after) but only up until after the FROM clause. The query I used to test is below. There is a space before the new line on the SELECT and FROM lines but every line after does not have a space at the end and the query succeeds. Take away the space at the end of any of the SELECT and FROM lines will produce the error. Use mouse to highlight the query and you will see the spaces at the end of the lines.

```
SELECT 
MAX(statPorts) as maxPorts, MIN(statPorts) as minPorts, AVG(statPorts) as avgPorts, MAX(statCPS) as maxCps, MIN(statCPS) as minCps, AVG(statCPS) as avgCps
FROM data-2015.08.22 
where
datadate between '2015-08-22 00:00:00-0000' and '2015-08-22 23:59:59-0000'
and portNum in (8493)
GROUP BY date_histogram(field='datadate','interval'='hour')
```

**Comment by eliranmoyal** [comment]
can you check it with the latest version?

**Comment by daledude** [comment]
Version 1.4.1 still same issue. You can check by doing a simple query below. Make sure there are no spaces at the end of the lines.

```
select
count(*)
from
someindex
```

1.4.1 no longer likes my query because the index name is formatted like data-2015.08.22. If I create an alias like data20150822 the query works.

**Comment by eliranmoyal** [comment]
fixed, and dots are allowed again
The new line was a problem after the select.
