### ISSUE TITLE
while using histogram, there is no way to create an alias.

### ISSUE THREAD

**Issue by vivekkothari** [NLPchina/elasticsearch-sql#81]
while using histogram, there is no way to create an alias.
this causes the column to be show as something like
histogram(field='field',interval='1d'  (to string implementation)
it would be awesome if support for alias was added.

**Comment by eliranmoyal** [comment]
You are right. I think it is because it is on the group by statement.
what do you say about something like : 
`group by date_histogram(field='insert_time','interval'='2h','format'='yyyy-MM','alias'='yourAlias')`

**Comment by vivekkothari** [comment]
Yes.. thats exactly what i need!!

**Comment by eliranmoyal** [comment]
Done
I'll make a new release with more features this weekend.

**Comment by eliranmoyal** [comment]
check it on a new release 1.4.1 
https://github.com/NLPchina/elasticsearch-sql/releases/download/1.4.1/elasticsearch-sql-1.4.1.zip
