### ISSUE TITLE
6.5.0 6.5.1版本报错问题[已解决]

### ISSUE THREAD

**Issue by tanjun2030** [NLPchina/elasticsearch-sql#820]
HI，我的ES版本是6.5.1，现在执行的时候一直报错，尝试了6.4.2版本正常。
1.安装插件
`./bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/6.5.1.0/elasticsearch-sql-6.5.1.0.zip`
2.安装node环境
`cd site-server
npm install express --save
node node-server.js `
3.启动elasticsearch并访问
`http://localhost:9200/_sql?sql=select * from my_index limit 10`
4.报错：
`{
error: {
root_cause: [
{
type: "parse_exception",
reason: "request body or source parameter is required"
}
],
type: "parse_exception",
reason: "request body or source parameter is required"
},
status: 400
}`

以上报错信息在6.5.0，6.5.1都是一样，6.4.2就没问题(我安装步骤是一样的）。
谁知道原因吗？
谢谢啦~

**Comment by shi-yuan** [comment]
````
curl -X GET "localhost:9200/_sql" -H 'Content-Type: application/json' -d'
{
    "sql": "SELECT * FROM my_index LIMIT 10"
}
'
````
````
curl -X POST "localhost:9200/_sql" -H 'Content-Type: application/json' -d'
{
    "sql": "SELECT * FROM my_index LIMIT 10"
}
'
````

**Comment by tanjun2030** [comment]
> ```
> curl -X GET "localhost:9200/_sql" -H 'Content-Type: application/json' -d'
> {
>     "sql": "SELECT * FROM my_index LIMIT 10"
> }
> '
> ```
> ```
> curl -X POST "localhost:9200/_sql" -H 'Content-Type: application/json' -d'
> {
>     "sql": "SELECT * FROM my_index LIMIT 10"
> }
> '
> ```

不能通过http请求的方式吗？我打算把这个【http://localhost:9200/_sql?sql=select * from my_index limit 10】做成api返回数据？

**Comment by shi-yuan** [comment]
支持的，不过Content-Type得是application/json

**Comment by shi-yuan** [comment]
kibana也是可以访问的哦：

![1](https://user-images.githubusercontent.com/8057153/49566125-85b3d080-f964-11e8-84fb-7dbdd616dfd5.png)

**Comment by tanjun2030** [comment]
这个是为什么呢？6.4.2版本直接通过http://localhost:9200/_sql?sql=select * from my_index limit 10 就能返回json结果了，6.5+就不行了。。

**Comment by tanjun2030** [comment]
> kibana也是可以访问的哦：
> 
> ![1](https://user-images.githubusercontent.com/8057153/49566125-85b3d080-f964-11e8-84fb-7dbdd616dfd5.png)

我试了，6.5.1的kibana确实可以！但是url的方式直接不行了。

**Comment by tanjun2030** [comment]
> 支持的，不过Content-Type得是application/json

我明白了，我通过java请求试试，估计是浏览器直接url不行了。

**Comment by shi-yuan** [comment]
这个是es的限制，上面的出错信息是es本身抛出来的

**Comment by shi-yuan** [comment]
或者可以把数据放在requestbody里

**Comment by shi-yuan** [comment]
````
curl -X POST "localhost:9200/_sql" -H 'Content-Type: application/json' -d'
SELECT * FROM my_index LIMIT 10
'
````

**Comment by tanjun2030** [comment]
> 这个是es的限制，上面的出错信息是es本身抛出来的

难怪，我看源码里面没有这个报错，哈哈

**Comment by tanjun2030** [comment]
> curl

这个直接执行也可以。。谢谢哈。。那估计是6.4.*版本没做这个限制，6.5.*才有的。
辛苦辛苦！

**Comment by shi-yuan** [comment]
代码接收参数这块儿做了兼容：
1、支持（推荐）：
curl -X POST "localhost:9200/_sql" -H 'Content-Type: application/json' -d'
{
    "sql": "SELECT * FROM my_index LIMIT 10"
}
'
2、支持：
curl -X POST "localhost:9200/_sql" -H 'Content-Type: application/json' -d'
SELECT * FROM my_index LIMIT 10
'

![1](https://user-images.githubusercontent.com/8057153/49566623-425a6180-f966-11e8-8cfd-41237cd06b08.png)

**Comment by tanjun2030** [comment]
> 接收参数这块儿做了兼容：
> 1、支持（推荐）：
> 
> ```
> curl -X POST "localhost:9200/_sql" -H 'Content-Type: application/json' -d'
> {
>     "sql": "SELECT * FROM my_index LIMIT 10"
> }
> '
> ```
> 2、支持：
> 
> ```
> curl -X POST "localhost:9200/_sql" -H 'Content-Type: application/json' -d'
> SELECT * FROM my_index LIMIT 10
> '
> ```
> ![1](https://user-images.githubusercontent.com/8057153/49566623-425a6180-f966-11e8-8cfd-41237cd06b08.png)

这种方式怎么通过java请求呢？没有curl的api呢。。尴尬

**Comment by SDUmzg** [comment]
@shi-yuan es jdbc alson report this error, how do you deal with it for es 6.5+ jdbc

**Comment by shi-yuan** [comment]
随便一个http client就可以了
