### ISSUE TITLE
date_histogram offset

### ISSUE THREAD

**Issue by zhyh1105** [NLPchina/elasticsearch-sql#821]
在使用date_histogram函数时，field如果是long类型的时间戳，想设置offset时，发现不行，查看源码org.nlpcn.es4sql.query.maker.AggMaker.dateHistogram(MethodField field)时发现switch里没有对offset参数进行处理，需添加如下代码
```
case "offset":
    dateHistogram.offset(value);
    break;
```
发现好几个版本都有类似情况，不知是有意不处理offset参数，还是忘了呢？

**Comment by lychee180** [comment]
I have the same question.
