### ISSUE TITLE
Aggregation Sort by _count

### ISSUE THREAD

**Issue by vishnugt** [NLPchina/elasticsearch-sql#823]
s there a way to sort terms aggregation by `_count` instead of `_key`?

Corresponding ES query would be something like this:

`
{
  "aggs": {
    "genres": {
      "terms": {
        "field": "genre",
        "order": {
          "_count": "asc"
        }
      }
    }
  }
}
`

By default it is sorted with `_count` in descending order, but is there a way to sort it in ascending order?

**Comment by shi-yuan** [comment]
```sql
SELECT * FROM myindex GROUP BY terms(alias='genres',field='genre',order='{"_count":"asc"}')
```
