### ISSUE TITLE
Sorting aggregation with child metric aggregation

### ISSUE THREAD

**Issue by vishnugt** [NLPchina/elasticsearch-sql#824]
Do we have support to sort aggregations by its child metric aggregation?

Elasticsearch query will be something like this
`{
    "aggs" : {
        "colors" : {
            "terms" : {
              "field" : "color",
              "order": {
                "avg_price" : "asc" 
              }
            },
            "aggs": {
                "avg_price": {
                    "avg": {"field": "price"} 
                }
            }
        }
    }
}`

**Comment by shi-yuan** [comment]
```sql
SELECT avg(price) AS avg_price FROM myindex GROUP BY terms(alias='colors',field='color',order='{"avg_price":"asc"}')
```
