### ISSUE TITLE
date_histogram聚合之后的别名怎么写

### ISSUE THREAD

**Issue by zhangkunjie** [NLPchina/elasticsearch-sql#828]
使用date_histogram函数聚合查询，但是查询的结果聚合字段是date_histogram(field='@timestamp','interval'='1d') 
语句：
SELECT 
count(distinct url.keyword) as num
FROM  search_log_*
where
     bt.keyword='purity_add_doc'
and  @timestamp>= '2018-12-13' 
and   @timestamp<'2018-12-14'
and  purity_add_doc9=98
group by date_histogram(field='@timestamp','interval'='1d') 
结果：
date_histogram(field='@timestamp','interval'='1d')     num
2018-12-13                                                                     100
请问如何改变结果表头date_histogram(field='@timestamp','interval'='1d'这个值？在哪里使用as?

**Comment by shi-yuan** [comment]
alias
```sql
SELECT
count(distinct url.keyword) as num
FROM search_log_*
where
bt.keyword='purity_add_doc'
and @timestamp>= '2018-12-13'
and @timestamp<'2018-12-14'
and purity_add_doc9=98
group by date_histogram(alias='histogram', field='@timestamp','interval'='1d')
```

**Comment by zhangkunjie** [comment]
赞~谢谢！
