### ISSUE TITLE
Getting error while using "GEO_BOUNDING_BOX"  in the query

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#84]
http://xx.xxx.xx.xxx:9200/_sql?sql=SELECT count(*) FROM index_name/test_locs WHERE GEO_BOUNDING_BOX(test_loc,40.8,-74.0,40.7,-73.0)

Error below

{"error":"SqlParseException[err find condition class org.durid.sql.ast.expr.SQLMethodInvokeExpr]","status":500}

Any idea. I believe GEO_BOUNDING_BOX is supported in the query.

**Comment by satapsa** [comment]
I installed the 1.3.5 release and it solved the issue.

**Comment by satapsa** [comment]
I am not getting the parsing error. However the GEO_BOUNDING_BOX is NOT filtering out the records it is supposed to

select * from index_name/test_locs  where GEO_BOUNDING_BOX(test_loc,35.00,-85.280000,25.00,-75.00)

The same in curl is filtering out the records correctly.
curl -XGET 'ip:9200/index_name/test_locs/_search?pretty'-d '{"query":{"filtered":{"filter":{"geo_bounding_box":{"test_loc":{"top_left": {"lat": 35.00,"lon": -85.28},"bottom_right": {"lat":  25.00,"lon": -75.00}}}}}}}'

Note : test_loc is the name of the geo_point

**Comment by eliranmoyal** [comment]
the order is lon and than lat

**Comment by eliranmoyal** [comment]
check our wiki and please tell us if you having any other problems
https://github.com/NLPchina/elasticsearch-sql/wiki/Geographic-Queries
