### ISSUE TITLE
麻烦更新支持下5.6.14?

### ISSUE THREAD

**Issue by xfyuan** [NLPchina/elasticsearch-sql#842]
能麻烦更新支持下5.6.14吗，现在只到5.6.13。。

非常感谢！

**Comment by shi-yuan** [comment]
恩恩，近期会支持的~

**Comment by xfyuan** [comment]
麻烦了。

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/releases/tag/5.6.14.0
