### ISSUE TITLE
How to Use Boost Option in SQL Plugin

### ISSUE THREAD

**Issue by mhsankar** [NLPchina/elasticsearch-sql#847]
Hi.
How can write below code in **SQL Plugin** ?
i want to use **Boost** option in query.

```
POST _search
{
    "query": {
        "match" : {
            "title": {
                "query": "quick brown fox",
                "boost": 2
            }
        }
    }
}
```

**Comment by mhsankar** [comment]
what is difference between q=query('field:search')
and field=matchQuery('quick brown fox')?
another question: how to use boost in  q=query('field:search')

**Comment by shi-yuan** [comment]
[Query String Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) VS [Match Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html)

**Comment by shi-yuan** [comment]
boost example：
```sql
SELECT * FROM myindex WHERE q=query('field:search^5')
```
Or
```sql
SELECT * FROM myindex WHERE q=query('field:search', boost=5)
```

**Comment by mhsankar** [comment]
How can use [operator](https://www.elastic.co/guide/en/elasticsearch/guide/current/match-multi-word.html#match-improving-precision) or [minimum_should_match](https://www.elastic.co/guide/en/elasticsearch/guide/current/match-multi-word.html#match-precision) in query?
How can see generated query by this plugin?

**Comment by mhsankar** [comment]
and How can see generated query by this plugin?

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/wiki/Installation-Guide

**Comment by shi-yuan** [comment]
![1](https://user-images.githubusercontent.com/8057153/51154040-73a34700-18ad-11e9-81a4-73a7ed91fe0c.png)

**Comment by mhsankar** [comment]
Thank you @shi-yuan 
another question.
is there any way write elastic query and it convert to sql format query?

**Comment by shi-yuan** [comment]
Sorry，I don't know that.

**Comment by shi-yuan** [comment]
```sql
SELECT * FROM myindex WHERE title = matchQuery('quick brown fox', boost = 2, operator = 'and', minimum_should_match = '75%')
```
```json
{
  "from": 0,
  "size": 1000,
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "match": {
                  "title": {
                    "query": "quick brown fox",
                    "operator": "AND",
                    "prefix_length": 0,
                    "max_expansions": 50,
                    "minimum_should_match": "75%",
                    "fuzzy_transpositions": true,
                    "lenient": false,
                    "zero_terms_query": "NONE",
                    "auto_generate_synonyms_phrase_query": true,
                    "boost": 2
                  }
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  }
}
```

**Comment by mhsankar** [comment]
i'm using elastic version 6.2.4
how can use operator in this version?
how can update my elastic sql plugin?

**Comment by shi-yuan** [comment]
Local packing，then replace elasticsearch-sql-x.x.x.x.jar

**Comment by mhsankar** [comment]
what do you mean local package?
what am i do?
when i clone source code how replace with elasticsearch-sql-x.x.x.x.jar?

**Comment by shi-yuan** [comment]
[elasticsearch-sql-6.2.4.0.zip](https://github.com/NLPchina/elasticsearch-sql/files/2769031/elasticsearch-sql-6.2.4.0.zip)

**Comment by mhsankar** [comment]
Hi @shi-yuan 
i download [this ](https://github.com/NLPchina/elasticsearch-sql/archive/6.2.4.0.zip) file
run with "Intellj Idea".
when apply this [change](https://github.com/NLPchina/elasticsearch-sql/commit/78c2afc32831dad26c0cb6ce9e4559037c676635) it needed previous changes.
i must get all changes after release "ElasticSearch SQL Plugin 6.2.4" . it is a problem.
some feature added in new version of elasticsearch.
how can ignore all this new elastic feature?
how can update changes without update elasticsearch version in "pom.xml"?
