### ISSUE TITLE
nested query is not working as expected from 6.4.2

### ISSUE THREAD

**Issue by palbiplab** [NLPchina/elasticsearch-sql#850]
The test case `QueryTest.complexNestedQueryBothOnSameObject()` returns result with `SELECT * FROM %s/nestedType where nested('message',message.info = 'a' and message.author ='i' )` but it returns nothing for `SELECT * FROM %s/nestedType where nested('message',message.info = 'c' and message.author ='h' )`.
message has array of records : `{"message":[{"info":"c","author":"h","dayOfWeek":4},{"info":"a","author":"i","dayOfWeek":5}]`.

Observation is query doesn't match with first array value.

**Comment by shi-yuan** [comment]
just try latest version~

**Comment by palbiplab** [comment]
Thanks, @shi-yuan it works with the latest version (6.5.3)
