### ISSUE TITLE
nested(path,conditions..,inner_hits) and nested(condition) returns different results from 6.4.2

### ISSUE THREAD

**Issue by palbiplab** [NLPchina/elasticsearch-sql#851]
`where nested('message',message.info='a') `and ` where nested(message.info)='a'` returns different result from 6.4.2

Note: tested with existing test cases data (nested_objects.json)

**Comment by shi-yuan** [comment]
just try latest version~

**Comment by palbiplab** [comment]
Thanks, @shi-yuan it works with the latest version (6.5.3).
