### ISSUE TITLE
请问这种条件sql 怎么写 谢谢！

### ISSUE THREAD

**Issue by LLeiFeng** [NLPchina/elasticsearch-sql#859]
{
  "processCode":"****",
  "timeStamp":"***",
  "rule": [
    {
      "result": [
        {
          "name": "verdict",
          "strValue": "pass"
        }
      ],
      "name": "test_7"
    },
    {
      "result": [
        {
          "name": "verdict",
          "strValue": "reject"
        }
      ],
      "name": "test_7"
    },
    {
      "result": [
        {
          "name": "reson",
          "strValue": "pass"
        }
      ],
      "name": "test_rule_3"
    }
  ]
}

文档格式类似这条 想按十分钟统计rule.name=test_7,rule.result.name=verdict时 result.name.strValue的分布 请问sql该如何写呢？
像以上数据得出的就是 pass:1 ,reject:1 谢谢！

以下是我写的sql,group by 那块的条件过滤有些问题没写出来
GET _sql/_explain?sql=select * from ${index} where commitId>0 and (timeStamp between 1547501223173 and 1547537223173)  and (nested(rule,rule.name = 'test_rule_7')) group by date_histogram(field='timeStamp','format'='yyyy-MM-dd HH:mm','interval'='10m','alias'='time')，nested(rule.name)

**Comment by shi-yuan** [comment]
这几个字段的mapping能给下么？

**Comment by LLeiFeng** [comment]
"rule": {
            "type": "nested",
            "properties": {
              "name": {
                "type": "keyword",
                "index_options": "freqs"
              },
              "result": {
                "type": "nested",
                "properties": {
                  "name": {
                    "type": "keyword",
                    "index_options": "freqs"
                  },
                  "strValue": {
                    "type": "keyword",
                    "index_options": "freqs"
                  }
                }
              }
            }
          }
mapping 如上 @shi-yuan

**Comment by LLeiFeng** [comment]
GET _sql?sql=select * from stanlee_decision-engine_2019-01-15 where commitId>0 and (timeStamp between 1547501223173 and 1547537223173)  and (nested(rule,rule.name = 'test_7')) group by date_histogram(field='timeStamp','format'='yyyy-MM-dd HH:mm','interval'='10m','alias'='time'),(nested(rule.name)),nested(rule.result.strValue) limit 0;

获取到的结果
```
```

**Comment by shi-yuan** [comment]
这个得加agg filter了，还不支持的， 
```json
{
  "from": 0,
  "size": 0,
  "query": {
      ...
  },
  "aggregations": {
    "rule.name@NESTED": {
      "nested": {
        "path": "rule"
      },
      "aggregations": {
        "rule.name": {
          "terms": {
            "field": "rule.name",
            "size": 1000,
            "shard_size": 20000,
            "min_doc_count": 1,
            "shard_min_doc_count": 0,
            "show_term_doc_count_error": false,
            "order": [
              {
                "_count": "desc"
              },
              {
                "_key": "asc"
              }
            ]
          },
          "aggregations": {
            "rule.result.strValue@NESTED": {
              "nested": {
                "path": "rule.result"
              },
              "aggregations": {
                "rule.result.strValue": {
                  "filter": {
                    "term": {
                      "rule.result.name": "verdict"
                    }
                  },
                  "aggregations": {
                    "rule.result.strValue": {
                      "terms": {
                        "field": "rule.result.strValue",
                        "size": 1000,
                        "shard_size": 20000,
                        "min_doc_count": 1,
                        "shard_min_doc_count": 0,
                        "show_term_doc_count_error": false,
                        "order": [
                          {
                            "_count": "desc"
                          },
                          {
                            "_key": "asc"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by LLeiFeng** [comment]
好的 谢谢

**Comment by shi-yuan** [comment]
不好意思哈的，是支持的：
```sql
select * from stanlee_decision-engine_2019-01-15 where commitId>0 
and (timeStamp between 1547501223173 and 1547537223173) 
and (nested(rule,rule.name = 'test_7')) 
group by date_histogram(field='timeStamp','format'='yyyy-MM-dd HH:mm','interval'='10m','alias'='time'),
(nested(rule.name)),
nested(rule.result.strValue),
filter('rule.result.name', rule.result.name=TERM('verdict'))
```

**Comment by LLeiFeng** [comment]
好的 谢谢哈  另外请问这个group by nested 支持别名吗 谢谢哈

**Comment by shi-yuan** [comment]
```sql
group by ...
(nested('alias', rule.name)),
...
```

**Comment by shi-yuan** [comment]
不支持的

**Comment by LLeiFeng** [comment]
另外一种情况  如果group by 时候不指定(nested(rule.name))这一列 但是想筛选出rule.name="test_rule",这一列的聚合数据 这个条件怎么加呢 也就是可以不筛选其他的rule.name等于其它列的数据  谢谢shi-yuan
select * from stanlee_decision-engine_2019-01-15 where commitId>0 
and (timeStamp between 1547501223173 and 1547537223173) 
and (nested(rule,rule.name = 'test_7')) 
group by date_histogram(field='timeStamp','format'='yyyy-MM-dd HH:mm','interval'='10m','alias'='time'),
(nested(rule.name)),
nested(rule.result.strValue),
filter('rule.result.name', rule.result.name=TERM('verdict'))

**Comment by LLeiFeng** [comment]
> 不支持的

只不支持group by nested 时候起别名吗？

**Comment by shi-yuan** [comment]
嗯嗯，group by nested的别名是不支持的

**Comment by LLeiFeng** [comment]
好的 谢谢shi-yuan
另外请问下 如果是group by 的多个filter 改如何写呢  我这样写指定rule.name='test_7' 以及rule.result.name='verdict'是不行的  麻烦了 谢谢

GET _sql/?sql=select * from stanlee_decision-engine_2019-01-15 where commitId>0 and (timeStamp between 1547501223173 and 1547537223173) and (nested(rule,rule.name = 'test_rule_7')) group by date_histogram(field='timeStamp','format'='yyyy-MM-dd HH:mm','interval'='10m','alias'='time'),nested(rule.result.strValue),filter('rule.name',rule.name=TERM('test_7')),filter('rule.result.name', rule.result.name=TERM('verdict'))

**Comment by shi-yuan** [comment]
filter后面可以接多个条件的：filter('rule.name',rule.name=TERM('test_7') and rule.result.name=TERM('verdict'))

**Comment by LLeiFeng** [comment]
好像不行 
这种方式是可以筛选出数据的
```
GET _sql/?sql=select * from stanlee_decision-engine_2019-01-15 where commitId>0 and (timeStamp between 1547501223173 and 1547537223173) and (nested(rule,rule.name = 'test_rule_7')) group by date_histogram(field='timeStamp','format'='yyyy-MM-dd HH:mm','interval'='10m','alias'='time'),nested(rule.result.strValue),filter('rule.result.name',rule.result.name=TERM('verdict'))
```
这种方式筛选不出数据，是因为nested(rule.result.strValue) 的nested path 是rule.result,  rule.name的path是name 么？
```
GET _sql/?sql=select * from stanlee_decision-engine_2019-01-15 where commitId>0 and (timeStamp between 1547501223173 and 1547537223173) and (nested(rule,rule.name = 'test_rule_7')) group by date_histogram(field='timeStamp','format'='yyyy-MM-dd HH:mm','interval'='10m','alias'='time'),nested(rule.result.strValue),filter('rule.name',rule.name=TERM('test_rule_7'))
```

**Comment by LLeiFeng** [comment]
这个group by 筛选过滤语法有文档吗  wiki里面没有看到相关的文档诶~

**Comment by shi-yuan** [comment]
```sql
select * from stanlee_decision-engine_2019-01-15 where commitId>0 
and (timeStamp between 1547501223173 and 1547537223173) 
and (nested(rule,rule.name = 'test_rule_7')) 
group by date_histogram(field='timeStamp','format'='yyyy-MM-dd HH:mm','interval'='10m','alias'='time'),
nested(rule.name),
filter('rule.name',rule.name=TERM('test_rule_7')),
nested(rule.result.strValue),
filter('rule.result.name', rule.result.name=TERM('verdict'))
```

**Comment by shi-yuan** [comment]
上面的sql执行是有问题的，在[这里](https://github.com/NLPchina/elasticsearch-sql/commit/a1bf9f9e3181f07ac43ac82e71802047be8d8cc6)做了修复，如果用的话，记得更新哈

**Comment by shi-yuan** [comment]
目前这方面的文档，是没有的哦，现在有的是一些[testcase](https://github.com/NLPchina/elasticsearch-sql/blob/master/src/test/java/org/nlpcn/es4sql/AggregationTest.java)，里面有一些group by filter的示例，可以参考参考哈

**Comment by LLeiFeng** [comment]
好的 感谢
