### ISSUE TITLE
DELETE SQL with LIMIT

### ISSUE THREAD

**Issue by zarasargsyan** [NLPchina/elasticsearch-sql#867]
Hello,

I'm trying to run delete sql query with limitation, but it deletes all founded rows. Is limitation for delete query supported or no?

example

>  DELETE FROM bank WHERE age >30 LIMIT 1;
but it deletes all which age >30

**Comment by shi-yuan** [comment]
Oh~~~，limit not supported now！:sweat:

**Comment by developer-devPHP** [comment]
@shi-yuan sorry, but do you have any estimation, when this future could be exists. 
This will be very useful future.

**Comment by shi-yuan** [comment]
:ok_hand:

**Comment by developer-devPHP** [comment]
any roughly estimation?

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/commit/f8ee5b6fc40d40073e76ab80ba35b9e0975e1016

**Comment by shi-yuan** [comment]
```sql
delete from myindex limit 3
```
