### ISSUE TITLE
limit 100,2 can not be used correctly

### ISSUE THREAD

**Issue by aitanjupt** [NLPchina/elasticsearch-sql#88]
If i use "limit 100,2", I want to get results pagely, but I found this doesnt work well. "limit 100,2" 'result = "limit 2". How can I do Paging well?
"SELECT *,COUNT(1),SUM(orderTotalAmount) FROM myIndex where (id=110820) GROUP BY tId ORDER BY rId DESC LIMIT 0,5"
This is my sql. I found using "GROUP BY" causes this issue.
And I found "GROUP BY date_histogram()" even causes "limit 2" does not work.

**Comment by eliranmoyal** [comment]
I don't think you can page on elastic when using aggregations.
see https://github.com/elastic/elasticsearch/issues/7956  for term agg

and for date histogram
https://github.com/elastic/elasticsearch/issues/7103

**Comment by aitanjupt** [comment]
yes, its elasticsearch's issue. thank you for your information.
