### ISSUE TITLE
需要等介支持_search?preference=xyzabc123

### ISSUE THREAD

**Issue by microhuang** [NLPchina/elasticsearch-sql#883]
官方描述见：https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-request-preference.html

**Comment by shi-yuan** [comment]
```sql
select /*! PREFERENCE(_shards:2,3|_local) */ * from myindex
```

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/commit/cdb9c32a78ee5fb9b6f48bf19ee07305d75a0d6b
