### ISSUE TITLE
DELETE with limit generate an error

### ISSUE THREAD

**Issue by developer-devPHP** [NLPchina/elasticsearch-sql#884]
When doing delete in cycle for example something like this
```php
do{
    DELETE FROM index LIMIT 100
}
while(stopcondition)
```

got an error  ``version_conflict_engine_exception`` ``version conflict, current version [2] is different than the one provided [1]``

In original elastic ``_update_by_query`` they have a param ``conflicts=proceed``
Can we pass parameter like this or do we have an alternate solution for this?

**Comment by shi-yuan** [comment]
conflicts hint is needed, like this:
```sql
DELETE /*! CONFLICTS(proceed) */ FROM index LIMIT 100
```

**Comment by developer-devPHP** [comment]
Have the following error, when running
 ```sql 
DELETE /*! CONFLICTS(proceed) */ FROM index LIMIT 100 
``` 
query or trying to run explain
```json
{
    "error": {
        "root_cause": [
            {
                "type": "parser_exception",
                "reason": "syntax error"
            }
        ],
        "type": "parser_exception",
        "reason": "syntax error"
    },
    "status": 500
}
```

**Comment by shi-yuan** [comment]
because this hint not supported now

**Comment by developer-devPHP** [comment]
Is this hint support implemented nearest future?

**Comment by shi-yuan** [comment]
Of course
