### ISSUE TITLE
Space separated field names

### ISSUE THREAD

**Issue by micxba** [NLPchina/elasticsearch-sql#89]
Some of my fields in an index are "Status Text" etc which is beyond my control. In most RDBMS you can issue a query like Select * from [Status Text] where x=y but that does not appear to be the case in this plugin.

**Comment by eliranmoyal** [comment]
Do you mean space separated index name?

**Comment by micxba** [comment]
Apologies, I gave a bad query as an example. The index name does not have spaces but the fields so a better RDBMS equivalent would be Select [field name] from index where x=y

**Comment by eliranmoyal** [comment]
I got it working on my fork. 
I got a PR but its on for 14 days now.. So if you want you can build my fork and try it out :)

**Comment by eliranmoyal** [comment]
Check it with latest version (1.4) it is working now
