### ISSUE TITLE
How to query with date field in true timezone

### ISSUE THREAD

**Issue by kiakaku** [NLPchina/elasticsearch-sql#890]
I have sql like this

```sql
select created,customer_first_address 
from packages-* 
where created >= '2019-02-28 17:00:00' 
order by created desc limit 10
```

But response

> failed to parse date field [2019-02-28 17:00:00] with format [strict_date_optional_time||epoch_millis]

How can i give sql a format `yyyy-MM-dd HH:mm:ss`

**Comment by shi-yuan** [comment]
```sql
select created,customer_first_address 
from packages-*
where date_format(created,'yyyy-MM-dd HH:mm:ss') >= '2019-02-28 17:00:00' 
order by created desc limit 10
```

**Comment by kiakaku** [comment]
hi @shi-yuan if using `date_format` function then how is parse with true timezone

**Comment by shi-yuan** [comment]
```sql
select created,customer_first_address 
from packages-*
where date_format(created,'yyyy-MM-dd HH:mm:ss','+08:00') >= '2019-02-28 17:00:00' 
order by created desc limit 10
```

**Comment by palbiplab** [comment]
The explain for above sqls
`{
  "from": 0,
  "size": 200,
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "script": {
                  "script": {
                    "source": "def date_format_1266264528 = DateTimeFormatter.ofPattern('dd/MM/YYYY').withZone(ZoneId.systemDefault()).format(Instant.ofEpochMilli(doc['phDOB'].value.getMillis()));date_format_1266264528 > '22/11/2018'",
                    "lang": "painless"
                  },
                  "boost": 1
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  }
} 
`

And it throws exception(> cannot be applied to string type) with elastic search 6.4.2, does it work with later version or im missing anything? The value of phDOB is of date type in index. Thanks in advance.

**Comment by shi-yuan** [comment]
> The explain for above sqls
> `{ "from": 0, "size": 200, "query": { "bool": { "filter": [ { "bool": { "must": [ { "script": { "script": { "source": "def date_format_1266264528 = DateTimeFormatter.ofPattern('dd/MM/YYYY').withZone(ZoneId.systemDefault()).format(Instant.ofEpochMilli(doc['phDOB'].value.getMillis()));date_format_1266264528 > '22/11/2018'", "lang": "painless" }, "boost": 1 } } ], "adjust_pure_negative": true, "boost": 1 } } ], "adjust_pure_negative": true, "boost": 1 } } } `
> 
> And it throws exception(> cannot be applied to string type) with elastic search 6.4.2, does it work with later version or im missing anything? The value of phDOB is of date type in index. Thanks in advance.

resolved here 
https://github.com/NLPchina/elasticsearch-sql/issues/807

**Comment by palbiplab** [comment]
Thanks @shi-yuan , appreciate your quick response.
