### ISSUE TITLE
missing fields

### ISSUE THREAD

**Issue by platdrag** [NLPchina/elasticsearch-sql#90]
for some reason, some fields cannot be included in queries:

trying to specifically add the @timestamp field results in a query error (althought doing select * prints it properly)

some fields are missing altogether for example a query like this:
SELECT '@timestamp',sessionMainUrl,dstHost,allHostsInSession
FROM logstash-2015.09.10* 
where type="GRAY_DATA_SESSIONS_HTTP" limit 10

results with only 2 fields, the field 'allHostsInSession' just being ignored
(verified directly in ES, the field indeed exist)

also, if field really does not exist, no error is displayed.

**Comment by eliranmoyal** [comment]
Fields with @ is a bit problem for sql (those are variables.) I will work on it.
about the 2nd problem. if you don't add the '@timestamp' you still not getting the allHostsInSession value?

**Comment by eliranmoyal** [comment]
Check on latest version
