### ISSUE TITLE
When will the update for elasticsearch-sql be available for Elasticsearch 6.7?

### ISSUE THREAD

**Issue by kchanporn** [NLPchina/elasticsearch-sql#911]
Elasticesearch 6.7 just came out and we downloaded it yesterday. We were wonder when will the never version that is compatible with Elasticesearch 6.7 be available? 

Thank you!

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/releases/tag/6.7.0.0
