### ISSUE TITLE
springboot 整合多数据源 elasticsearch-sql 6.2.3.0 一直转菊花没有结果

### ISSUE THREAD

**Issue by liujianrong** [NLPchina/elasticsearch-sql#912]
![image](https://user-images.githubusercontent.com/12397561/55141625-cafb4880-5175-11e9-9069-54f58b3c0a1b.png)

跑单测，程序一致在loaded plugin [org.elasticsearch.transport.Netty4Plugin] 转菊花

maven依赖：
 
        <dependency>
            <groupId>org.nlpcn</groupId>
            <artifactId>elasticsearch-sql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>transport</artifactId>
            <version>6.2.3</version>
            
        </dependency>
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>6.2.3</version>
        </dependency>

数据源配置：
//    @Bean(name = "esDataSource", initMethod = "init", destroyMethod = "close")
    public DruidDataSource esDataSource() throws Exception {
        System.setProperty("es.set.netty.runtime.available.processors", "false");
        Properties properties = new Properties();
        properties.put("url", "jdbc:elasticsearch://127.0.0.1:9300/monitor/");
        properties.put(PROP_CONNECTIONPROPERTIES, "client.transport.ignore_cluster_name=true");
        return (DruidDataSource) ElasticSearchDruidDataSourceFactory.createDataSource(properties);
    }

使用AOP动态切换数据源
    @DataSource(name = DSEnum.DATA_SOURCE_ES)
    public Monitor selectOne() {
        return elasticsearchDAO.selectOne();
    }

**Comment by shi-yuan** [comment]
最新版用的x-pack-transport吧，用最新版打个包吧

**Comment by liujianrong** [comment]
> 最新版用的x-pack-transport吧，用最新版打个包吧

ok, thanks
