### ISSUE TITLE
在查询group by的时候，group by中文字段结果会被分词

### ISSUE THREAD

**Issue by sc750531323** [NLPchina/elasticsearch-sql#918]
比如，select username,count(*) from table where xxx group by username;  如果username是英文就能完整显示出来，如果是中文，比如小明，那么会出现"小"字多少个，"明"字多少个,es版本6.3.1

**Comment by shi-yuan** [comment]
mapping里定义username的时候，设置了分词了吧

**Comment by sc750531323** [comment]
解决了，使用username.keyword就可以了
