### ISSUE TITLE
elasticSearch paging problem

### ISSUE THREAD

**Issue by w17703931335** [NLPchina/elasticsearch-sql#919]
My data default return 10,000 more than 10,000 error, how to use Java to modify the maximum number of returned

**Comment by shi-yuan** [comment]
[Scroll](https://github.com/NLPchina/elasticsearch-sql/wiki/Scroll)

**Comment by shi-yuan** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#dynamic-index-settings

**Comment by ZQbd** [comment]
使用es-sql，不用limit，我如何后台一次性查询出所有结果

**Comment by shi-yuan** [comment]
可以用scroll去拿

**Comment by w17703931335** [comment]
thank you,Problem solved
