### ISSUE TITLE
limit 10这样可以,但是limit 0,10这样写就报错

### ISSUE THREAD

**Issue by wds--moon** [NLPchina/elasticsearch-sql#927]
# select title from shandong LIMIT 1,2 错误
$ select title from shandong LIMIT 10 这样可以
@shi-yuan

**Comment by wds--moon** [comment]
@shi-yuan 我发一下一个bug就是的elasticSearch6.4.3 使用的druid的版本只能低于1.0.12,不知道为啥原因

**Comment by shi-yuan** [comment]
url不对，应该是：

**Comment by wds--moon** [comment]
我发现一个问题,就是elasticSearch-sql插件,使用的druid连接池,我当时就像自己干脆就直接使用druid少去麻烦,结果就出现上面的兼容性问题,后来我还是改成追光者hikari

**Comment by shi-yuan** [comment]
刚开始是仅仅用了sql parse的，后来支持了jdbc，就用了druid的连接池，考虑着，升级下druid

**Comment by wds--moon** [comment]
非常感谢,

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/releases/tag/6.7.1.0

druid已升级到最新
