### ISSUE TITLE
es_sql查询报405

### ISSUE THREAD

**Issue by sanaLiu** [NLPchina/elasticsearch-sql#929]
我装的是集群版的加了https认证的es集群，并且三台都安装了es_sql，但是这三台es_sql只能查询到其中一台es的数据，查询其他两台es都报405，不允许post请求，但是三台es和es_sql的配置和安装方式都是一样的，这是为什么呢

**Comment by shi-yuan** [comment]
只能访问一台的_sql？相关日志信息，大致的配置能给下么？

**Comment by sanaLiu** [comment]
cluster.name: elasticsearch
network.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300
transport.tcp.compress: true
action.auto_create_index: true
discovery.zen.ping.unicast.hosts: ["ip1","ip2","ip3"]
http.compression: true
bootstrap.memory_lock: false
bootstrap.system_call_filter: false
http.cors.enabled: true
http.cors.allow-credentials: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length,Authorization"
opendistro_security.ssl.transport.enabled: true
opendistro_security.ssl.transport.keystore_filepath: 
opendistro_security.ssl.transport.truststore_filepath: 
opendistro_security.ssl.transport.truststore_password: 
opendistro_security.ssl.transport.keystore_password: 
opendistro_security.ssl.transport.enforce_hostname_verification: false
opendistro_security.ssl.http.enabled: true

**Comment by shi-yuan** [comment]
request的Headers能看看么？如果直接用https://es:9200/能正常访问么？

**Comment by sanaLiu** [comment]
我访问 https://es:9200/ 是可以的，用es自带的sql命令行查询都是可以的

**Comment by shi-yuan** [comment]
访问其他机器的base_uri不一样的，是吧？从Headers看，Response Headers的allow-methods不一致的

**Comment by sanaLiu** [comment]
是的，三台_sql只能访问其中一台es，之前是都可以的，es配置什么的都没改过的

**Comment by shi-yuan** [comment]
post请求都不允许了，其他url的post请求可以么？检查检查searchguard的配置

**Comment by sanaLiu** [comment]
好的吧
