### ISSUE TITLE
解析SQLExpr的有问题

### ISSUE THREAD

**Issue by WhisperLoli** [NLPchina/elasticsearch-sql#930]
![image](https://user-images.githubusercontent.com/31977300/58193606-f7ef5600-7cf5-11e9-9ba6-d7101751bcb5.png)

我用的ES版本是5.2.2，使用range query给double类型的值70.1，解析后类却转变成了BigDecimal，而BigDecimal在ES中是不支持的，最后执行查询的时候ES源码中会校验值的类型，导致报错
@shi-yuan

**Comment by WhisperLoli** [comment]
![image](https://user-images.githubusercontent.com/31977300/58196348-b31aed80-7cfc-11e9-8fc3-54839d344bbe.png)

**Comment by WhisperLoli** [comment]
![image](https://user-images.githubusercontent.com/31977300/58196772-9b903480-7cfd-11e9-809a-5008447a70cc.png)

ES源码org.elasticsearch.common.io.stream.StreamOutput.class中655行左右会判断类型，最后导致抛出异常

![image](https://user-images.githubusercontent.com/31977300/58196912-d85c2b80-7cfd-11e9-9717-3458b583faee.png)

**Comment by shi-yuan** [comment]
sql能给下么？

**Comment by WhisperLoli** [comment]
```shell
SELECT storeid,skucode,rtcid,percent_mark,penetrance,qty,pickpercent,fresh_cp_seq,sum_35days_sales FROM fgrm-2019-05-17 WHERE storeid=5009 AND percent_mark = 1 AND sum_by_pickpercent > 70.1 AND sum_by_pickpercent < 80 AND skucode in (1547548) ORDER BY qty DESC LIMIT 2500 
```

**Comment by WhisperLoli** [comment]
其实解析SQL语法这段，是交给druid来做的，可能和druid版本有关，但是更换druid版本不知道会不会兼容

**Comment by shi-yuan** [comment]
mapping里sum_by_pickpercent是什么类型？

**Comment by shi-yuan** [comment]
最新版已经把druid升级到最新了

**Comment by WhisperLoli** [comment]
mapping中sum_by_pickpercent给的是double类型，因为要比较数值大小，不能设text/keyword类型。
我们线上用的es5.2.2，不清楚版本用最新druid会不会有问题，如果这个版本用不了最新版druid，那么这个版本的es-sql可能就会一直存在问题，包括其他使用低版本druid解析的es-sql

**Comment by WhisperLoli** [comment]
试了一下最新版本的druid，里面没有MySqlSQLColumnDefinition这个类，但是es-sql引用了这个类解析columns，所以也是不行

**Comment by shi-yuan** [comment]
本地测试，发现没问题的噢：
```json
curl -XPUT 127.0.0.1:9200/test -d '{
    "settings" : {
        "number_of_shards" : 1,
        "number_of_replicas" : 0
    },
    "mappings" : {
        "test" : {
            "properties" : {
                "sum_by_pickpercent" : { "type" : "double" }
            }
        }
    }
}'

curl -XPUT 'http://127.0.0.1:9200/test/test/1' -d '{
    "sum_by_pickpercent": 78.9999
}'

curl -XPUT 'http://127.0.0.1:9200/test/test/2' -d '{
    "sum_by_pickpercent": 70.9999
}'
```

![image](https://user-images.githubusercontent.com/8057153/58335986-6a3a7480-7e75-11e9-99ae-aeb40852bd61.png)

**Comment by WhisperLoli** [comment]
是的，我直接拿sql在kibana里面也能执行，但是放到程序里面就不行

**Comment by shi-yuan** [comment]
程序里，是调用的_sql，jdbc，还是直接用的searchdao？

**Comment by WhisperLoli** [comment]
程序中用的是SearchDAO

**Comment by shi-yuan** [comment]
这个[commit](https://github.com/NLPchina/elasticsearch-sql/commit/9b139bb9d772fd8fa7c1be147d03e302d44ef499)已被修复，建议用5.x的最新的版本

**Comment by WhisperLoli** [comment]
@shi-yuan 使用5.X的最新版本的话，那我ES是不是也要升级到对应的最新版本啊，目前版本是5.2.2

**Comment by shi-yuan** [comment]
不用的
