### ISSUE TITLE
topHits好像有问题，是我写的不对吗？

### ISSUE THREAD

**Issue by wutiancheng94** [NLPchina/elasticsearch-sql#932]
我执行了下topHits，出了空指针异常
![image](https://user-images.githubusercontent.com/49070709/58413920-870cbd00-80ac-11e9-8b8e-fed558a53810.png)

跟踪源码时发现是这里的问题：
![image](https://user-images.githubusercontent.com/49070709/58414210-4feadb80-80ad-11e9-86ba-4b959c2099c3.png)

我看其他问题上语法也是这样写啊。。。。

**Comment by wutiancheng94** [comment]
用的6.3.0.0版本

**Comment by shi-yuan** [comment]
```sql
SELECT topHits(size=1,alias='salePrice',sale_price='asc') FROM property_index
```
