### ISSUE TITLE
只能filter 不能计算得分吗？

### ISSUE THREAD

**Issue by wutiancheng94** [NLPchina/elasticsearch-sql#939]
我看了解析后的dsl，几乎都是 "filter"，这导致了score都是一样的。。。
请问怎么实现原始的全文检索打分呢？

**Comment by ansjsun** [comment]
order by _score




在2019年06月11日 01:31，wutiancheng94 写道：

我看了解析后的dsl，几乎都是 "filter"，这导致了score都是一样的。。。
请问怎么实现原始的全文检索打分呢？

**Comment by wutiancheng94** [comment]
这样吗？
"SELECT id,subject FROM property_info where q=multimatch(query='j姐',fields='subject.IKS,subject.SPY,subject.FPY,subject.words') limit 10 order by _score"
但是写出来的sql转换成dsl：
{
  "from": 0,
  "size": 10,
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "multi_match": {
                  "query": "j姐",
                  "fields": [
                    "subject.FPY^1.0",
                    "subject.IKS^1.0",
                    "subject.SPY^1.0",
                    "subject.words^1.0"
                  ],
                  "type": "best_fields",
                  "operator": "OR",
                  "slop": 0,
                  "prefix_length": 0,
                  "max_expansions": 50,
                  "zero_terms_query": "NONE",
                  "auto_generate_synonyms_phrase_query": true,
                  "fuzzy_transpositions": true,
                  "boost": 1
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "_source": {
    "includes": [
      "id",
      "subject"
    ],
    "excludes": []
  }
}
这样所有文档的_score得分都是0，这样就不对了。实际上是不应该要外面的那层bool filter才对，请问怎么实现啊？

**Comment by wutiancheng94** [comment]
> order by _score 在2019年06月11日 01:31，wutiancheng94 写道： 我看了解析后的dsl，几乎都是 "filter"，这导致了score都是一样的。。。 请问怎么实现原始的全文检索打分呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

这样吗？
"SELECT id,subject FROM property_info where q=multimatch(query='j姐',fields='subject.IKS,subject.SPY,subject.FPY,subject.words') limit 10 order by _score"
但是写出来的sql转换成dsl：
{
"from": 0,
"size": 10,
"query": {
"bool": {
"filter": [
{
"bool": {
"must": [
{
"multi_match": {
"query": "j姐",
"fields": [
"subject.FPY^1.0",
"subject.IKS^1.0",
"subject.SPY^1.0",
"subject.words^1.0"
],
"type": "best_fields",
"operator": "OR",
"slop": 0,
"prefix_length": 0,
"max_expansions": 50,
"zero_terms_query": "NONE",
"auto_generate_synonyms_phrase_query": true,
"fuzzy_transpositions": true,
"boost": 1
}
}
],
"adjust_pure_negative": true,
"boost": 1
}
}
],
"adjust_pure_negative": true,
"boost": 1
}
},
"_source": {
"includes": [
"id",
"subject"
],
"excludes": []
}
}
这样所有文档的_score得分都是0，这样就不对了。实际上是不应该要外面的那层bool filter才对，请问怎么实现啊？

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/issues/941
