### ISSUE TITLE
请问这种dsl对应的sql该怎么写？谢谢

### ISSUE THREAD

**Issue by wutiancheng94** [NLPchina/elasticsearch-sql#941]
我发现这条sql解析后的dsl是这样的
![ScreenShot00047](https://user-images.githubusercontent.com/49070709/59363270-78d6c600-8d67-11e9-9046-1e7d75648d8d.png)

请问，要获得这样的dsl，对应的sql该怎么写呢？
![ScreenShot00048](https://user-images.githubusercontent.com/49070709/59363533-e84cb580-8d67-11e9-948a-3e496fc4b381.png)
因为我需要每一项的"_score", 而第一种写法的"_score" 全是0

**Comment by shi-yuan** [comment]
```sql
SELECT * FROM student where city = "杭州" order by _score 
```
```json
{
  "from": 0,
  "size": 1000,
  "query": {
    "bool": {
      "must": [
        {
          "match_phrase": {
            "city": {
              "query": "杭州",
              "slop": 0,
              "zero_terms_query": "NONE",
              "boost": 1
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "sort": [
    {
      "_score": {
        "order": "asc"
      }
    }
  ]
}
```

**Comment by wutiancheng94** [comment]
> ```sql
> SELECT * FROM student where city = "杭州" order by _score 
> ```

order by _score  之前试了感觉没有用啊 还报错了。。。

**Comment by wutiancheng94** [comment]
> ```sql
> SELECT * FROM student where city = "杭州" order by _score 
> ```
> 
> ```json
> {
>   "from": 0,
>   "size": 1000,
>   "query": {
>     "bool": {
>       "must": [
>         {
>           "match_phrase": {
>             "city": {
>               "query": "杭州",
>               "slop": 0,
>               "zero_terms_query": "NONE",
>               "boost": 1
>             }
>           }
>         }
>       ],
>       "adjust_pure_negative": true,
>       "boost": 1
>     }
>   },
>   "sort": [
>     {
>       "_score": {
>         "order": "asc"
>       }
>     }
>   ]
> }
> ```
