### ISSUE TITLE
Support of Standrad Deviation an Median

### ISSUE THREAD

**Issue by satapsa** [NLPchina/elasticsearch-sql#97]
Is Standard Deviation and Median supported ? If yes, can you please provide example ?

**Comment by eliranmoyal** [comment]
Not yet, I'll try to implement this later this week

**Comment by satapsa** [comment]
Thanks a lot !! Support for "stats" and "extended_stats"  will be really helpful.

**Comment by eliranmoyal** [comment]
stats already supported :) 
I checked it and it's just not showing good on web interface , i'll fix it.
I will add precentiles and extended_stats

**Comment by satapsa** [comment]
Can you please provide me an example ? I am on version 1.3.5. Do I need to upgrade ? Which version should I upgrade to ?

**Comment by eliranmoyal** [comment]
It should work on 1.3.5
SELECT STATS(age) from accounts

it will only work on http://localhost:9200/_sql?sql=SELECT STATS(age) from accounts
not on web interface (there's a bug there on stats query, i'll fix it)

**Comment by satapsa** [comment]
I donot see the max, min, sum etc coming back though

{"took":45,"timed_out":false,"_shards":{"total":4,"successful":4,"failed":0},"hits":{"total":999,"max_score":1.0,"hits":[{"_index":"xxxx_201506_1000","_type":"locs","_id":"AU-9VqeaORdCmoSZ8Xbw","_score":1.0,"_source":{}},{"_index":"xxxx_201506_1000","_type":"locs","_id":"AU-9VqeaORdCmoSZ8Xb3","_score":1.0,"_source":{}},{"_index":"ookla_201506_1000","_type":"locs","_id":"AU-9VqeaORdCmoSZ8Xb7","_score":1.0,"_source":{}},{"_index":"xxxx_201506_1000","_type":"locs","_id":"AU-9VqeaORdCmoSZ8Xb_","_score":1.0,"_source":{}},{"_index":"ookla_201506_1000","_type":"locs","_id":"AU-9VqeaORdCmoSZ8XcB","_score":1.0,"_source":{}},{"_index":"ookla_201506_1000","_type":"locs","_id":"AU-9VqeaORdCmoSZ8XcF","_score":1.0,"_source":{}},{"_index":"ookla_201506_1000","_type":"locs","_id":"AU-9VqeaORdCmoSZ8XcJ","_score":1.0,"_source":{}},{"_index":"ookla_201506_1000","_type":"locs","_id":"AU-9VqeaORdCmoSZ8XcN","_score":1.0,"_source":{}},{"_index":"ookla_201506_1000","_type":"locs","_id":"AU-9VqeaORdCmoSZ8XcR","_score":1.0,"_source":{}},{"_index":"ookla_201506_1000","_type":"locs","_id":"AU-9VqeaORdCmoSZ8XcV","_score":1.0,"_source":{}},.............................

**Comment by eliranmoyal** [comment]
its on the aggregations section below. at least its like that on 1.4.2 that i'm using

**Comment by satapsa** [comment]
I donot see a aggregation section for the stats. However when I run the same for max I can see the aggregation section
 http://myIP:9200/_sql/?sql=select max(downlaod_kbps) from xxxxx/locs 

---"aggregations":{"MAX(downlaod_kbps)":{"value":null}}}

So seems 1.3.5 is not supporting stats.

**Comment by eliranmoyal** [comment]
Yeah , just wait till tomorrow i'll finish with all you need :)

**Comment by satapsa** [comment]
Thanks a lot . That is great !!

**Comment by eliranmoyal** [comment]
Check it on the newest version 1.4.3
examples can be found on our wiki
https://github.com/NLPchina/elasticsearch-sql/wiki/Beyond-SQL-Features

**Comment by satapsa** [comment]
I have to upgrade the sql plugin to 1.4.3 to access these features ?

**Comment by eliranmoyal** [comment]
Yes

**Comment by eliranmoyal** [comment]
Is this working for you? Can I close this issue?

**Comment by satapsa** [comment]
Planning to check it out today. Need to upgrade the Elastic search. Can you please hold on to it till Monday ?

**Comment by satapsa** [comment]
Hi Eliranmoyal

I upgraded the sql plugin to 1.4.3. It pulls the result for the following. However it does not the Web-ui

http://xx.xxx.xxx.xxx:9200/_sql?sql=select stats(download_kbps) from xxxxxx/locs

http://xx.xxx.xxx.xxx:9200/_sql?sql=select stats(upload_kbps) from xxxxxx/locs

http://xx.xxx.xx.xxx:9200/_sql?sql=select stats(download_kbps),stats(upload_kbps) from xxxx/locs

http://xx.xxx.xx.xxx:9200/_sql?sql=select extended_stats(download_kbps),extended_stats(upload_kbps) from xxxx/locs

**Comment by eliranmoyal** [comment]
Try ctrl+f5? maby the last version is still in your chrome.
Go to http://xx.xxx.xx.xxx:9200/_plugin/sql
And you should get something like this
![image](https://cloud.githubusercontent.com/assets/2933669/10436847/bbe5aa52-7131-11e5-9fe9-879fa78ff280.png)

**Comment by satapsa** [comment]
Yeap.- you are right. I can see the output now. Cool ..

Thank you very much !!
