### ISSUE TITLE
关于“不等于”运算符

### ISSUE THREAD

**Issue by niyanchun** [NLPchina/elasticsearch-sql#974]
你好，关于不等于运算符的问题，有一些疑问：

1. 我试验了一下，不等于运算符现在支持的应该是`<>`这个运算符对吧？后来在issue #429 中也看到了类似的讨论。
2. 在where条件中的不等于可以正确翻译成dsl，我explain了一下，看是翻译成了bool+must not的形式。
3. 但在case when里面使用`<>`，会翻译成script（见下面代码片段），但在painless scrip里面是不认识`<>`运算符的。是不是现在case when里还不支持不等于运算符？还是我的使用有问题？

```
        "fail_num": {
            "sum": {
                "script": {
                    "source": "if((doc['errorcode'].value<>'AAAAAAAAAA') && (doc['errorcode'].value<>'') && (doc['errorcode'].empty)){1} else {0}",
                    "lang": "painless"
                }
            }
        }
```

从我目前对于不等于运算符理解的情况来看，我感觉支持`!=`运算符会更好一些，一方面更通用，`<>`只有在大多数数据库里面才表示不等于，但现在大多数数据库也开始转向`!=`。另一方面，如果是`!=`，转化成script以后，painless也可以正确识别。

**Comment by shi-yuan** [comment]
```sql
select 
case when errorcode not in('AAAAAAAAAA','') then 1
else 0 end errorcode
from alarm
```

**Comment by niyanchun** [comment]
感谢！
