### ISSUE TITLE
请问是否支持 significant text aggregation?

### ISSUE THREAD

**Issue by IggyGao** [NLPchina/elasticsearch-sql#985]
再对text field进行聚合时，会发现速度极慢。而significant text aggregation是用于text字段的聚合方式，初步测试比直接term聚合快1~2个数量级别。具体见https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-bucket-significanttext-aggregation.html#search-aggregations-bucket-significanttext-aggregation

不过在文档和现有issue中都没有找到相关功能，请问是否支持此功能？没有的话，有计划支持吗~感谢！

**Comment by shi-yuan** [comment]
不好意思，目前没有哈，不过这个是可以支持的

**Comment by shi-yuan** [comment]
```sql
SELECT * FROM index GROUP BY significant_text(field='my_field',alias='keywords',size=100,shard_size=100,min_doc_count=1)
```
```json
{
  "from": 0,
  "size": 0,
  "aggregations": {
    "keywords": {
      "significant_text": {
        "size": 100,
        "shard_size": 100,
        "min_doc_count": 1,
        "shard_min_doc_count": 0,
        "field": "my_field",
        "jlh": {}
      }
    }
  }
}
```
