### ISSUE TITLE
how to connect es like oracle. my es version is 5.6.14

### ISSUE THREAD

**Issue by Leehom23** [NLPchina/elasticsearch-sql#987]
our software must use driver to connect es. such as oracle and mysql;
just need drivername and url.
so what should i do to solve this problem.

**Comment by Leehom23** [comment]
[https://github.com/NLPchina/elasticsearch-sql/issues/28#issuecomment-243646949](url)

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/issues/897
