### ISSUE TITLE
Problem with elastic search version 7.1.1 related core x-pack sql plugin

### ISSUE THREAD

**Issue by developer-devPHP** [NLPchina/elasticsearch-sql#992]
```
java.lang.IllegalArgumentException: Cannot replace existing handler for [/_sql] for method: POST
```
I think this happen as elastic search by default reserved route`` /_sql`` for his default ``x-pack sql`` version.
So my suggestion to change this plugin  router with something to not case an issue with elastic core version for example add some prefix.

**Comment by hg199705** [comment]
我刚刚也遇到这个问题，请问你解决了吗？

**Comment by developer-devPHP** [comment]
@shi-yuan  Can you look into this, when you have a time, because I think this will touch all versions which is greater than elaticsearch version 7

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/issues/989

**Comment by developer-devPHP** [comment]
@shi-yuan Thank you very much
`xpack.sql.enabled: false` config helps me
