### ISSUE TITLE
Need to implement track_total_hits functionality

### ISSUE THREAD

**Issue by developer-devPHP** [NLPchina/elasticsearch-sql#997]
Elastic search starts from version 7.0 added property `track_total_hits`
here is official article 
[https://www.elastic.co/guide/en/elasticsearch/reference/7.0/search-request-track-total-hits.html](url)
And for latest version of elastic search this is a documentation for `track_total_hits` property
[https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html](url)

Can we ability to use this property? I think we need some hint for this like 
`/*! TRACK_TOTAL_HITS() */`

**Comment by shi-yuan** [comment]
```sql
select /*! TRACK_TOTAL_HITS(true) */ * from test

select /*! TRACK_TOTAL_HITS(false) */ * from test

select /*! TRACK_TOTAL_HITS(10) */ * from test
```
