### ISSUE TITLE
Response to just show data and not the column header using csv output

### ISSUE THREAD

**Issue by rkhapre** [NLPchina/elasticsearch-sql#999]
How to get Response to just show data and not the column header using csv output

Currently i am using RESTAPI for csv like this
http://xxxx:9200/_sql?flat=true&format=csv&sql=select a,b,c from index

Currently the response comes with the header name, how can i avoid to just get the response only with data and not with the csv headers.

I do not see any parameters in the documentation

**Comment by shi-yuan** [comment]
````
curl -X GET "localhost:9200/_sql" -H 'Content-Type: application/json' -d'
{
	"format":"csv",
	"flat":true,
	"sql":"select a,b,c from index",
	"showHeader":false
}
'
````

**Comment by rkhapre** [comment]
With above solution, i am getting this error. I am using version 6.8.0

```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "request [/_sql] contains unrecognized parameter: [showHeader]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "request [/_sql] contains unrecognized parameter: [showHeader]"
    },
    "status": 400
}
```

**Comment by rkhapre** [comment]
Please open this issue

**Comment by shi-yuan** [comment]
In version 7.4.2.1，![image](https://user-images.githubusercontent.com/8057153/69006785-37c68b80-096f-11ea-9b5e-20499748ec33.png)

**Comment by rkhapre** [comment]
This means i cannot use version 6.8.0

**Comment by shi-yuan** [comment]
Also in elastic6.8.4 branch
